### ISSUE TITLE
Jurisdictions Applications Unclear

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#102]
Located at?  Does that mean physical address of credentialing organization?
Assessment and Learning Opportunities delivered at?  How do we handle multiple options?
Can be used for intended purpose at?  Only licenses are clear on that question  We need to be clear what is being asserted.
What does “valid” mean?
Note: Global jurisdiction question on Sept 19 from global accreditor—what is being asserted?
Note:  University of Phoenix—Advanced Multi-media Development Certificate
Globally: This credential is valid anywhere in the world. (WHAT DOES “VALID” MEAN?)
Specific Places: This credential is valid in these places:
•United States
Not sure how residency restrictions addressed.  For example Advanced Multimedia Development Certificate at University of Phoenix says
Applicable to Residents Of
These conditions have residency restrictions:
Online:

**Comment by jkitchensSIUC** [comment]
@CTITechPlanning @NateArgo need to clean that up.  I agree it's confusing.  Valid is relevant to some certifications that are only Valid in specific geographic areas.

**Comment by stuartasutton** [comment]
I'm sorry. What we are looking at?

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate @CTITechPlanning we're going to create a Google doc covering jurisdiction to show exactly how it is used with each profile and subsequently communicated with the app.

**Comment by stuartasutton** [comment]
The referenced google doc is:

https://docs.google.com/spreadsheets/d/12pOhfAKOV5TwiSJWB_g3elZ20BuWsxoyqOJi6zTddok/edit#gid=0

**Comment by bobgsheets** [comment]
Thanks

**Comment by stuartasutton** [comment]
Some of the questions regarding what does a/the Jurisdiction resource "mean" is dependent on the "verb" used in an assertion (triple) to point a subject resource to a ctdl:Jurisdiction resource; e.g.,

Credential==bannedIn==>Jurisdiction

All an instance of the Jurisdiction entity should do is unambiguously identify a jurisdiction.

**Comment by bobgsheets** [comment]
I am thinking it is the assertions that are the issue to be discussed.  I
think they fall into two buckets.

*Where they can be attained*--we assume somethings that online is always
available everywhere but some types of credentials can only be offered in
states (to state residents) where they are "authorized" to do business.  We
also cannot assume that they are globally authorized either.  We got that
question from an international accreditors on Sept 19 Q&A.

*Where they can be used for their intended purpose*---some credentials are
applicable everywhere in some sense but have different levels
of recognition and value whereas others such as licenses are not.  I think
we need to restrict the definition so that it is different than market
value and gets at the most basic level of "portability" although
portability is sometimes used to refer to what we call connections.  In
most cases, this will apply to licenses and some certifications and mostly
at the state level except for a few such as crane operators which is
sometimes city by city.

I think we need to focus on whether there is any restriction on portability
so people can legally take them and present them anywhere

**Comment by stuartasutton** [comment]
@bobgsheets, so, I think you are agreeing that there are issues with the verbs (properties referencing ctdl:Jurisdiction) **and also** in the definition which currently reads:

> Geo-political informaton [sic] about applicable geographic areas and their exceptions. 

You say: (1) the definition of the class should be adjusted to focus the entity on "portability"; and (2) from your opening sentence, that we need to address the insufficiency of the verbs referencing the class.

I would assume that the definitional issue can and should be tackled now and that we plan to rectify the properties issue in the next release (if they cannot get sandwiched in for the 17th release).

***Proposed Revision to Definition:***

> A geographic or geo-political area of concern to the lifecycle of a resource. 

This change (corrects the current spelling error and) makes the definition of a jurisdiction **absolutely neutral** as to purpose; thus, shifting the burden of meaning to where it belongs on the property (verb) referencing the Jurisdiction class. Then, the goal would be to make sure that the those properties developed focus on:

> Where the resource can be attained; and
> Where the resource can be used for its intended purpose

**Comment by bobgsheets** [comment]
Agree.  I think we should focus on the properties today if posible.

**Comment by bobgsheets** [comment]
Here are some more thoughts on two key issues related to assertions about
jurisdiction


*Credential Use*



Use confuses:

1.       Intended Use--where it is intended to be used

Very subjective and may be hard to pin down

Consider adding jurisdiction to development process in future release



2.       Market Value---where does it have use and value as intended

Add to Labor Market Value in future release

Add to Credential Holder Profile in future release



3.       Legal Restrictions—where it is restricted for use for its intended
purpose

*Address now because of importance to license and certification*

Can be used/Required to Work In---the credential meets requirements for
working in some jurisdictions but not all jurisdictions



*Credential/Learning Opportunity/Assessment Access/Where Made Available*



Need consistent why to handle all Delivery Types—On-line and In-Person



1.       Physical locations where offered for In-Person

2.       Requirements sometime address resident status

3.       Cannot assume that on-line is available everywhere because degree
granting institutions need to seek “state authorization” in a similar way
as institutions wanting to establish physical locations within a state.
But, I am not sure about other types of credentials such as badges,
certifications, etc. who seek state recognition but may not require
authorization.  I will check that out.

**Comment by siuc-nate** [comment]
Worksheet for changes to jurisdiction:
https://docs.google.com/document/d/1fT8F2wBsbiPvWeBiDIaHiBT7HOD_AZXGL862emyOYQU/edit
Specifically columns 3 and 4.

**Comment by siuc-nate** [comment]
Notable updates as of today's call:
- Updated definitions for role related properties
- Added inverse role properties with range of JurisdictionProfile
- Add "assertedBy" property to JurisdictionProfile
- Drop "Assesses" and "assessedIn" and "assessedBy" properties
- Drop "Monitors" and "monitoredIn" and "monitoredBy" properties
- Drop "Confers" and "conferredIn" and "conferredBy" properties
- Drop "Endorses" and "endorsedIn" and "endorsedBy" properties
- Drop "UpdatesVersion" and "updatedVersionBy" properties
- Drop "Owns" and "Owner" properties
- Drop "Contributor" property
- Drop "Validates" and "validatedBy" properties
- Drop "Verifies" and "verifiedBy" properties

**Comment by stuartasutton** [comment]
NOTE that the evaluation of object properties in [Jurisdiction and Role Related Properties](https://docs.google.com/document/d/1fT8F2wBsbiPvWeBiDIaHiBT7HOD_AZXGL862emyOYQU/edit) did **not** include the following:

> [ctdl:evaluatedBy](http://www.credreg.net/page/propertiesviewer#evaluatedBy)
[ctdl:evaluates](http://www.credreg.net/page/propertiesviewer#evaluates)

**Comment by jkitchensSIUC** [comment]
@stuartasutton is there more to do with this issue?

**Comment by jkitchensSIUC** [comment]
This is complete.
