### ISSUE TITLE
Delivery Format and Course Presentation

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#104]
We are capturing information on learning opportunity but do not capture all the different types of direct assessment and competency-based formats that are very important in determining value in time and money, for example:
In the 2014 fall semester, Polk State College will shift the Engineering Technology Associate of Science program to an Open Entry, Open Exit (OEOE) format. The self-paced hybrid format will offer a direct‐assessment and hybrid competency‐based program combining theory development with hands‐on open lab assignments
There is now a number of competency-based education delivery format frameworks that lay out all the options.  I propose we explore how to describe consistent with Course Presentation we had at the TAC meeting.

**Comment by jkitchensSIUC** [comment]
See the LearningDelivery vocabulary in the vocabulary viewer and in the Vocabulary Spreadsheet https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0 

Rows 98 through 106.

See LearningSchedule vocabulary in the vocabulary viewer and in the Vocabulary Spreadsheet https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0 

Rows 107-110 - This includes several terms including competency based.

Do we need to add this to the LearningDelivery vocabulary?
Open Entry, Open Exit (OEOE)

If we want to ask specific questions to the TAC, we need to post to the Google Group. 

We are identifying assessment vocabularies and properties separately from learning opportunities. The assessment vocabulary and properties are under review.  

We'll put this on the next weekly agenda.

**Comment by jkitchensSIUC** [comment]
@bobgsheets Western Kentucky University has an WKU On Demand - Architectural & Manufacturing Sciences http://www.wku.edu/amsondemand/index.php.  "WKU On Demand is excited to offer this personalized learning program which will allow students to use what they know to complete course requirements on a schedule that is convenient for them." It's competency based.  They have a video describing what on demand means https://www.youtube.com/watch?v=qCxZv5y0vI4.

1. self paced.
2. by info you already know.
3.  no traditional semesters or deadlines.
4. paired with personal coach.

**Comment by jkitchensSIUC** [comment]
@siuc-nate need to be sure this is on the assessment and learning opp Visio with one document to review with the agenda tomorrow.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate we covered Learning Opportunity updates here https://docs.google.com/document/d/1KDdOXpCX0b3KyJnvR52hyOOwhbeUCMtBzlLbPZYV1vc/edit?usp=sharing

The notes indicate the following, can this be closed? Didn't @bobgsheets finalize definitions with us?   

Spreadsheet Updates Complete: 
ctdl:deliveryType property added.
Vocabulary spreadsheet DeliveryType updated (new terms added & old deleted).
DeliveryType concept scheme class definition updated.
ctdl:learningDeliveryType property changed to ctdl:deliveryType on LearningOpProfile.

Scope Notes: Don't need to include at this time. May add later

Changes made 2016-11-08:
To AVOID the property name and the vocabulary name being the same, I abbreviated the vocabulary name to LearningMethod.  (Stuart)
Vocabulary concepts added: http://www.credreg.net/page/vocabulariesviewer#LearningMethod

Changes to make Nov 17, 2016:
"LearningFormat" becomes "LearningMethodType"
Add definition to LearningMethodType: "The methods used to conduct the learning opportunity being referenced."
"Contextual" becomes "Applied"
"Lecture/Seminar" becomes "Lecture" and "Seminar" (separate terms)

Spreadsheet Updates Complete:
(SEE ABOVE CHANGE) Property ctdl:learningFormatType added to LearningOpProfile with “@@@” placeholder definition;
(SEE ABOVE CHANGE) ctdl:LearningFormat added to class table with “@@@” placeholder definition;
Top level concepts (yellow highlighting) have been added to a ctdl:LearningFormat vocabulary in Vocabulary Inventory V.2 spreadsheet (https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit#gid=0) -- placeholder definitions using “@@@”

ctdl:deliveryTypeDescription 
Range: Literal
Domain: LearningOpportunityProfile
Definition: A more detailed, refined description of delivery type.
Complete. Learning Opportunity Profile only pending Assessment Profile determination with the Assessment Review Group. 

ctdl:validationMethodDescription 
Range: Literal
Domain: LearningOpportunityProfile, Credential, VerificationProfile
Definition: Description of the methods used to evaluate the validity and reliability.
Complete. Learning Opportunity Profile only pending Assessment Profile determination with the Assessment Review Group. 
Spreadsheet Updates Complete:
property added to the three domains;
validationProcess property referencing ProcessProfile deleted from Credential and AssessmentProfile
NOTE: In the deleted validationProcess property “check and approve” language was used for “validation”. 















Spreadsheet Updates Complete (1) ctdl:deliveryTypeDescriptionproperty added)

**Comment by jkitchensSIUC** [comment]
@stuartasutton can this one be closed?

**Comment by bobgsheets** [comment]
Not sure if I need to respond.  Am checking others before my meeting
starts.

Forgot to ask question on "quality assurance credential"   and how it
relates to definition of credential and relationship to QA action status

**Comment by jkitchensSIUC** [comment]
The question above, "Forgot to ask question on "quality assurance credential"   and how it
relates to definition of credential and relationship to QA action status." is unrelated to this issue. It has been moved to #194
