### ISSUE TITLE
Role Types:  Consistent Definition and Use

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#105]
Not consistently applying role types with some very extensive such as:
Lipscomb University: Organization Roles Assessed By, Conferred By, Created By, Offered By, Owned By
But others have same roles and are just given Owned By and Created By.

Is this a problem in the CTDL and how we use it with the pilot sites?   It is not just one credential but across most of them.

**Comment by jkitchensSIUC** [comment]
That's an issue on our end.  For degree-granting orgs, all of those roles should be consistently defaulted.  We have to clean that up.

**Comment by jkitchensSIUC** [comment]
@CTITechPlanning @siuc-nate we need to review the editor and put quality control on the related properties.

**Comment by stuartasutton** [comment]
Some variance will likely be the case when and if people submit data that has been generated by editors other than "the editor". I.e., you can control your entry point through guidelines and programmatic constraints (perhaps), but not likely to be able to control data from external sources where such consistency is not deemed a priority. "Inter-indexer" consistence is a classic problem that no one has solved. Even consistency across records with a single indexer is not frequently achieved.

**Comment by siuc-nate** [comment]
The relevant updates for service type are here:
https://docs.google.com/document/d/1nS5ToAST0tIFn3DK3tSpxwkExzmfIP9pVizgTXc8SZ0/edit

They mirror the updates to roles we did when working with Jurisdictions.

**Comment by jkitchensSIUC** [comment]
@stuartasutton can this one be closed?

**Comment by jkitchensSIUC** [comment]
This is complete.
