### ISSUE TITLE
Subject Area: How Do We Address?

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#106]
Options:
Allow them to refer to external subject categories such as CIP (although it was developed for programs, it can and is used more widely)
Suggest other controlled vocabularies for subject headings
Add them from competency headings and course headings
Allow them to just name them
Other?

**Comment by jkitchensSIUC** [comment]
We need to go over this with the next meeting. We have both CIP codes and subjects.  CIP codes are only applicable to learning opportunities. 

We have controlled vocabulary for CIP but alternative is subjects.
We have controlled vocabulary for occupations (i.e. SOC) but also have text option for occupations that do not have SOC codes.
We have a controlled vocabulary for industry (i.e. NAICS) but also have text option for industries that do not have NAICS codes.
We have a controlled vocabulary for military occupations (i.e. MOCs).

The text option is based on the actual terms used by the organization.

**Comment by stuartasutton** [comment]
@bobgsheets, I think it is important to distinguish between what the CTDL enables and what the CER uses/deploys. Second, the ctdl:subject property **technically** accommodates all of what you set out in your comment.  

As defined, the ctdl:subject property [1] is applicable to description of credentials, assessments, and learning opportunities. It has as potential values (range) ***either*** text (free fill-in of actual terms used) or concepts from an open-ended array of controlled vocabularies.  That's what is technically enabled by the CTDL. 

Separate matter--what gets implemented in CER. What's implemented can require: 

1. both options (free & controlled), 
2. just one option (free only, controlled only) 
3. if controlled : (a) specified vocabulary, (b) specified set of vocabularies, (c) open ended from unspecified vocabularies of the right classes (e.g., the set of vocabularies for industry classifications).

So, are their other controlled vocabularies not specifically included? Most likely. Those enumerated so far are pretty much U.S. only (except (ESCO) and probably not even all of the potential U.S. vocabularies. So, adding (continuously) to a suggested list of controlled vocabularies for various notions (occupations, industries etc.) would be good and ***doesn't affect the formal specification.*** BUT, to the extent you want consistent discovery, the more heterogeneous the data, the less useful the data is absent massive cross-mapping efforts. It's the old question--do you allow anything or push toward some level of data consistency.

[1] http://www.credreg.net/page/propertiesviewer#subject
