### ISSUE TITLE
Discussion of encoding of CER "Credential 6"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#108]
First, GitHub would not accept a .json file extension for upload, so the attached a .txt file which it would accept.

The **_attached file**_ 

> [Credential_6.txt](https://github.com/CredentialTransparencyInitiative/vocabularies/files/508541/Credential_6.txt)

 is the edited json metadata for credential no. 6 in the CER:

> https://credentialfinder.org/detail/credential/6

With one exception that we can discussed on  today's call (since I need to demo the problem), the edits bring the metadata into alignment with the CTDL. That issue needing demonstration has to do with absolutely no entity represented in the metadata having assigned URI. In JSON-speak, each @type (BachelorDegree, JurisdictionProfile, etc. etc.) needs an "@id" that is either a URI or a nodeID. As a result of not having them, this data cannot survive on the open web. BUT, easier demo'd than explained. I'll do a JSON-2-JSON conversion of the code that will make the issue (and solution) quite clear.

There are several places where I have actually augmented the data --e.g. with the CredentialAlignmentObjects for the O*Net concepts etc. and where we actually have URI to our own vocabularies and the frameworks actually have names etc. There were also a couple of purposeType entries in the original metadata that are not in our controlled vocabulary, so I eliminated them here. Also some had codeNotations that I could not see where they came from. 

There is one place where I have augmented throughout and that is with the addition of language tags ("en-US") to all literals represented in the English language. There can be no "default" assumptions because they only hold within a closed system. In the wild, best practice says human language literals must have language tags. It's a lot of changes in the code, but very, very algorithmic. 

Stuart

**Comment by stuartasutton** [comment]
Ooops, caught a coding error.
[Credential_6-rev.txt](https://github.com/CredentialTransparencyInitiative/vocabularies/files/508642/Credential_6-rev.txt)

**Comment by stuartasutton** [comment]
After sending you Credential_6.txt, I took the code and ran it through an RDF parser that generates an actual graph. I was not pleased. The resource URI in the object position of triples were being generated as literals (i.e. the text of the URI) and not a "things". Translated: that means there were no links in the graph. So, I learned yet another lesson about JSON.  The only thing that forms a link is an "@id". So, I went through the JSON again, this time turning every (or almost every) instance of the text of a URI into an @id expression.

Thus, things like this:

     "ctdl:creator": [ 
                     "http://www.wgu.edu"
     ],
...became things like this:

     "ctdl:creator": [ 
                     {"@id": "http://www.wgu.edu"}
     ],

**Comment by siuc-nate** [comment]
The serializations page has been updated after we discussed this: http://credreg.net/page/serializations

Can we close this issue?

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton putting this on the agenda for tomorrow.

**Comment by jkitchensSIUC** [comment]
@siuc-nate is this addressed?

**Comment by siuc-nate** [comment]
This was handled, but I don't have access to close the issue.
