### ISSUE TITLE
Property ranges from vocabulary class to credentialAlignmentObject

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#109]
I want to sweep through the properties that have vocabularies as range and those ranges from their vocabulary classes to CredentialAlignmentObject. While not wrong as they are, it might be easier for people implementors to understand if the range was consistently CredentialAlignmentObject and the usage note explained where a specific vocabulary is required or considered best practice and the vocabulary class where a more open use of "any vocabulary of the class". 

Since we are already implementing vocabularies using CredentialAlignmentObject, I am going to go ahead and execute.

**Comment by siuc-nate** [comment]
Sounds good to us

**Comment by stuartasutton** [comment]
I think I have caught them all. I have also added a "best practice" to usage for each instance that says for Credentials intended for the Credential Engine Repository to use the specific CTDL vocabulary.
