### ISSUE TITLE
Organization: add availabilityListing

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#112]
It makes sense that an organization could have many locations it would want/need to provide.

**Comment by stuartasutton** [comment]
Are you suggesting that availabilityListing have CredentialOrganization added as domain? What does available even mean when it is an organization?

**Comment by siuc-nate** [comment]
It is probably not the most semantically smooth thing, I suppose, but some property to be used to provide a list of physical and/or online locations where an organization exists would be useful.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

Corrected and added to CredentialOrganization:

> http://www.credreg.net/page/propertiesviewer#availabilityListing
