### ISSUE TITLE
Resolve differences between "offeredBy" properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#113]
https://docs.google.com/spreadsheets/d/1uZbr8R19IB7M6xwwurX9Pssuxm5HGppCLqRV8MixSIU/edit#gid=1368515968
Rows 33-36
This is an example where, I believe, "providedBy" was renamed to "offeredBy" - resulting in duplicitous "offeredBy" properties with different definitions.  There may be a need to resolve the differences between these definitions, but this is most likely just a matter of needing to remove the former "providedBy" rows altogether.

There may be other instances of this duplication from renaming.

**Comment by stuartasutton** [comment]
It appears that you have already removed the providedBy instances. I would suggest a definition like "An agent that provides or presents a resource."

**Comment by siuc-nate** [comment]
They are still present in the indicated rows (specifically 35 and 36) though they are currently also named "offeredBy"

**Comment by siuc-nate** [comment]
The spreadsheet needs to be updated.  I also found duplicates on rows 1348 and 1349.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate looks like the duplicates from 1348 and 1349 were removed but we still have duplicates in rows 34 and 35.  Stuart will you delete the duplicates or would you like us to handle?

**Comment by siuc-nate** [comment]
Note: these duplicate rows are still present:
![image](https://cloud.githubusercontent.com/assets/21346519/19985337/3591d51c-a1e0-11e6-9e92-f03f90b0619e.png)

**Comment by siuc-nate** [comment]
I have removed the identical/duplicate rows.
