### ISSUE TITLE
Suggestion: rename "providesAdvancedStanding" to "advancedStandingFrom"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#114]
This would bring it grammatically in line with the other properties that point to Condition profile, e.g.:

Credential requires [Conditions]
Credential recommends [Conditions]
Credential isRequiredFor [Conditions]
Credential isRecommendedFor [Conditions]
Credential (has) renewal [Conditions]
Credential (provides) advancedStandingFor [Conditions]
Credential (receives) advancedStandingFrom [Conditions]

otherwise that last one would read
[Conditions] providesAdvancedStanding (for) Credential

which is inconsistent with the others, and makes it hard to determine at a glance what the difference is between "advancedStandingFor" and "providesAdvancedStanding"

**Comment by siuc-nate** [comment]
Our team met and agrees with this.

Would it be better to use "providesAdvancedStanding" and "receivesAdvancedStanding" or to use "advancedStandingFor" and "advancedStandingFrom"?

**Comment by siuc-nate** [comment]
Per our meeting yesterday, we also need to add:

Credential preparesFor [Conditions]
Credential preparationFrom [Conditions]

**Comment by siuc-nate** [comment]
Following our meetings and discussions, the revised list is:

Credential requires [Conditions]
Credential isRequiredFor [Conditions]

Credential recommends [Conditions]
Credential isRecommendedFor [Conditions]

Credential advancedStandingFrom [Conditions]
Credential isAdvancedStandingFor [Conditions]

Credential preparationFrom [Conditions]
Credential isPreparationFor [Conditions]

Credential hasPart [Credential]
Credential isPartOf [Credential]

Credential isSimilarTo [Conditions]

**Comment by bobgsheets** [comment]
I think this looks good.  I only have two remaining questions before we close this out.

1. We are pulling "recommended for" from our existing properties and we need to be clear what this is saying versus "prepared for" 

2.  In addressing pathways, we need to allow people to: (1) reference a pathways framework (e.g., CompTIA pathways model) and say that is where I fit and (2) make specific assertions regardless of pathway framework about pathway connections with one or more other credentials.   As a result, I would like to see us explore a more comprehensive credential connections vocabulary that includes the four education and career pathway assertions.

**Comment by siuc-nate** [comment]
Thanks, Bob

We need to nail down exactly what a Pathway object is. What are its properties, what is it used for, who creates it, what does it look like, etc.? Is it a map or sequence of credentials? Is it a tree or graph of related credentials that may not necessarily have a prescribed order? Is it something else entirely?

Once we have defined a Pathway, we can figure out how and where it fits into the rest of our schema.

**Comment by siuc-nate** [comment]
I have taken the following actions in the spreadsheet:

1. Renamed "ctdl:advancedStandingFor" to "ctdl:isAdvancedStandingFor"
2. Renamed "ctdl:providesAdvancedStanding" to "ctdl:advancedStandingFrom"

**Comment by siuc-nate** [comment]
I have renamed "ctdl:recommendedFor" to "ctdl:isRecommendedFor"

@stuartasutton @bobgsheets 
We have created a document to better track and discuss these changes:
https://docs.google.com/document/d/1uqBiM0uKCNpKRSNmH9ZPV6qmiYY0CfQsYEIS02WRQEM/edit

It contains current and proposed updates to properties and definitions as of the time of this post.

**Comment by stuartasutton** [comment]
I have split off the Credential-to-Credential relationships (connections) to a new issue #150; separating it from the Career Pathway which deserves its own issue.

**Comment by jkitchensSIUC** [comment]
Closing this because it was split off into #150 and #47
