### ISSUE TITLE
Add resourceUrl to Profiles

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#116]
This should be added to:
- Credential
- Organization
- ProcessProfile
- RevocationProfile
- VerificationServiceProfile

**Comment by stuartasutton** [comment]
Can we talk about this? If you add these schema:url properties to profiles, you are asking people creating the metadata to fill in the blanks. That does not comport very well with the discussion on Tuesday.

**Comment by siuc-nate** [comment]
Our handling of this should certainly be consistent - but we should circle back around and discuss this when we get a chance.

**Comment by jkitchensSIUC** [comment]
Putting this on the agenda for tomorrow.

**Comment by stuartasutton** [comment]
@siuc-nate & @jkitchensSIUC, we did not get to this on our call Tuesday. Nate, 'need' is the goal, not 'consistency'. Having properties with a class that people don't need adds to the complexity and issues of choice that emerged in yesterday's call. **Do each of these classes actually need this property?** 

We've discussed this property before -- [ctdl:resourceUrl](http://www.credreg.net/page/propertiesviewer#resourceUrl) is a big invitation to soft spam.  We warn about how it should be used moderately in the usage note; but, it is has a role no more definitive definition than "want to point us to something else"?.

**Comment by siuc-nate** [comment]
I believe we've encountered cases where it would be useful (such as pointing to webpages or PDFs) in at least a few of the profiles mentioned above - but I do not remember offhand which ones. @jkitchensSIUC could probably tell you more clearly/authoritatively than I could.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @mparsons1953 not sure why this is being deferred to me.  This is on the agenda for review this week.

**Comment by siuc-nate** [comment]
It might also be worth coming up with a consistent name for the properties that are explicitly intended to be URLs (ie to external things not in CTDL), even though all of them are technically objects within RDF

**Comment by jkitchensSIUC** [comment]
@siuc-nate we're not using ResourceURL.  Isn't the open issue for URLs #158 ? Close this issue and have one issue for the URL wrap up.
