### ISSUE TITLE
CredentialAlignmentObject: rename "credentialFrameworkUrl" to "competencyFrameworkUrl"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#119]
https://docs.google.com/spreadsheets/d/1uZbr8R19IB7M6xwwurX9Pssuxm5HGppCLqRV8MixSIU/edit#gid=1368515968
Row 273

**Comment by stuartasutton** [comment]
No, Nate. Competency frameworks are just one kind framework that is referenced. If anything, cut it back to "frameworkUrl" and make it neutral.

**Comment by siuc-nate** [comment]
Makes sense.  I assume this would also apply to the name (i.e., "frameworkName")?

**Comment by stuartasutton** [comment]
Go ahead and make them. They seem quite reasonable.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

1. credentialFrameworkUrl changed to frameworkUrl; and
2. credentialFramework changes to frameworkName.
