### ISSUE TITLE
Credential versus Learning Opportunity:  Assessments, Costs, and Time to Earn

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#120]
Many times we are describing assessments that are tied to the credential (e.g., assessments for certifications independent of any learning opportunity) and others tied to the learning opportunities (e.g., assessments in courses).   Does CTDL make this distinction and can we capture both?

Same with costs.  Sometimes it is cost of standalone assessments and others it is learning opportunity that includes assessment.   Does CTDL make this distinction and can we capture both?

Same with Time to Earn.  Sometimes we are talking about the assessment (e.g., certification exam) and it is in hours and other times we talk about learning opportunities that last 4 years.  Does CTDL make a distinction between assessments  (certifications and direct assessment options in degrees) and learning opportunities?

**Comment by siuc-nate** [comment]
Yes to all:
- LearningOpportunityProfile has the ability to reference an AssessmentProfile
- Both profiles maintain their own independent CostProfiles
- Both profiles maintain their own independent DurationProfiles

**Comment by stuartasutton** [comment]
Can this issue be closed?

**Comment by jkitchensSIUC** [comment]
@siuc-nate @bobgsheets let's do a quick example during our meeting tomorrow so we can be sure Bob's good with this and close this issue.

**Comment by jkitchensSIUC** [comment]
During the CTDL release review @bobd @stuartasutton @siuc-nate determined this issue can be closed.
