### ISSUE TITLE
AssessmentProfile: add instructionalProgramType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#122]
This would be the same as what is used in LearningOpportunityProfile.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton is this update needed http://credreg.net/page/propertiesviewer#instructionalProgramType 

Currently, the domain for instructionalProgramType is only LearninOpportunityProfile.  

http://credreg.net/page/propertiesviewer#instructionalProgramType

**Comment by siuc-nate** [comment]
Yes, this is the property that will allow us to tie an assessment to a CIP code.

**Comment by jkitchensSIUC** [comment]
@stuartasutton can this be updated for the release?

**Comment by jkitchensSIUC** [comment]
Added Domain of AssessmentProfile to instructionalProgramType.

This is complete.
