### ISSUE TITLE
Add recommends property to AssessmentProfile and LearningOpportunityProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#123]
This would work just like it does with Credential.

**Comment by siuc-nate** [comment]
Documented here:
https://docs.google.com/document/d/1Mb9VlGVKQiS7STbWL9uU7Rux3sjIc3wywBz770NWrhk/edit#

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate looks like this needs to be updated in the spreadsheet.  http://credreg.net/page/propertiesviewer#recommends

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

Added AssessmentProfile and LearningOpportunityProfile to to the domain list of the recommends property. **BUT** do you actually mean the class Assessment and the class LearningOpportunity and not their profiles (we have both)?

**Comment by siuc-nate** [comment]
Nope, the intent was to add it to the profiles.  I believe this can be closed now.
