### ISSUE TITLE
Requirements:  Admission versus Good Standing to Continue

### ISSUE THREAD

**Issue by bobgsheets** [CredentialTransparencyInitiative/vocabularies#124]
In most cases with universities and colleges, they describe requirements into two buckets:
1. Admission requirements to qualify to enter credential learning opportunity--program of study.
2.  Maintaining good standing--being able to continue and complete (e.g., grade point avg).

Does CTDL distinguish those two buckets of requirements?

We usually list them together in WorkIt app.

**Comment by siuc-nate** [comment]
Under the current way CTDL works, all requirements are grouped together for a given route. 1 condition profile = 1 complete set of requirements to attain the credential. So yes, there would be a single ConditionProfile that provides both the admission and good standing requirements.

**Comment by jkitchensSIUC** [comment]
@bobgsheets @siuc-nate let's do a quick example of this during our meeting tomorrow.

**Comment by stuartasutton** [comment]
@siuc-nate, you say:

> "Under the current way CTDL works, all requirements are grouped together for a given route. 1 condition profile = 1 complete set of requirements to attain the credential. So yes, there would be a single ConditionProfile that provides both the admission and good standing requirements."

But the fact that one instance of ConditionProfile handles all the requirements for a single "route" doesn't answer the question. I think @bobgsheets is asking whether ctdl:requires (etc.) can be more precise to meet more specific circumstances (e.g., something like this property/subproperty set):

**ctdl:requires**
> ***ctdl:requiresForAdmit*** (subproperty of ctdl:requires)
> ***ctdl:requiresToContinue*** (subproperty of ctdl:requires)

Am I correct @bobgsheets?

**Comment by siuc-nate** [comment]
If a single ConditionProfile didn't encompass all of that, then wouldn't "maintaining good standing" be handled by ctdl:renewal (a ConditionProfile defining renewal terms) and/or ctdl:revocation (a RevocationProfile defining revocation terms)?

**Comment by stuartasutton** [comment]
If so, @siuc-nate, then that would handle @bobgsheets distinction.

**Comment by jkitchensSIUC** [comment]
During CTDL review today, we determined this is not an issue at this time.
