### ISSUE TITLE
Need to include financing and financial aid information

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#125]
We would need to determine whether this would be a part of cost profile or of assessment/learning opportunity/task/etc.

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate whether or not a learning opportunity or assessment or credential qualifies for financing and financial aid is lacking from CTDL. For example, the military COOL sites that identify civilian credentials that are approved by military branches and they provide filtering for: Navy Bucks Funded and GI bill  http://www.cool.navy.mil/usn/overview/resource_icons.htm.  Putting on agenda for tomorrow.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate can this be closed?

This was reviewed with Learning Opportunity https://docs.google.com/document/d/1KDdOXpCX0b3KyJnvR52hyOOwhbeUCMtBzlLbPZYV1vc/edit#

Notes indicate, Changes to make:
Add "FinancialAlignmentObject" class (subclass of CredentialAlignmentObject)

ADDITION COMPLETE (2016-11-08):
http://www.credreg.net/page/propertiesviewer#FinancialAlignmentObject

**Comment by siuc-nate** [comment]
Yes, it is now handled.
