### ISSUE TITLE
Addressing earning of credit hours

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#126]
Some of the use cases we've come across involve the need to indicate where (and to what extent) completing something (such as a learning opportunity or an assessment) will award [usually college] credit hours to the user.  

I think this could be done with an alignment object (or something similar) - the credit hours system being the framework (e.g., carnegie) and some other property indicating the number of credits awarded along with any other relevant descriptive data. This would allow for non-college credits to be awarded as well.

I am not well-versed on the details of how credits work across different institutions - so I will have to lean on Stuart and Bob for this one.

**Comment by jkitchensSIUC** [comment]
The new property would need to be named something like "creditsAwarded."  Putting on agenda for tomorrow.

**Comment by stuartasutton** [comment]
With something like creditsAwarded would work. Anyway to align with properties in [schema:Course](http://pending.schema.org/Course)?

Is this something that would be better served with a dedicated type (it's not really fodder for AlignmentObject). It would seem that one would need the creditValue awarded and the creditUnit (a vocabulary? Like with [Course](http://pending.schema.org/Course) -- "NoCredit", "Quarter", "Semester", "CarnegieUnits", "ContinuingEducationUnits", "ClockHours" etc..

**Comment by jkitchensSIUC** [comment]
These are more examples of credits awarded:
CEUs, CPDUs and PDUs

- Continuing Education Units
- Continuing Professional Development Units
- Professional Development Units

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate can this be closed?

This was part of the Learning Opportunity Review https://docs.google.com/document/d/1KDdOXpCX0b3KyJnvR52hyOOwhbeUCMtBzlLbPZYV1vc/edit?usp=sharing

Notes on the Google document state, Spreadsheet Updates Complete:
creditUnitType property added to the three domains;
CreditUnit concept scheme created and recorded in Class spreadsheet and Vocabulary Inventory V2 spreadsheet.
Property creditUnitTypeDescription added to Properties spreadsheet
Property creditUnitValue added to Properties spreadsheet
Property creditHourType added to Properties spreadsheet
Property creditHourValue added to Properties spreadsheet

Note: Should the CreditUnit concept “Academic Credit” scope note encompass “primary, secondary and adult education”. Original was K-12 and we changed it to “secondary (K-2)”. But K-12 includes primary.

**Comment by siuc-nate** [comment]
Updating the scope makes sense to me.  Otherwise yes, it appears this can be closed. @stuartasutton do you want this issue left open until the scope is changed?

**Comment by jkitchensSIUC** [comment]
I'm closing this issue. We didn't use ctdl:AcademicUnit. Instead we used ctdl:SecondaryDiplomaCredit.  Its definition is Credit that is issued or accepted for a secondary diploma.  The scope not is: Includes credits earned while enrolled in a secondary diploma program that meet graduation requirements.  This was agree upon during the review with Bob, Stuart, Nate and Jeanne.
