### ISSUE TITLE
CostType vocabulary: add "fees"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#127]
These would be any charges over and above tuition. Refer to cost type spreadsheet.

**Comment by stuartasutton** [comment]
Perhaps "OtherFees" since most consider the other categories as "fees" and then the disambiguating language of "over and above tuition".

**Comment by siuc-nate** [comment]
Sounds good to me.

**Comment by stuartasutton** [comment]
How is this issue impacted by issue #140?

**Comment by siuc-nate** [comment]
Presumably "OtherFees" would just be added to the list Jeanne provides in that issue as a catch-all for everything that isn't a part of that list.

**Comment by siuc-nate** [comment]
Is the intent of this term covered instead by the "optionalCharges" term?

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton The Google Sheet used for the updates made with #140 is https://docs.google.com/spreadsheets/d/19--mCccXkLeCxxQ74c1lx5_k31FCIyk-d-PRqHgQqls/edit?usp=sharing

This issue predates the review and updates with #140.  Looking at the types of costs, Optional has a different meaning from OtherFees.  As we talked about, optional fees imply they are optional.  OtherFees makes more sense as the catch all.  Is this being added?

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton I just updated the vocabulary based on https://docs.google.com/spreadsheets/d/19--mCccXkLeCxxQ74c1lx5_k31FCIyk-d-PRqHgQqls/edit?usp=sharing

The thread also talks about needing: ctdl:OtherCharges? We have ctdl:OptionalCharges.  I don't see other and optional meaning the same thing.  Optional means charges are optional but other means, other charges.  We need to get this once closed out.  

The ctdl:CostTypes include:

- costType:AggregateCost
- costType:Application
- costType:BackgroundCheck
- costType:EnrollmentFee
- costType:RenewalFee
- costType:LearningResource
- costType:Meals
- costType:ProcessingFee
- costType:ProgramSpecificFee
- costType:ReexaminationFee
- costType:ReschedulingFee
- costType:ScoringFee
- costType:StandaloneAssessment
- costType:StudentServicesFee
- costType:TechnologyFee
- costType:Tuition
- costType:RoomOrResidency
- costType:OptionalCharges

**Comment by jkitchensSIUC** [comment]
Determined we should not add OtherFees to this vocabulary.  This is complete.
