### ISSUE TITLE
Extend Applicable Audience vocabulary

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#129]
We need to discuss additional terms, such as "employer", "teacher/educator", etc., and other audiences (like the ones indicated on the home page of the prototype)

**Comment by jkitchensSIUC** [comment]
@stuartasutton @bobgsheets @siuc-nate originallly...or sometime in the past...we talked about audience in terms of who is the audience for the credential/credentialing services. For example, we have NOCTI Business and their audience is businesses.  We have Audience currently in cost and condition profile as follows:

ctdl:Audience	Citizen
ctdl:Audience	CurrentMilitary
ctdl:Audience	CurrentStudent
ctdl:Audience	FormerMilitary
ctdl:Audience	FormerStudent
ctdl:Audience	Member
ctdl:Audience	NonCitizen
ctdl:Audience	PrivateEmployee
ctdl:Audience	PublicEmployee

Putting on agenda for tomorrow.

**Comment by siuc-nate** [comment]
We need to add a "Nonmember" term to this vocabulary.

**Comment by mparsons1953** [comment]
Not sure if comment is appropriate here, but I have a concern with the interpretation of applicable audience versus specific audience. We had discussed previously this and this may be more of a guidance task, and not an issue.
As an example for credential 1205, Renewal requirements:
https://credentialfinder.com/editor/credential/1205
As shown below, people will commonly pick every option. Should the guidance be to only select an audience type if the condition is **not** applicable to all? 
As was discussed previously, if:
- people pick all, 
- and then new vocabulary (say **Resident Alien**) is added 

Any conditions created before the addition of new vocabulary will appear to NOT be applicable to a new term.
![applicable audience](https://cloud.githubusercontent.com/assets/16601156/19900834/e79d8f12-a032-11e6-8b56-d2969a4e27f6.PNG)

**Comment by siuc-nate** [comment]
Additional updates:
https://docs.google.com/document/d/1hRUMQ7kvdSDDO8A4dTWig5Yo7fpFFbX0zPmvfRl1OgQ/edit

Note updates to the definitions, usage notes, terms, etc.

**Comment by jkitchensSIUC** [comment]
@stuartasutton I made all of the definition updates to the vocabulary. Only one update is left.

For  URI: Audience 

- Change  the definition to The types of audiences for which the resource being described is applicable or available.
- Change the comment to If the resource is applicable or available for any type of audience, do not select anything.

Also, do we need to deem this one unstable?  See our note from the review of ctdl:audienceType indicating this is likely insufficient beyond the cost and condition profile use.

Sorry, I would have updated this definition but I'm not really sure how the two spreadsheets work together now.

**Comment by jkitchensSIUC** [comment]
Updated definition and comment. This is complete.
