### ISSUE TITLE
AssessmentProfile: add "version" property

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#130]
This would work the same way as it does on Credential.  We need to discuss whether or not LearningOpportunityProfile needs a version property as well.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @bobgsheets @siuc-nate NOCTI's assessment blue prints all show a version number http://www.nocti.org/PDFs/JobReady/1437_21st_Century_Skills.pdf

![image](https://cloud.githubusercontent.com/assets/20917206/19742255/c50cfe04-9b89-11e6-8b47-17d433fd5b46.png)

**Comment by stuartasutton** [comment]
I see no problem with adding a [ctdl:versionIdentifier](http://www.credreg.net/page/propertiesviewer#versionIdentifier) to any entity in the model that needs it. The range of versionIdentifier is the class IdentifierValue which let's one explain the identifier as well as provide it. Currently, only Credential has a versionIdentifier property. We'd just need to expand the property's domain.

**Comment by jkitchensSIUC** [comment]
Will ctdl:versionIdentifier http://credreg.net/page/propertiesviewer#versionIdentifier be updated to include Assessment Profile? Learning Opportunity?

**Comment by jkitchensSIUC** [comment]
Added Domain of AssessmentProfile to versionIdentifier.

This is completed.
