### ISSUE TITLE
Enable indicating standards compliance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#131]
we need to be able to indicate standards compliance in at least three ways: 
1. ProcessProfiles that follow standards
2. QA awards that indicate standards met
3. Learning Opportunities and Assessments that follow standards.

For example:
"NOCTI and Nocti Business Solutions have earned full accreditation from the International Certification Accreditation Council (ICAC). This recent accomplishment ensures that a neutral third party has properly evaluated both organizations and held them up to international standards. ICAC accreditation signifies that NOCTI's career and technical education (CTE) assessments and certifications, as well as Nocti Business Solutions' technical skill assessments, follow the best international industry practices and standards outlined in **ISO 17024**."
http://www.nocti.org/index.cfm

This is based on feedback we received from NOCTI.

Would this require addition of another property? Or would we overload the current use of AlignmentObject in various places?

**Comment by stuartasutton** [comment]
Don't we already do this with organizations and credentials? E.g., the example is a straight forward accreditedBy, isn't it? The International Certification Accreditation Council (ICAC) has a framework it uses to accredit--ISO 17024--by which NOCTI is accredited. So NOCTI can assert an accreditedBy the International Certification Accreditation Council (ICAC) has a framework it uses to accredit--ISO 17024. So NOCTI can assert an accreditedBy and the Council can issue an AccreditAction with an instrument of ISO 17024.

Now, that is a organization and credential. Are you saying that these actions need to be extended to Process Profile, Learning Opportunities, Assessments, and Processes?

**Comment by siuc-nate** [comment]
What you say makes sense - my thinking on this was very similar, though I figured there would need to be a credential representing compliance with that standard.  Perhaps that is a by-product of also building the prototype.

Anyway, to your question, this is another case where @jkitchensSIUC would be better suited to clarifying her intent with this issue than I would be. However, I believe the intent was to allow what you suggest: to say that processes and so on are themselves compliant with given standards.

**Comment by jkitchensSIUC** [comment]
Could this be accomplished by just adding another property to ProcessProfile, Assessment, LearningOpportunity, and Credential (something like "targetStandard")?  This would point to an CredentialAlignmentObject that would in turn point to the associated standard.

**Comment by stuartasutton** [comment]
Let me see if I can summarize what I see here:

 1. We have a way for for NOCTI to assert that it has been "accreditedBy" ICAC; and 
 2. We have a way for ICAC to take an AccreditAction with the ***object*** being NOCTI and the ***instrument*** being ISO 17024. 

**Is what we are missing is a way in the example for NOCTI to state that the basis of their ICAC accreditation as the practices and standards outlined in ISO 10724?**

**Comment by siuc-nate** [comment]
What we're missing is a way for NOCTI to say that their processes themselves, independent of any organization or other entity, are compliant with a given standard.  Ditto it seems for the other objects (Credentials, Assessments, Learning Opportunities).  I don't know if we would need "targetStandard" or "compliantWith" or something like that - the former might imply that it was the process _for_ a given standard and the latter might be overly specific.  But basically we need to say:

ProcessProfile --compliesWith(?)--> CredentialAlignmentObject --targetUrl--> [ISO standard URL]

**Comment by stuartasutton** [comment]
What's wrong with:

ProcessProfile --compliesWith(?)-->[ISO standard URL] 

Is an AlignmentObject really necessary?

**Comment by siuc-nate** [comment]
Technically no, but invariably there will be the desire to communicate a name and description (and probably codedNotation, and possibly framework) of the standard, just like there is with Competencies (particularly if the standard doesn't have a URL and is just text in a PDF alongside other standards, as we have seen with some competencies).

So, to mirror our handling of competencies, I recommend using AlignmentObject.

**Comment by stuartasutton** [comment]
Then handle it when and if it arises. That's not doing it wrong. Its
responding and adding when there is actual need...not "just in case".

**Comment by siuc-nate** [comment]
I understand that, and that may be what we need to do with the metadata. 

As a system developer though, I have to anticipate needs like that as far ahead of time as possible, so it can be difficult separating the two mindsets. It may be a simple addition in RDF terms, but trying to make a system dependent on this property _not_ being an AlignmentObject later needing it _to_ be one can be quite the headache.  Since our metadata is ultimately intended for use by such systems, I can't help but feel the need to push for at least including the option of using an AlignmentObject here, to be consistent with how we handle other things.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton Is this unresloved? Or is this or some aspect of this handled throughto  updates the Process Profile updates #169 ?

**Comment by siuc-nate** [comment]
It appears to still be an issue. I do not know how a process profile would indicate its own alignment to some set of standards. @stuartasutton please correct me if I'm wrong.

**Comment by jkitchensSIUC** [comment]
@siuc-nate we added properties just in the last week to identify if a standard is being followed

**Comment by siuc-nate** [comment]
Which properties?

**Comment by jkitchensSIUC** [comment]
Added Credential and AssessmentProfile to the Domain of:

1. processStandardsDescription
2. processStandards

This is complete.
