### ISSUE TITLE
Learning Opportunity - Credit/Non-Credit

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#132]
We don't identify if a learning opportunity is credit or non credit.  @bobsheets Do we need to include this?

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate this is still open and will be on agenda for tomorrow.

**Comment by stuartasutton** [comment]
Isn't this somewhat related to issue #136?

**Comment by stuartasutton** [comment]
Isn't this related to issue #126?

**Comment by jkitchensSIUC** [comment]
Types of credits was handled with #126 closing this issue.
