### ISSUE TITLE
Apprenticeship as a delivery type for Learning Opportunity

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#133]
@bobsheets Apprenticeship is a method of learning while working and getting paid.  I cannot find where we identify this as a Learning Opportunity delivery method. This is not necessarily related to an Apprenticeship Certificate.  For example, we have an Associate of Applied Science Degree in Advanced Manufacturing Technician with Gateway Community & Technical College that formats the learning opportunity with apprenticeship. Do we need to add "apprenticeship" to the LearningDelivery vocabulary?

**Comment by siuc-nate** [comment]
This would make sense as a part of issue #84

**Comment by jkitchensSIUC** [comment]
On November 17, 2016  this was handled with ctdl:LearningMethod including learningMethod:WorkBased 

Work based includes methods such as apprenticeships, internships, externships, work study, clinical rotations, residencies, practicums, field study, team projects, and cooperative education.

https://docs.google.com/document/d/1KDdOXpCX0b3KyJnvR52hyOOwhbeUCMtBzlLbPZYV1vc/edit#heading=h.dj38qyympd9x

Closing this issue.
