### ISSUE TITLE
Need to handle assessment weightings

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#134]
From @bobgsheets:
We have test map weightings that I thought we were including

We need to discuss this - we are handling these areas of the assessment as competencies but do not have a way of expressing weighting.

http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary

**Comment by stuartasutton** [comment]
@bobsheets, I am not certain I understand. Can you point me to an actual example of a "test map" with weightings? 

The [ctdl:ConditionProfile] (http://www.credreg.net/page/domainsviewer#ConditionProfile) relating an instance of a Credential to an AssessmentProfile has the [ctdl:weight] (http://www.credreg.net/page/propertiesviewer#weight ) that supports expresson of the weight of the relationship of a recommendation, requirement, or comparison of a Credential and an AssessmentProfile (i.e., an Assessment), as well as a TaskProfile, or LearningOpportunityProfile.

I am assuming that your reference to the ASN properties is to those declared for use in stating the strength of fit between that resource and a node in a CompetencyFramework; i.e.: 

1. [**BroadCorrelation**] (http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary#Broad_Correlation)
2. [**ExactCorrelation**] (http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary#Exact_Correlation)
3. [**MajorCorrelation**] (http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary#Major_Correlation)
4. [**MinorCorrelation**] (http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary#Minor_Correlation)
5. [**NarrowCorrelation**] (http://standards.asn.desire2learn.com/index.php?title=ASN_Vocabulary#Narrow_Correlation)

Is this correct?

**Comment by siuc-nate** [comment]
Those enumerations would roughly map to various percentage values of weight (e.g., "exact correlation" = 100% or 1.0).  I would prefer weight (or some similar property that replaces weight, perhaps "correlation"?) to be those 5 terms rather than a plain decimal. 

I think it's probably more useful and easier to understand with those terms and their definitions/constraints, and I do not see much utility in being able to define finely-grained weights (e.g., what is the real-world difference between a weight of 75% and a weight of 78.3%?).

The above terms have the added utility of being able to describe broader and narrower items in addition to useful expressions of weight.

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate isn't the weight for showing the weight of assessment questions in the context of the exam?  Certification and certificate blueprints provide great examples.  One  example we have is NOCTI 21st Century Skills http://www.nocti.org/PDFs/JobReady/1437_21st_Century_Skills.pdf

![image](https://cloud.githubusercontent.com/assets/20917206/19741866/128277ce-9b88-11e6-9a88-832e9cac39e6.png)

**Comment by jkitchensSIUC** [comment]
**Add "weight" property to CredentialAlignmentObject** 

{

"@type": "ctdl:AssessmentProfile",

"ctdl:subject": [

{

    "@type": "CredentialAlignmentObject",

    "targetName": "First Aid and General Safety",

    "weight": 0.19

},

{

    "@type": "CredentialAlignmentObject",

    "targetName": "Medical Terminology",

    "weight": 0.18

}

],

"ctdl:targetCompetency": [

    {

        "@type": "CredentialAlignmentObject",

        "targetName": "Competency Name goes here",

        "targetDescription": "Competency description text body goes here",

        "frameworkName": "Health Assisting Framework"

        "frameworkUrl": "http://health-assisting-framework.com",

        "targetUrl": "http://health-assisting-framework.com/competency/12345",

        "weight": 0.35

    }

]
}

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

The ctdl:weight property has been added to the ctdl:CredentialAlignmentObject; 

 > See http://www.credreg.net/page/propertiesviewer#weight

Barring any other comments, this issue can be closed.

**Comment by jkitchensSIUC** [comment]
Closing issue.
