### ISSUE TITLE
Expand agent QA target type vocabulary

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#136]
Need to include subclasses of credentials and agent types.  This is relevant to the QA stuff we got from Roy:
https://docs.google.com/document/d/144CetlzwrXUyaaC1j_6Nq-AWn7-TlBdxekxn8C3fAOQ/edit#

**Comment by stuartasutton** [comment]
Credentials referenced that are not currently covered appear to be a further subdivision of the existing Certificates (**in bold**):


First Level | Second Level | Third Level
------------ | ------------- | -------------
Certificate |   |  
 | Apprenticeship Certificate |  | 
 |  | Journeyman Certificate  |
 |  |  Master Certificate  | 
 | **Academic Certificate** |  |  
 |  | **Post-Baccalaureate Certificate**
 |  | **Sub-Baccalaureate Certificate**
 |  | **Post-Masters Certificate**
 |  | **Post-Doctorate Certificate**
 |  | **Non-Degree Certificate**
 | **Industry/Professional Certificate** |  |
 |  | **Certificate of Participation**
 |  | **Certificate of Achievement**  
 |  | **Certificate of Completion**
 |  | **Assessment-Based Certificate**

**Comment by siuc-nate** [comment]
So wouldn't a target type of "Certificate" (and the existing apprenticeship related ones) cover this?  I don't think we want/need to add almost a dozen new credential subclasses based on just this.

**Comment by stuartasutton** [comment]
OK, I AM confused. Then what were you wanting added? So, where do we "[n]eed to include subclasses of credentials and agent types"?

**Comment by siuc-nate** [comment]
I will have to defer to @jkitchensSIUC to clarify her original intent on this one as well.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate @bobgsheets this is going on the agenda for tomorrow.  Roy's QA committee determined the QA vocabulary and we two areas where we're currently not addressing the QA committee's requests documented in part here https://docs.google.com/document/d/144CetlzwrXUyaaC1j_6Nq-AWn7-TlBdxekxn8C3fAOQ/edit#.  We have to address the credential types and/or credential subclasses as well as the agent (org) types.

**Comment by jkitchensSIUC** [comment]
@bobgsheets is following up with Roy Swift on this.

**Comment by jkitchensSIUC** [comment]
The updated QA-related classes, properties and vocabulary was documented here
https://docs.google.com/document/d/1Z1CWl_UgcqxjmqIasA_i-0qzYuPqr0zURnddBtvq57I/edit?usp=sharing
