### ISSUE TITLE
Process Profile - rename "assessmentProfile" property to "targetAssessment"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#138]
We had a similar issue with this property on ConditionProfile a few days ago.  Should this be handled the same way?

**Comment by stuartasutton** [comment]
I'm confused. Via #139, instances if assessmentProfile were changed to assessmentProfiled. I think I am failing to grasp the pattern for when a profile instance points **back*** and says "that's the thing I am profiling"...i.e., "I am profiling that", ***and*** when it point forward saying there is the target resource.

**Comment by siuc-nate** [comment]
There are two factors here:
1. ProcessProfile currently has "targetCompetencyFramework", "targetCredential", and "targetLearningOpportunity". This is to enable associating a given process profile with a given target. It needs a property that points to an assessment profile as well.
2. It has no "learningOpportunityProfiled" property because there is no learning opportunity being profiled, neither is there an assessment being profiled.

Part of the confusion, I think, is that we use process profile both in the context of "an organization describing its processes related to a [target]" (in which case the "target" properties make more sense) as well as "A [target] defining its own processes" (in which case the "___profiled" properties would make more sense).  

Also, to this day, as I've mentioned before, we have still not truly delved into process profile to determine exactly what properties it needs and/or how it should be used. Currently it is full of properties we derived from the QA documents, which, in hindsight, may or may not actually apply directly to processes.

**Comment by jkitchensSIUC** [comment]
@stuartasutton will you make the change or should we have this on the agenda for tomorrow?

**Comment by stuartasutton** [comment]
**APPEARS TO BE ALREADY DONE**

**Closing issue**
