### ISSUE TITLE
CostProfile: change "assessmentProfile" to "assessmentProfiled"

### ISSUE THREAD

**Issue by CTITechPlanning** [CredentialTransparencyInitiative/vocabularies#139]
This would bring it in line with the "learningOpportunityProfiled" and "taskProfiled" properties.  I assume this was a typo of some sort?

Note: I have made the correction - I wanted to note it here in case it impacts something that Stuart or someone else is doing.

**Comment by stuartasutton** [comment]
It does, indeed, have impact. The addition of a slightly renamed property to the CostProfile means that the other two domains that used that renamed property also needed to be renamed. I have made that change. When changing a property name, look to see if the original has other classes in its domainIncludes. If so, the property needs to be changed in those types/classes as well. If we don't change it in all places (ie. all the relevant classes), we end up with the original property name being a table in the definitions as well as the renamed property.

**Comment by stuartasutton** [comment]
**ACTIONS TAKEN:**

Property "assessmentProfiled" updated in all domains (http://www.credreg.net/page/propertiesviewer#assessmentProfiled).

Closing issue
