### ISSUE TITLE
ctdl:CostType Needs Additional Vocabulary 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#140]
Cost Type currently provides no clear vocabulary for:

Enrollment Fee - One time required fee to enroll in a program. 

Student Services Fee - Non-refundable fee required  to access a variety of services.

Room or Residence - costs to board while enrolled in a program.

Meals - costs for meals while in enrolled in a program.

Optional Charges - additional fees for accessing other services, equipment, or facilities.

Technology Fee - cost for accessing technologies that are made available to a program.

**Comment by siuc-nate** [comment]
We also need to add:
- Maintenance Fees
- Reexamination Fee
- Scoring Fee
- Processing Fee
- Rescheduling Fee

These are typical recertification fees.

![image](https://cloud.githubusercontent.com/assets/21346519/19873045/c12e07d8-9f8a-11e6-8400-7895312d90db.png)

[CAP_handbook.pdf](https://github.com/CredentialTransparencyInitiative/vocabularies/files/562941/CAP_handbook.pdf)

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

I have added the cost concepts noted by Jeanne and Nate to the CostType vocabulary at http://www.credreg.net/page/vocabulariesviewer#CostType. Note that Nate's concepts currently lack definitions.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate I updated all of the missing definitions.  There's still one term that we either need to add or close on issue #127  

Since all of the terms were added as well as definitions and scope notes, except for one identified in #127, I'm closing this issue.
