### ISSUE TITLE
Publishing properties in schema.org as: schema:name vs ctdl:name

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#141]
@stuartasutton ,
Anderson raised the following question regarding use of **schema:name**, vs **ctdl:name**:

> For the schema.org properties, such as name and description, which is the correct form: schema:name or ctdl:name. 
> Because the serialization schema says that the ctdl:name is required, but the data samples have schema:name. 

Should we be publishing properties that exist in schema.org with the schema prefix or every property with the ctdl prefix?
I imagine part of Anderson's concern is from the schema validation viewpoint.

**Comment by stuartasutton** [comment]
@andersoncardoso, @mparsons1953, @science & @jkitchensSIUC, we ***absolutely*** should be using "ctdl" and not "schema" for two indisputable reasons:

1. **CE needs to maintain control of its properties and classes.** We are consistently using owl:sameProperty and owl:sameClass to declare where a ctdl term maps to schema.org. Every property and class we define *may* or *may not* be adopted by schema.org. ***And*** (and this is a HUGE "and"), there are no promises that the schema.org properties we use in our application profile will not be significantly changed or even deprecated (sent to their "attic").  Bottom line, we should follow other projects that need stability by defining our properties in our own namespace and mapping them to schema.org. That is the only way that CE can maintain the integrity of its schema. When, and if, adopted by schema at some future point, there will be two URI to individual properties of classes, one in the ctdl namespace and one in the schema.org namespace. For example, see the LRMI properties in their own namespace at http://lrmi.dublincore.net/lrmi-schema/ and note that the terms formally declare their equivalencies to schema.org. See also the Good Relations namespace driving the e-commerce terms in schema.org--again, declared in the Good Relations namespace and mapped to schema.org equivalencies. Schema.org has no stated long-term dedication to the stability of its terms. The lifecycle of webpage markup is generally short while the need for stability in data structures is long-term. We support that longevity by declaring in our own namespace where we can make the necessary guarantees. When, and if, any of the ctdlL is adopted, they adopt a snapshot of the relevant properties and classes in the ctdl namespace. At that point, both initiatives can maintain parallel development or not.
2. **There are no such properties/classes in the schema.org namespace.**  Of course, until schema.org adopts ctdl in whole or in part (most likely the latter), there is no mechanism for referencing the ctdl terms as being in the schema.org namespace. Thus, we cannot coin new terms now as being in that namespace. I know that this is different from the call of this issue, but also points to a single ctdl namespace using the same mapping mechanism by us with current schema.org terms that future adoption by schema.org should use when replicating ctdl terms it adopts in its namespace. ***It is all about mapping.***

**Comment by science** [comment]
@stuartasutton Are you saying that we should use "ctdl:" for all vocab terms even when they are sourced from schema.org?

**Comment by stuartasutton** [comment]
Yes, that is what I am saying. That's exactly where we've been for some time. See declarations in Properties Viewer [1] and in the CE Context File (and other serializations) [2]. 

**Shall we go over this on today's call? I can join early.**

[1] http://www.credreg.net/page/propertiesviewer
[2] http://www.credreg.net/Page/serializations/#jsonSerialization

**Comment by andersoncardoso** [comment]
@mparsons1953 as soon as you start publishing as `ctdl:name` and etc, ping me so I can change on the schema. For now the validation is using 'schema:name' to keep consistency with the samples.

**Comment by siuccwd** [comment]
@andersoncardoso we are now publishing with ctdl:name, rather than schema:name

**Comment by andersoncardoso** [comment]
@siuccwd done and deployed =)

**Comment by jkitchensSIUC** [comment]
Closing this issue.
