### ISSUE TITLE
ctdl:assessmentInformation versus ctdl:description

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#142]
For AssessmentProfile, we have:
**ctdl:description**
> A short description of the resource being described.

**ctdl:assessmentInformation**
> An text of an authoritative resource providing human-readable, in-depth information about the assessment being profiled.

Do we need both of these properties? 
What would be the guidance?
Would someone be more prone to just use the description and provide as little or as much information as suits them?

**Comment by stuartasutton** [comment]
@mparsons1953, it is redundant and varies only in terms of the length of text. In the misty past, I think that the ctdl:assessmentInformation may have been a URL pointing to a more indepth description provided as opposed to authored in the metadata. With both now as range of "text", all is does as promote the question you are asking...which should I use and why? 

The CTDL does not define or constrain "short", so, I'd dump ctdl:assessmentInformation.

**Comment by jkitchensSIUC** [comment]
We agree, please dump ctdl:assessmentInformation.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

The ctdl:assessmentInformation property has been deleted on ctdl:AssessmentProfile (the only occurrence).

**Closing issue.**
