### ISSUE TITLE
CTDL "release" process and timetable

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#143]
@jkitchensSIUC, several weeks ago, Nate, Mike and I discussed on our call a "release" process and getting a needed "release" out the door. We define a "release" as a (permanently) frozen (to everyone!) snapshot of the associated spreadsheets (properties, classes, controlled vocabularies, and json context). We should most likely date-stamp the names of the associated spreadsheets for a release and identify the release accordingly. The general process would be replicate the frozen, date-stamped spreadsheets as a "pending", publicly available, dynamic development version. When work on the pending version is deemed complete, it is frozen with date-stamped name, and the cycle repeats. With each snapshot, the github schema versions (including the json context) are updated from the frozen spreadsheets. There should be a "Pending History" page that is updated as new things are added and changes made in the pending state of the spreadsheets etc. (see, for example [1]).

Each snapshot "release" must be documented on a permanent "Release History" page (see, for example [2]) with: (1) itemization (not explanation) of what has changed; and (2) itemization of anything that remains "unstable" (i.e., risky to use). Each "release" must be announced through **some broadcast mechanism** that pushes update messages to subscribers who have individually joined the channel. This communication channel should be used for **no other purpose** beyond announcing changes to the CTDL (including links to github issues discussing those changes and actions taken).

We need to get a 0.9? snapshot out the door as quickly as possible (i.e., now?) and declare a soft, approximated update cycle during the ongoing period of initial development--perhaps every 2-3 months? If we include statements of what is unstable in our release history, by implication, everything else is deemed stable and needs to follow the principle of "change nothing that breaks systems" (and that means other people's systems, not just ours).  

Can we target a release within the next 1-2 weeks? That's possible only is we are confident that we've covered the 'significant' changes in what we already have.

Stuart

[1] http://pending.schema.org/
[2] http://schema.org/docs/releases.html

**Comment by jkitchensSIUC** [comment]
@stuartasutton Nate, Mike and I are reviewing the open issues together so you know we're on the same page.  We agree with this issue and will put it on the agenda for tomorrow.

**Comment by jkitchensSIUC** [comment]
Release date is November 17, 2016 @mparsons1953 @siuc-nate review this issue.

**Comment by siuc-nate** [comment]
We have setup this document:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#

Specifically the navigation section:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#heading=h.ls8s8mbjka17

to cover the items outlined in this issue.

**Comment by jkitchensSIUC** [comment]
Refer to this issue for process documentation.
