### ISSUE TITLE
Terms label and URI token disjunction

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#144]
In schema.org (and Dublin Core), the URI of a property or class is comprised of the root namespace of the scheme or schema with the concatenated label token. For example, in Dublin Core, the URI for the concept of "title" is comprised of the  the root namespace of http://purl.org/dc/terms/  with the concatenated token or label of the property--i.e., "title"--with the resulting http://purl.org/dc/terms/title. Schema.org follows the same basic principle. Note that we do not always follow this approach; and should make that fact clear in our documentation.

For example, take a look at the concept of ctdl:AssistEmployers (http://purl.org/ctdl/terms/AssistEmployers) where the label is "Assists Employers Seeking Competent Practitioners". If this concept followed the rule of construction noted above, it would have the following URI:

> ctdl:AssistsEmployersSeekingCompetentPractitioners

While a sound argument could be made that a label of "Assist Employers" is quite sufficient and is fleshed out quite nicely in the definition, that argument is beside the point if asked "how do you construct your term URIs". At the moment, all we can say is that we **_sometimes**_ concatenate the label token to the base namespace to coin a URI and **_sometimes we do not**_. In other words, we do not constrain the construction of these URI. Personally, I think we should constrain. A label is a signal, not an explanation. No one should frame their understanding of the semantics of a term from the label without reading the definition. 

We need to state this matter clearly and emphatically in our documentation or people will start guessing at URI because they think they understand the algorithm when sometimes their guess would work and sometimes it would not.

**Comment by jkitchensSIUC** [comment]
@stuartasutton we agree with you.  Let's review this tomorrow so we know who is doing what.

**Comment by jkitchensSIUC** [comment]
@CTITechPlanning @siuc-nate @mparsons1953 resurfacing this issue for follow up.

**Comment by jkitchensSIUC** [comment]
@stuartasutton is this a Nov 17th milestone issue?

**Comment by siuc-nate** [comment]
Refer to the PURL planning document:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#

**Comment by jkitchensSIUC** [comment]
This is to provide a reminder to include the above explanation with the Name Space Policy.

How CTDL constructs URIs, what are the rules, or lack thereof.
