### ISSUE TITLE
Vocabularies viewer is missing properties and a TOC

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#145]
There are a few missing properties in the [Vocabularies Viewer] (http://www.credreg.net/page/vocabulariesviewer): 

1. The vocabularies (concept schemes) themselves have: (a) a definition that does not appear (see column D of the [Class Spreadsheet] (https://docs.google.com/spreadsheets/d/1UINeEQbBvD1CZNYRjounCZE-xuvMyNDJZPrOGNcuFH4/edit#gid=0) and (b) a comment note in column E;
2. The vocabulary terms (concepts) in the [Vocabularies Spreadsheet] (https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0) have scope notes (column F) that do not appear in the viewer.

Also, there needs to be a TOC for the concept schemes at the top of the tables like in the other viewers.

**Comment by siuc-nate** [comment]
I will address this today.

**Comment by siuc-nate** [comment]
I have updated the viewer.

**Comment by stuartasutton** [comment]
Thanks Nate. There is one more thing with the vocabulary tables. For each concept, we need to add a last row to the table labeled "In Scheme". This row should contain the contents of the concept's column "A" from the vocabulary spreadsheet [1] (including the namespace prefix).

[1] https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0

**Comment by stuartasutton** [comment]
LET'S GO OVER THIS ON OUR CALL TODAY.

**Comment by siuc-nate** [comment]
I've added the "In Scheme" row.

**Comment by stuartasutton** [comment]
**CLOSING ISSUE**
