### ISSUE TITLE
CE context file lacks "@type" declarations

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#146]
The schema.org context file  at http://schema.org/docs/jsonldcontext.json includes "@type" declarations for all properties that have a specific range datatype--e.g., dates, and URI. Below are examples from both the schema.org context file (which uses "@ type") and our context file at http://www.credreg.net/Page/serializations/#jsonSerialization which does not use "@ type" (***and should***).

**E.G., SCHEMA.ORG DATES:**

 "datasetTimeInterval": { "@id": "schema:datasetTimeInterval", "@type": "DateTime"},
 "dateCreated": { "@id": "schema:dateCreated", "@type": "Date"},
 "dateDeleted": { "@id": "schema:dateDeleted", "@type": "DateTime"},
 "dateIssued": { "@id": "schema:dateIssued", "@type": "DateTime"},
 "dateModified": { "@id": "schema:dateModified", "@type": "Date"},
 "datePosted": { "@id": "schema:datePosted", "@type": "Date"},
 "datePublished": { "@id": "schema:datePublished", "@type": "Date"},
 "dateRead": { "@id": "schema:dateRead", "@type": "DateTime"},
 "dateReceived": { "@id": "schema:dateReceived", "@type": "DateTime"},
 "dateSent": { "@id": "schema:dateSent", "@type": "DateTime"},
 "deathDate": { "@id": "schema:deathDate", "@type": "Date"},

**E.G., OUR DATES:**

 "dateEffective": { "@id": "ctdl:dateEffective" },
 "foundingDate": { "@id": "ctdl:foundingDate" },
 "alignmentDate": { "@id": "ctdl:alignmentDate" },
 "dateEffective": { "@id": "ctdl:dateEffective" },
 "endTime": { "@id": "ctdl:endTime" },

===============

**E.G., SCHEMA.ORG (PROPERTIES WITH RANGE URI)**

 "discussionUrl": { "@id": "schema:discussionUrl", "@type": "@id"},
 "acceptsReservations": { "@id": "schema:acceptsReservations", "@type": "@id"},
 "benefitsSummaryUrl": { "@id": "schema:benefitsSummaryUrl", "@type": "@id"},
 "contentUrl": { "@id": "schema:contentUrl", "@type": "@id"},

**E.G., OURS (PROPERTIES WITH RANGE xsd:anyURI)**

 "availabilityListing": { "@id": "ctdl:availabilityListing" },
 "versionIdentifier": { "@id": "ctdl:versionIdentifier" },
 "verificationServiceUrl": { "@id": "ctdl:verificationServiceUrl" },

**Comment by siuc-nate** [comment]
This should be easier to do now that each row has a data type identifier - I'll look into it this morning.

**Comment by siuc-nate** [comment]
I've updated the JSON-LD context.
