### ISSUE TITLE
Vocabulary PURLS for ConceptScheme (/ctdl/terms/) & Concepts (vary)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#147]
We need to go over the PURL service "partial" redirects for our vocabularies. Given the current vocabularies (not including stuff in issues impacting vocabularies), I think we need the following PURLs to support our individual concept schemes:

> http://purl.org/ctdl/agentQAPurpose
> http://purl.org/ctdl/agentSector
> http://purl.org/ctdl/agentServiceType
> http://purl.org/ctdl/assessmentDelivery
> http://purl.org/ctdl/assessmentMethod
> http://purl.org/ctdl/assessmentMode
> http://purl.org/ctdl/audience
> http://purl.org/ctdl/claimType
> http://purl.org/ctdl/credentialStatusType
> http://purl.org/ctdl/educationLevel
> http://purl.org/ctdl/externalInputType
> http://purl.org/ctdl/intendedPurpose
> http://purl.org/ctdl/learningDelivery
> http://purl.org/ctdl/learningSchedule
> http://purl.org/ctdl/organizationType
> http://purl.org/ctdl/processMethod
> http://purl.org/ctdl/residency
> http://purl.org/ctdl/revocationCriteria
> http://purl.org/ctdl/staffEvaluationMethod

There is a good, up-to-date explanation of the PURL service at https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator

We are particularly interested in "partial" redirects. 

Review Dublin Core examples:

> http://archive.org/services/purl/domain/dc_dcmitype (DCMI Type vocabulary)
> http://archive.org/services/purl/domain/dc_terms (DCMI properties/classed)
# 

VOCABULARY CLASSES

http://purl.org/ctdl/terms/AgentQAPurpose
    http://purl.org/ctdl/agentQAPurpose/AssistEmployers
    http://purl.org/ctdl/agentQAPurpose/EmployerTuitionAid
    ...

http://purl.org/ctdl/terms/AgentSector
    http://purl.org/ctdl/agentSector/BusinessIndustryAssociation
    http://purl.org/ctdl/agentSector/PrivateForProfit
    ...

http://purl.org/ctdl/terms/AgentServiceType
    http://purl.org/ctdl/agentServiceType/AccreditService
    http://purl.org/ctdl/agentServiceType/ApproveService
    ...

?????? http://purl.org/ctdl/terms/AggregateCost [1 concept = PROPERTY; why isn't this concept a member of CostType concept scheme?]

http://purl.org/ctdl/terms/AssessmentDelivery
    http://purl.org/ctdl/assessmentDelivery/InPerson
    http://purl.org/ctdl/assessmentDelivery/Online
    ...

http://purl.org/ctdl/terms/AssesmentMethod
    http://purl.org/ctdl/assessmentMethod/AchievementTest
    http://purl.org/ctdl/assessmentMethod/AdvancedPlacementTest
    ...

http://purl.org/ctdl/terms/AssessmentMode
    http://purl.org/ctdl/assessmentMode/Formative
    http://purl.org/ctdl/assessmentMode/Diagnostic
    ...

http://purl.org/ctdl/terms/Audience
    http://purl.org/ctdl/audience/Citizen
    http://purl.org/ctdl/audience/CurrentMilitary
    ...

http://purl.org/ctdl/terms/ClaimType
    http://purl.org/ctdl/claimType/BadgeClaim
    http://purl.org/ctdl/claimType/TranscriptClaim
    ...

http://purl.org/ctdl/terms/CredentialStatusType
    http://purl.org/ctdl/credentialStatusType/Active
    http://purl.org/ctdl/credentialStatusType/Deprecated
    ...

http://purl.org/ctdl/terms/EducationLevel
    http://purl.org/ctdl/educationLevel/Associate
    http://purl.org/ctdl/educationLevel/Bachelor
    ...

http://purl.org/ctdl/terms/ExternalInputType
    http://purl.org/ctdl/externalInputType/Associations
    http://purl.org/ctdl//externalInputType/Consumers
    ...

http://purl.org/ctdl/terms/IntendedPurpose
    http://purl.org/ctdl/intendedPurpose/GeneralEducation
    http://purl.org/ctdl/intendedPurpose/JobOrCareerPreparation
    ...

http://purl.org/ctdl/terms/LearningDelivery
    http://purl.org/ctdl/learningDelivery/BlendedLearning
    http://purl.org/ctdl/learningDelivery/CompetencyBased
    ...

http://purl.org/ctdl/terms/LearningSchedule
    http://purl.org/ctdl/learningSchedule/FullTime
    http://purl.org/ctdl/learningSchedule/PartTime
    ...

http://purl.org/ctdl/terms/OrganizationType
    http://purl.org/ctdl/organizationType/NonTraditional
    http://purl.org/ctdl/organizationType/AssessmentBody
    ...

http://purl.org/ctdl/terms/ProcessMethod
    http://purl.org/ctdl/processMethod/AdvisoryGroup
    http://purl.org/ctdl/processMethod/ExpertReview
    ...

http://purl.org/ctdl/terms/Residency
    http://purl.org/ctdl/residency/InState
    http://purl.org/ctdl/residency/International
    ...

http://purl.org/ctdl/terms/RevocationCriteria
    http://purl.org/ctdl/revocationCriteria/Abandonment
    http://purl.org/ctdl/revocationCriteria/Violation
    ...

http://purl.org/ctdl/terms/StaffEvaluationMethod
    http://purl.org/ctdl/staffEvaluationMethod/ExternalEvaluation
    http://purl.org/ctdl/staffEvaluationMethod/InternalEvaluation
    ...

**Comment by siuc-nate** [comment]
Wouldn't it make more sense to use a format like:
http://purl.org/ctdl/terms/Residency/InState
http://purl.org/ctdl/terms/Audience/Citizen
etc.?  I thought this was how these were supposed to be used. 

Also, I don't think we want to encode our ever-evolving vocabulary into the PURL itself.

**Comment by stuartasutton** [comment]
No, it does not make more sense. We do **not** create a PURL for each concept. What gets encoded as a PURL, is the vocabulary (i.e., the concept scheme), **not** the individual concepts in that vocabulary. That's the list at the top of this thread. Similarly, this principle also works with the classes and properties with the PURL http://purl.org/ctdl/terms/ --all that is needed using partial redirects is this single PURL and now what gets concatenated on the end. Bottom line, we do **not** create a PURL for each property, class, or concept. 

This is why we need to look at how "partial" redirects work in the PURL service and make absolutely sure we have it correct. 

Since we do not create PURLs at the concept level, all that needs to be certain right now with the "ever-evolving vocabularies" is that the vocabulary exists...nothing more.

**Comment by stuartasutton** [comment]
Note that this issue is related to issue #78.

**Comment by siuc-nate** [comment]
Sorry, I didn't mean to imply that every term would have a PURL.  What I meant was that we can use our existing PURL:
http://purl.org/ctdl/terms/
and rely on our system for everything else.  "Residency" and "Residency/InState" would both be handled by the system that http://purl.org/ctdl/terms/ redirects to.  That way we don't have to create a PURL just for Residency.

**Comment by stuartasutton** [comment]
I don't advise doing that exactly as you suggest. It's best to keep your PURL addressing properties and classes as a single namespace and then your concept instances in another. The concept scheme classes at the top of this thread are indeed in the /ctdl/terms/ PURL. ...e.g., http://purl.org/ctdl/terms/AgentQAPurpose. We can go over this on our call and I'll show you how the skos:inScheme ties the two together...I can show you this with a vocabulary in the DCMI namespace.

**Comment by siuc-nate** [comment]
In that case, wouldn't we want to have a single PURL that covers all of our vocabulary terms?
e.g.
http://purl.org/ctdl/vocab/InState
http://purl.org/ctdl/vocab/AccreditService
http://purl.org/ctdl/vocab/BlendedLearning

**Comment by stuartasutton** [comment]
Yes, that's possible. BUT, the concept scheme PURL should never the less be in /terms/. I was trying to reduce the length of the PURLs for concepts by eliminating the /vocab/...

**Comment by siuc-nate** [comment]
Right, so, to clarify, we'd have two PURLs:
http://purl.org/ctdl/terms
http://purl.org/ctdl/vocab

Which would redirect to information about the concepts (e.g. http://purl.org/ctdl/terms/Audience ) and vocabulary terms (e.g. http://purl.org/ctdl/vocab/Citizen ), respectively. 

That said, it seems a little backwards - descriptions of the vocabularies themselves (i.e., the concepts) would make more sense under "vocab" and the vocabulary _terms_ themselves are more intuitively placed under "terms", in my opinion.

**Comment by stuartasutton** [comment]
NO! There are likely instances that will arise where the same token (e.g., "State") may be defined differently. Lumping them together into a common namespace is massively problematic--as schema.org will discover...

**Comment by siuc-nate** [comment]
Oh, I must have misinterpreted you then.  I thought when you said:

> It's best to keep your PURL addressing properties and classes as a single namespace and then your concept instances in another.

You meant to have two PURLs - hence "vocabs" and "terms"

In _that_ case, I am still confused on why we wouldn't want to use a concatenation-based system (my previous stance) along the lines of:
http://purl.org/ctdl/terms/ (the PURL)
http://purl.org/ctdl/terms/Residency (PURL + vocab name to get information about the concept)
http://purl.org/ctdl/terms/Residency/InState (PURL + vocab + term to get information about that term within that vocabulary)

It turns each vocab into its own namespace and means we don't have to have a PURL for each concept.

**Comment by stuartasutton** [comment]
We are subtly saying **somewhat** the same thing, but functionally different. As you frame it, it dumps everything in the "/terms/" namespace. My suggestion (following DCMI's structure) puts the concept scheme in terms--i.e., your "http://purl.org/ctdl/terms/Residency" --meaning that the concept scheme classes are indeed classes like all the others in /terms/ but says its member concepts are in identified namespaces. Look at http://www.credreg.net/page/vocabulariesviewer#agentQAPurpose_AssistEmployers and note that the "In Scheme" puts the concept "AssistEmployers" in the concept scheme class in the /terms/ PURL at http://purl.org/ctdl/terms/Residency and its concepts in the namespace http://purl.org/ctdl/agentQAPurpose/.

See the table at DCMI for the concept "Image" in the DCMI "Type" vocabulary at http://dublincore.org/documents/dcmi-terms/#dcmitype-Image. Look carefully at the URI for the "Type" concept scheme and then the URI of the "Image" concept in that concept scheme. This follows the structure I propose above.

I originally had you set up a http://purl.org/vocabs/ (to distinguish between /terms/ and /vocabs/ to achieve this separation. We could maintain that distinction with:

> http://purl.org/ctdl/vocabs/Residency 
> http://purl.org/ctdl/vocabs/Residency/InState

I'd prefer that to dumping it all in the /terms/ root. The only thing I don't like about it is that the concept schemes ***as classes*** are no longer in the /terms/ namespace where I think they below.

But, I don't have to maintain this long-term, you do, so we just need to decide.

Stuart

**Comment by stuartasutton** [comment]
Also, we need to check with someone who knows about the use of "vocabs" since "@vocab" is a keyword in FSON-LD. While one letter off, "vocabs" is mighty close.

**Comment by siuc-nate** [comment]
What about this:

We setup the terms namespace to work as you intend and put the concept schemes in that so they retain their "classness":
http://purl.org/ctdl/terms/Residency

Then we setup the vocab namespace to handle vocabularies, where the namespace for each vocabulary matches its associated concept scheme:
http://purl.org/ctdl/vocabs/Residency/InState

Where /Residency/InState are handled by the system that http://purl.org/ctdl/vocabs redirects to. If needed we could probably setup http://purl.org/ctdl/vocabs/Residency to redirect to /terms/Residency if there's no term afterwards in the URL (or to return the same information that /terms/Residency would return).

Internally we would probably have /vocabs/Residency and /vocabs/Residency/InState be the "normal" way the system works and have /terms/Residency return the same info as /vocabs/Residency, but that would all be invisible to the consumer of the data. (It probably wouldn't be much additional effort to have /terms/Residency/InState return the same info as /vocabs/Residency/InState, too, just to cover all the bases).

My goal is basically to avoid having to maintain a PURL for each concept scheme, as these may change over time, and it complicates the implementation to have to account for them (unless they simply redirect to /terms/[ConceptScheme] or /vocabs/[ConceptScheme], in which case the only complication is having to maintain the PURLs when something changes - assuming it's okay to redirect http://purl.org/ctdl/residency/InState to [whatever.ext]/ctdl/terms (or vocabs)/Residency/InState, but I wonder if we're just being redundant at that point ).

Would something along these lines accomplish your goals as well?

**Comment by stuartasutton** [comment]
Nate, I think it is a very bad idea not to maintain a purl for each concept scheme. No, concept schemes do not change over time. Their member concepts change, but not the concept scheme. For example, here are 3 vocabularies namespaces from the Library of Congress relatively large array of controlled vocabularies (what they call "authorities" (/subjects/, /names/, & /genreForms/). They aren't PURLs, but that's not the issue:

http://id.loc.gov/authorities/subjects/
http://id.loc.gov/authorities/names/
http://id.loc.gov/authorities/genreForms/

These are massive concept schemes with concepts being added, deleted, split and combined. But the vocabularies as concept schemes don't change...just their member concepts.

**Comment by siuc-nate** [comment]
What I meant was, _our_ concept schemes are still quite fluid, as evidenced by #84.  Perhaps we can make PURLs for the stable ones, but it might be worth doing one more walkthrough of our concept schemes before we set them in stone.

**Comment by stuartasutton** [comment]
Yes, I am hoping we schedule review so we can get through in time to get
them updated where necessary and make the 17th deadline. We are close on
how much will be done with AssessmentType...are there others yet to surface?

**Comment by mparsons1953** [comment]
Stuart
I set up a few of the PURLs - based on referencing the credreg.net viewers. The latter will not be the final home for the data, so I didn't want to create PURLs that would would be obsolete. At this time, it doesn't appear possible to delete a PURL, or edit the source PURL, only the target URL.
The PURL: /ctdl/terms, cannot be used with the viewer. As I could not edit the PURL itself, I created /ctdl/term/ as an alternate test, and it does work:
http://purl.org/ctdl/term/AgentQAPurpose

I do have some confusion between which source should be to the vocabularies viewer, and which should be the properties viewer. The items that you initially reference as concept schemes, use camel case. This would seem relate to the properties (as only these are camel case). 

I created /ctdl/term/ for properties, and /ctdl/scheme/ for vocabulary.
You had referenced scheme, and Jeanne noted that ASN uses scheme in their PURLs for vocabulary:
/ASN/scheme/ASNEducationLevel/
http://purl.org/ctdl/scheme/Audience
http://purl.org/ctdl/scheme/ClaimType

As I was validating the PURLs, I had more confusion, as there is not a one-to-one match in the original list. For example, the first item is agentQAPurpose, and the only property is agentQualityAssurancePurpose.
Others:
- agentSector vs agentSectorType
- no agentServiceType, but have agentType

Anyway this is an early draft, primarily getting an understanding of the tool and determining how to craft a PURL, and design the target sites, to ease management.

**Comment by stuartasutton** [comment]
Mike, let's try and go over this tomorrow. We should look at the Dublin Core PURLS for the pattern of use for partial PURLS. I can explain the reasoning. 

Stuart

**Comment by mparsons1953** [comment]
Stuart,
I understand that the same name cannot be used for the term and the vocabulary. 
Also, I see that there are notes like the following that point me to the vocabulary item for a term, like the following: 

> Best practice for developing credential descriptions for the Credential Engine Registry is to use the CTDL ClaimType vocabulary.

From a programming point of view, it would be handy if there was a concrete pattern linking the term to the vocab. Otherwise we always need to manually make the association. **In most cases, the suffix of Type in the term can be removed to get to the vocab, but not always.** 

Below is the current cross reference, with notes.

Term| vocab|Notes
------- | -------- | ------
ctdl:agentQualityAssurancePurpose|	ctdl:AgentQAPurpose	
ctdl:agentSectorType|	ctdl:AgentSector	
ctdl:serviceType|	ctdl:AgentServiceType	
tbd|	ctdl:AssessmentType	
ctdl:audienceType|	ctdl:Audience	
ctdl:verifiedClaimType|	ctdl:ClaimType	
ctdl:costType|	ctdl:CostType|	Isn’t there an issue with only case differences? The accompanying note indicates the vocab will be Cost
ctdl:credentialStatusType|	ctdl:CredentialStatusType|	The accompanying note suggests that the vocab will be CredentialStatus
ctdl:creditUnitType|	ctdl:CreditUnit	
ctdl:deliveryType|	ctdl:DeliveryType|	Is there an issue when these only differ in case?
ctdl:educationLevelType|	ctdl:EducationLevel	
ctdl:externalInputType|	ctdl:ExternalInputType|	Only differ in case, and note suggests vocab will be ExternalInput
ctdl:purposeType|	ctdl:IntendedPurpose	
ctdl:learningFormatType|	ctdl:LearningFormat	
ctdl:agentType	| ctdl:OrganizationType	
ctdl:processMethodType| 	ctdl:ProcessMethod	
ctdl:residencyType|	ctdl:Residency	                                                
??? ctdl:revocationCriteria has a range of URI|	ctdl:RevocationCriteria|	Just case difference, and No accompanying note about ‘recommended best practice …’
No reference|	ctdl:SkillExpressionType	
ctdl:staffEvaluationMethod|	ctdl:StaffEvaluationMethod|	Just case difference, and No accompanying note about ‘recommended best practice …’

**Comment by jkitchensSIUC** [comment]
@mparsons1953 put all documentation concerning PURLs in one document and update status here. Link to the documentation from here as well.

**Comment by siuc-nate** [comment]
Refer to the PURL planning document:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#

**Comment by siuc-nate** [comment]
The PURLs in the chart in the planning document below have been entered, except for those flagged with a "No" in the last column (purpose and audienceLevel).
https://docs.google.com/document/d/1xqK7XSQsEK-CB3_6g5CG0z5Q0PKAPI851fazVwq68sQ/edit#heading=h.4d34og8
