### ISSUE TITLE
General properties at top of Domain Viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#148]
We have a set of general properties (i.e., no assigned "domainIncludes) at the top of the [Domain Viewer](http://www.credreg.net/page/domainsviewer):

![screenshot 2016-10-26 05 20 21](https://cloud.githubusercontent.com/assets/2939046/19725736/2888c09c-9b3c-11e6-8e80-14c058a6226b.png)

Would it be possible to move the header text "Domains" below the current set of 5 general properties (i.e., just before "AssessmentProfile") and then provide the header "General Properties" with the text: "General Properties are for general use with any CTDL type (class)."

**Comment by siuc-nate** [comment]
Done.

**Comment by stuartasutton** [comment]
Thanks, Nate. There does seem to be a problem with these general properties expanding when you clock on them.

**Comment by siuc-nate** [comment]
Whoops, broke something when I took out the clickable green header for that section - it should be working again now.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate can this be closed?

**Comment by siuc-nate** [comment]
I believe so.

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

Closing issue #148
