### ISSUE TITLE
Updates to Credential Connections properties.

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#150]
Issue #114 proposes some clean-up of properties defining Credential-to-Credential relationships (connections). Part of https://docs.google.com/document/d/1uqBiM0uKCNpKRSNmH9ZPV6qmiYY0CfQsYEIS02WRQEM/edit tracks those changes. I have used the table data in the document to update the spreadsheets/viewers to accommodate the following changes:
- **[requires](http://www.credreg.net/page/propertiesviewer#requires):** "The resource being described requires the resource being referenced."
- **[isRequiredFor](http://www.credreg.net/page/propertiesviewer#isRequiredFor):** "The resource being described is required for the resource being referenced."
- **[recommends](http://www.credreg.net/page/propertiesviewer#recommends):** "The resource being described recommends the resource being referenced."
- **[isRecommendedFor](http://www.credreg.net/page/propertiesviewer#isRecommendedFor):** "The resources being described is recommended for the resource being referenced."
- **[advancedStandingFrom](http://www.credreg.net/page/propertiesviewer#advancedStandingFrom):** "The resource being described has time or cost reduced by the resource being referenced."
- **[isAdvancedStandingFor](http://www.credreg.net/page/propertiesviewer#isAdvancedStandingFor):** "The resource being described reduces time or cost for the resource being referenced."
- **[preparationFrom](Preparation for the resource being described is provided by the resource being referenced.):** "Preparation for the resource being described is provided by the resource being referenced."
- **[isPreparationFor](http://www.credreg.net/page/propertiesviewer#isPreparationFor):** "The resource being described provides preparation for the resource being referenced."
- **[hasPart](http://www.credreg.net/page/propertiesviewer#hasPart):** "Indicates a resource that is (in some sense) a part of the resource being described."
- **[isPartOf](http://www.credreg.net/page/propertiesviewer#isPartOf):** "Indicates a resource that the resource being described is (in some sense) part of."
- **[isSimilarTo](http://www.credreg.net/page/propertiesviewer#isSimilarTo):** "A reference to another, functionally similar resource."

In addition, subproperties to [isSimilarTo](http://www.credreg.net/page/propertiesviewer#isSimilarTo) were brought over from ASN's mapping properties and slightly redefined to make them generic to comparing the key aspects of identity between two resources. Currently the domains and ranges have been defined as ctdl:Credential.
- **[broadAlignment](http://www.credreg.net/page/propertiesviewer#broadAlignment):** "The resource being referenced covers all of the relevant concepts in the resource being described as well as relevant concepts not found in the resource being described."
- **[narrowAlignment](http://www.credreg.net/page/propertiesviewer#narrowAlignment):** "The resource being described covers all of the relevant concepts in the referenced resource as well as relevant concepts not found in the referenced resource."
- **[exactAlignment](http://www.credreg.net/page/propertiesviewer#exactAlignment):** "The relevant concepts in the resources being compared are coextensive."
- **[majorAlignment](http://www.credreg.net/page/propertiesviewer#majorAlignment):** "There is major overlap of relevant concepts between the two resources being compared."
- **[minorAlignment](http://www.credreg.net/page/propertiesviewer#minorAlignment):** "There is minor overlap of relevant concepts between the two resources being compared."

**Comment by jkitchensSIUC** [comment]
Updated chart at the bottom of this:
https://docs.google.com/document/d/1uqBiM0uKCNpKRSNmH9ZPV6qmiYY0CfQsYEIS02WRQEM/edit#

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate Is this completed except for Pathway related properties that are being deferred as a later action item?
