### ISSUE TITLE
Is a separate AggregateCost vocabulary necessary

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#151]
The AggregateCost vocabulary has **one concept**--AggregateCost. Is there a reason that AggregateCost is not a concept of the CostType vocabulary? Having a vocabulary with a single concept doesn't really make any sense. In such cases, you'd be looking at a property and not a concept.

**Comment by siuc-nate** [comment]
I thought it already was a part of that vocabulary - I do not think it is supposed to be separate.  I recall some time back there was a separate (and, personally, unwanted) "aggregateCost" property that this may have been related to originally.

**Comment by stuartasutton** [comment]
Great! It did not appear to make any sense otherwise. 

**ACTION TAKEN** Made concept of CostType and issue closed.
