### ISSUE TITLE
Terms list (TOC) is unalphabetized

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#152]
Would it be possible to put the TOC (Terms List) in the [Vocabularies Viewer](http://www.credreg.net/page/vocabulariesviewer#termsLinks). It is pretty useless otherwise.

**Comment by siuc-nate** [comment]
This should be fixed now.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

Issue closed.
