### ISSUE TITLE
Redirect Vocabularies Viewer to Ver.2 of spreadsheet

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#153]
The [Vocabularies Viewer](http://www.credreg.net/page/vocabulariesviewer) needs to be redirected to read from the new [2016-10-26-Ver.2 spreadsheet](https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit#gid=0).

**Comment by siuc-nate** [comment]
This has now been updated.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

Issue closed.
