### ISSUE TITLE
CostProfile: remove scheduleType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#154]
Probably related to #84, as well as our recent discussion (in which we move "fullTime" and "partTime" to Audience), and because no "scheduleType" vocabulary exists ( http://credreg.net/page/vocabulariesviewer ), the scheduleType property should be removed from CostProfile.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

The scheduleType property was removed from CostProfile.
