### ISSUE TITLE
INVENTORY of "unstables" in the 2016-11-17 release

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#155]
We need to start here an inventory of unstable aspects of the upcoming 2016-11-17 release (including all relevant issue no. references for each). 

**We do NOT need long explanations.** Reserve those for the relevant issues.

**Comment by siuc-nate** [comment]
Tracking for 2016-11-17 Release: https://docs.google.com/spreadsheets/d/1OEeqb53gPVkf5Fa-6BhWogvjSbqTpIuAxqz5HHWBGRw/edit#gid=0

**Comment by jkitchensSIUC** [comment]
After the cutover, everything will default to stable.  We need to mark all unstable classes, properties and vocabularies.

**Comment by jkitchensSIUC** [comment]
On November 16, 2016 all of the classes, properties and vocabularies that were determined to be "Unstable" were flagged to show as unstable with the CTDL release on November 17, 2016.  See the listing here https://docs.google.com/spreadsheets/d/1OEeqb53gPVkf5Fa-6BhWogvjSbqTpIuAxqz5HHWBGRw/edit?usp=sharing.  

This is complete for the 11-17-2016 Milestone.
