### ISSUE TITLE
Viewer behavior of property 'Comment" and "Usage Note"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#156]
Currently, where a property has varying scope of application across a number of domains to which is it applies, any varying text shows up in the Comments row of the properties viewer as separate entries--one per line--with each prefaced with the classname where the text applies. The Usage Note row of the tables behaves differently with a single text. This behavior is reversed--i.e., the Usage Note should behave like the current Comment and the Comment should behave like the current Usage Note. 

We need to use the Comment field as the place for a single text that further refines/explains the property Definition--to say more about it in general. If different classes (types) have variations in refinement of the property as applied, those should appear in Usage Notes with each variation prefaced by the type (just as the current Comment handles varying text).

**Comment by siuc-nate** [comment]
I have updated the domains viewer and properties viewer - the vocabularies viewer does not appear to use comment or usage note.

**Comment by stuartasutton** [comment]
No, they do not. Comment 'could' be used but Usage Note is unlikely.

**Comment by stuartasutton** [comment]
NOTE: The "Usage Note" does not quite match the former behavior of Comment. While the Usage Note does prepend the type (e.g., CredentialOrganization), it does not seem to reflect Usage Not values on more than one entity. See ctdl:assesses (http://www.credreg.net/page/propertiesviewer#assesses). It has two domains, each with a Usage Note but only the note for one is visible...Is it because in this particular instance the Usage Note for both domains is the same text?

**Comment by siuc-nate** [comment]
Ah, whoops, I found the issue - try it now.

**Comment by jkitchensSIUC** [comment]
Since Nate indicated this is fixed and we're switching to a new view, closing this issue.
