### ISSUE TITLE
Review ProcessProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#157]
Many properties within ProcessProfile probably belong with other entities - we need to review how ProcessProfile is used and determine which of its properties should be moved elsewhere.

Likely suspects so far:
- staffEvaluationMethod (move to Organization)
- staffSelectionCriteria (move to Organization)

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton didn't we cove all of process profile? Can this be closed?

**Comment by stuartasutton** [comment]
@jkitchensSIUC, yes...closing.
