### ISSUE TITLE
Consistent naming/casing of properties with phrases like "URL"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#158]
Once our vocabularies and properties and such have stabilized, we should probably review them to ensure we are consistently using the same casing on properties with acronyms like URL in them, e.g.,:
processURL vs processUrl. 

We should also address the naming convention for URL properties so that we consistently name them.

**Comment by stuartasutton** [comment]
As part of these considerations, we need to clearly distinguish between URL uses that intend to: (1) identify a text string that is formatted in terms of the HTML protocol (i.e., literal datatype--e.g. marking up an actual URL on an HTML page as being of type (URL); and (2) identify a resource (i.e., are not a text string beginning with HTML but rather a link to some thing).

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton we have two documents related to URLs 

https://docs.google.com/document/d/1H_M8WhPisqEab5MUEmz24wU4a76STn07NuSwXYywY8w/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1j5fBG-dH29uRfo0Zln-Of7BTLIqW0aeuWyFb2CXaO1g/edit?usp=sharing

@siuc-nate where is your clear list of proposed updates for URLs?

**Comment by siuc-nate** [comment]
https://docs.google.com/spreadsheets/d/1j5fBG-dH29uRfo0Zln-Of7BTLIqW0aeuWyFb2CXaO1g/edit#gid=0

The list of changes for URLs are in the rightmost column on this spreadsheet.  They are a summation of details listed in all of the other columns.

Notably we need to discuss the use (or non-use) of url as a property of organization, assessment, and learning opportunity (and as of this afternoon, ConditionProfile)

**Comment by jkitchensSIUC** [comment]
@siuc-nate please login with the credreg account and make yourself a member. You need to be able to use all tools and we need to be able to assign to you when you need to be included.  

@siuc-nate please get with @stuartasutton on Nov 15th to finalize this so updates can be made.

**Comment by siuc-nate** [comment]
@jkitchensSIUC I did this yesterday - I still have not received the "invitation" email github claims to have sent that would let me join - checked inbox and spam folder.

**Comment by siuc-nate** [comment]
Refer to Issue #192
