### ISSUE TITLE
IdentifierValue for public keys 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#159]
@science had emailed this issue.

Determine if IdentifierValue entity is sufficient for the use case below 

http://credreg.net/page/domainsviewer?showEditorMapping=true#IdentifierValue

It would be really useful if organization schema could have a data structure something like 

	"publicKeys": [{"keyType": "RSA256", "key": "..."}]

This way, when organizations sign documents with a public key, we could have in our same database a statement that shows who is responsible for the key. The keys themselves are absent an identity - they're just strings. Being able to affiliate organizations with public keys would be a handy tool for figuring out who is who.

@mparsons1953 @stuartasutton @science is this an issue relevant to the Nov 17th release? What is the next step for discussion/resolving?  I know @stuartasutton had replied to the email but I cannot find it so anyone who has more information, please post it here.

**Comment by jkitchensSIUC** [comment]
Why not use the ctdl:identiferValue?

**Comment by jkitchensSIUC** [comment]
@stuartasutton  will edit additional information 

Refer to the CTDL Guide "Identifiers" section http://credreg.net/ctdl/handbook#identifier

Deprecate: ceterms:partOfIdentifierValueSet
Deprecate: ceterms:IdentifierVaueSet

Add: IdentifierType
Definition: Formal name of the identifier type.
Comments: Such as ISBN or SSN.

**Comment by stuartasutton** [comment]
**Actions to be taken:**

(1) Deprecate property: ceterms:partOfIdentifierValueSet
(2) Deprecate class: ceterms:IdentifierVaueSet
Neither have "superseded by" terms

(3) Add property: identifierType

Label: identifierType
Definition: "Formal name or acronym of the identifier type such as ISBN and SSN."
Comment: None 
Type: Property
Domain: Credential, Agent, LearningOpportunityProfile, AssessmentProfile
Range: IdentifierValue
Status: Stable

**Comment by siuc-nate** [comment]
@stuartasutton to be consistent with our other definitions, should the above instead be:
Definition: Formal name or acronym of the identifier type
Comment: Examples include ISBN and SSN

**Comment by siuc-nate** [comment]
I have made the changes listed above (and will close this issue pending Stuart's response to the question in my previous post) and noted them in the history tracking.

**Comment by stuartasutton** [comment]
If it makes it more consistent, sure.

**Comment by siuc-nate** [comment]
Thanks..

**Comment by stuartasutton** [comment]
Nate, I messed this up.

**Comment by stuartasutton** [comment]
Nate, I messed up his definition of `identifierType`. 

Corrected:

Label: identifierType
Definition: Formal name or acronym of the identifier type.
Comment: Examples include ISBN and SSN.
Type: Property
Domain: IdentifierValue
Range: rdfs:Literal
Status: Stable

**Comment by siuc-nate** [comment]
I have made the updates:
http://credreg.net/ctdl/pending#identifierType
