### ISSUE TITLE
ProcessProfile: change "assessmentProfiled" to "targetAssessment" and "credentialProfiled" to "targetCredential"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#161]
This will allow it to match the "target____" properties that exist in ProcessProfile for CompetencyFramework, and LearningOpportunity.

http://credreg.net/ctdl#ProcessProfile

- We already have ceterms:targetAssessment
- Remove assessmentProfiled
- Add targetCredential property, it is completely missing.

**Comment by stuartasutton** [comment]
I am assuming this issue is on hold as we eliminate ctdl:ProcessProfile?

**Comment by siuc-nate** [comment]
Since we are not dropping process profile, this remains an issue.

**Comment by siuc-nate** [comment]
This has been taken care of.
