### ISSUE TITLE
New ctdl:CredentialFramework as umbrella class

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#164]
This is less an issue than a heads up. I have created a new super class named [ctdl:CredentialFramework](http://www.credreg.net/page/propertiesviewer#CredentialFramework) defined as 

>"The class of all structured sets of conceptual resources intentionally designed for use as value vocabulary terms for description and classification in the credentialing context."

Member subclasses of ctdl:CredentialFramework include:

>[ctdl:CompetencyFramework](http://www.credreg.net/page/propertiesviewer#CompetencyFramework)
[ctdl:IndustryClassification](http://www.credreg.net/page/propertiesviewer#IndustryClassification)
[ctdl:InstructionalProgramClassification](http://www.credreg.net/page/propertiesviewer#InstructionalProgramClassification)
[asn:ProficiencyScale](http://explore.dublincore.net/theory/briefing-papers/asn-briefing-2/#proficiencyScale) 
[ctdl:OccupationClassification](http://www.credreg.net/page/propertiesviewer#OccupationClassification)
etc...

**Comment by jkitchensSIUC** [comment]
@stuartasutton thank you.

**Comment by jkitchensSIUC** [comment]
@siuc-nate making sure you saw this.  
@stuartasutton can this be closed?

**Comment by jkitchensSIUC** [comment]
This is complete.
