### ISSUE TITLE
Need namespace table at top of Vocabulary Viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#165]
The vocabularies viewer at http://www.credreg.net/page/vocabulariesviewer need the conventional namespace table at the top of the display. It will need to include the prefixes and PURLs for each of the controlled vocabularies. E.g.,

> **PREFIX:** costType
**VOCABULARY NAME:** http://purl.org/ctdl/terms/CostType
**VOCABULARY TITLE:** CTDL Cost Type Concept Scheme

(Note: as of this date (2016-11-07), not all vocabularies in the Vocabulary Inventory V2 spreadsheet have been assigned their *individual* concept URI prefixes.)

**Comment by siuc-nate** [comment]
This is done, mostly - I have kept the PURLs hidden since they don't work yet.

**Comment by jkitchensSIUC** [comment]
Since we won't use any of the old viewers after the 17th. I'm closing this issue.  @siuc-nate has the new single-page "viewer" setup for both the official release and for pending with the disclaimer so we'll remove all prior viewers and switch to the new version.
