### ISSUE TITLE
New LearningFormat vocabulary not showing in Vocabs Viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#166]
I added the LearningFormat vocabulary to the Vocabulary Inventory V2 spreadsheet (https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit#gid=0) at lines 103-108) and declared the vocabulary's class in the class spreadsheet (http://www.credreg.net/page/propertiesviewer#LearningFormat). BUT, for some reason, the vocabulary is not showing up in the Vocabularies Viewer at http://www.credreg.net/page/vocabulariesviewer.

It's a mystery...

**Comment by siuc-nate** [comment]
This appears to already be working:
http://www.credreg.net/page/vocabulariesviewer#vocabulary_LearningFormat
http://www.credreg.net/page/vocabulariesviewer#learningFormat_Contextual

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton since Nate indicated this is done, I'm closing this issue.
