### ISSUE TITLE
Renaming links at top of Vocabularies Viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#167]
Nate, can we rename the links at the top of the Vocabularies Viewer (http://www.credreg.net/page/vocabulariesviewer) as well as the section labels to which they link as follows:

> Vocabularies List ==> Controlled Vocabulary (Concept Scheme) List
> Term List ==> Concept List

**Comment by siuc-nate** [comment]
Done.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton since Nate indicated this is done, I'm closing this issue.
