### ISSUE TITLE
Reconnecting Enumeration Class list in Properties Viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#168]
Nate, I hate to ask you to repeat this exercise again (3rd time :-()... 

If you follow the Enumeration Classes Link at the top of the Properties Viewer (http://www.credreg.net/page/propertiesviewer#enumClassesLinks) you see that once again the sections for the enumerations are empty. This is because I again changed text in column F ("Sub-Class Of") of the Class Spreadsheet (https://docs.google.com/spreadsheets/d/1UINeEQbBvD1CZNYRjounCZE-xuvMyNDJZPrOGNcuFH4/edit#gid=0) used to trigger which classes are shown in the enumeration class section of the Properties Viewer. The trigger text in column F is now "skos:ConceptScheme". Where there are more than one sub-class, the "skos:ConceptScheme" text is always the trailing (last entry) text.

**Comment by siuc-nate** [comment]
This is now fixed.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton since Nate indicated this is fixed, I'm closing this issue.
