### ISSUE TITLE
Inventorying/handling references to ProcessProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#169]
We need to do an inventory of properties on various entities and their referencing of ProcessProfile .

**Comment by jkitchensSIUC** [comment]
@stuartasutton @CTITechPlanning @siuc_nate  today Nate and I will create the Process Profile review document so we can expedite review tomorrow.

**Comment by siuc-nate** [comment]
Notes from today's call, referencing https://docs.google.com/spreadsheets/d/1dPMEMYB7LLMn9mAZMFRh70TA7a4_fqS8hgWb3T8pN8s/edit#gid=551265448

I have attempted to keep track of the changes, but it's possible I missed something:

- Keep ProcessProfile
- Update property definitions ("Places where ProcessProfile is used" tab in the spreadsheet)
- Drop "selectionProcess" property
- Drop "agentProcess" property
- Update scope notes of the terms referenced in the Vocabularies tab to reflect QA/non-QA/both
- Drop ProcessMethodType property and vocabulary
- Add ProcessMethodDescription (a literal):
   - Definition: A more detailed refinement of the process methods.
   - Scope Note: Includes methods such as "advisory group", "major change report", "validation survey", etc.
- Add ProcessMethod (a URI):
   - Definition: A resource that describes the process methods.
- Drop StaffEvaluationMethod property and vocabulary
- Drop StaffSelectionCriteria property
- Add "ctdl:staffQualification" (a URI):
   - Definition: A resource that describes staff qualifications.
- Add "ctdl:staffQualificationDescription" (a literal):
   - Definition: Description of staff qualifications.
- Replace "target" properties with "profiled" properties, e.g. "targetCredential" -> "credentialProfiled"
- Rename ctdl:decisionInformationUrl to ctdl:decisionInformation
   - Definition: A resource that describes the types of decisions that are made about the processes the organization performs and how those decisions are defined.
- Add ctdl:decisionInformationDescription (a literal):
   - Definition: The types of decisions that are made about the processes the organization performs and how those decisions are defined.
- Modify terms in the ExternalInputType vocabulary:
   - Change "Industry Professional Associations" label to "Associations"
   - Change "Industry Employers" to "Employers" (name and label)
   - Change "Industry Practitioners" to "Practitioners" (name and label)
   - Change "Industry Subject Matter Experts" label to "Subject Matter Experts"
   - Remove "NationalGovernment", "StateGovernment", "LocalGovernment", and "Faculty"
   - Add "Government":
      - Definition: External stakeholder review, guidance or recommendations by government.
   - Add "Educators":
      - Definition: External stakeholder review, guidance or recommendations by education instructors or faculty.
   - Add "Guardians":
      - Definition: External stakeholder review, guidance or recommendations by parents or guardians.
   - Add "General Public": 
      - Definition: External stakeholder review, guidance or recommendations by the general public.
   - Change definition of "Students": External stakeholder review, guidance or recommendations by all types of learners.
- Change "ctdl:offeredByDirectoryUrl" to "ctdl:verificationDirectory"
- Change domain of ctdl:verificationDirectory to VerificationServiceProfile
- Add "ctdl:outcomeReviewDescription" (a literal):
   - Definition: How outcomes are reviewed.
- Add Scope Note to "ctdl:policiesAndProcedures": Includes handling of conflicts of interest, complaint, and appeal process policies.
- Change "ctdl:processCriteria" to "ctdl:processStandards"
- Change Definition of "ctdl:processStandards": A resource describing the criteria, standards, and/or requirements used in or by the process being described.
- Add "ctdl:processStandardsDescription" (a literal):
   - Definition: A description of the criteria, standards, and/or requirements used in or by the process being described.
- Drop processCriteriaValidation
- Drop publicInformationUrl
- Add "ctdl:policiesAndProceduresDescription" (a literal):
   - Definition: A description of policies and procedures for the process being described.
- Change definition of "ctdl:policiesAndProcedures": A resource that describes policies and procedures for the process being described.

**Comment by stuartasutton** [comment]
Handling issue 169 Process Profile changes today (Saturday, 2016-11-12).

**Comment by stuartasutton** [comment]
**ACTIONS TAKEN**

 1. Dropped selectionProcess property
 1.  Dropped agentProcess property
 1. Vocabularies dropped: ProcessMethod, StaffEvaluationMethod (& removed from Class)
 1. All vocabulary revisions complete from "Vocabularies" tab (see: [ExternalInput](http://www.credreg.net/page/vocabulariesviewer#ExternalInput) Note: "Type" removed from Concept Scheme name to match Class and Properties spreadsheet)
 1. Dropped processMethodType property
 1. Drop staffEvaluationMethod property and vocabulary
 1. Drop staffSelectionCriteria property
 1. Added [processMethodDescription](http://www.credreg.net/page/propertiesviewer#processMethodDescription) property
 1. Added [process Method](http://www.credreg.net/page/propertiesviewer#processMethod) property
 1. Added [staffQualification](http://www.credreg.net/page/propertiesviewer#staffQualification) property
 1. Added [staffQualificationDescription](http://www.credreg.net/page/propertiesviewer#staffQualificationDescription) property
 1. Changed targetCredential to [credentialProfiles](http://www.credreg.net/page/propertiesviewer#credentialProfiled) (all instances) 
 1. Renamed decisionInformationUrl property to [decisionInformation](http://www.credreg.net/page/propertiesviewer#decisionInformation)
 1. Add [decisionInformationDescription](http://www.credreg.net/page/propertiesviewer#decisionInformationDescription) property
 1. Change offeredByDirectoryUrl to [verificationDirectory] (http://www.credreg.net/page/propertiesviewer#verificationDirectory) and changed domain to VerificationServiceProfile
 1. Added [outcomeReviewDescription](http://www.credreg.net/page/propertiesviewer#outcomeReviewDescription) property
 1. Added scope note to [policiesAndProcedures](http://www.credreg.net/page/propertiesviewer#policiesAndProcedures) property
 1. Changed processCriteria property to [processStandards](http://www.credreg.net/page/propertiesviewer#processStandards) and updated definition.
 1. Added [processStandardsDescription](http://www.credreg.net/page/propertiesviewer#processStandardsDescription) property
 1. Dropped processCriteriaValidation
 1. Dropped publicInformationUrl
 1. Changed definition of [policiesAndProcedures](http://www.credreg.net/page/propertiesviewer#policiesAndProcedures) property

**Comment by jkitchensSIUC** [comment]
@siuc-nate this comprised many updates. Please review to be sure they're all completed. If anything is missing, be very specific. Post regardless here so we can close this one out.

**Comment by jkitchensSIUC** [comment]
Completed.
