### ISSUE TITLE
Indicate properties that are used for quality assurance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#170]
Is there a way within the schema to indicate which properties (aka roles) are used for quality assurance (e.g., "accredits") vs those that are not (e.g., "owns")?  It seems that the closest match to this would be our list of QualityAssuranceAction subclasses.

Also, is it possible for a property to be used both for QA _and_ non-QA? (e.g., "approves")

**Comment by stuartasutton** [comment]
There are two ways:

 1. Modify the definition of CredentialOrganization to say, for example, that ctdl:accredits is applicable to QA organizations; ***or***

 2. If you want to hardwire the semantics in definitively, create a QAcredentialOrganization subclass of CredentialOrganization and make the domain of these properties QAcredentialOrganization. If a property is applicable to instances of vanilla CredentialOrganizations and QAcredentialOrganizations, that can be handled in the same way.

**Comment by siuc-nate** [comment]
Note: This would also apply to CredentialAction related properties.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton is this a new QA related issue that we didn't discuss?  If this is already handled based on the agreed upon changes we discussed can it be closed? If not, what exactly is the issue? Maybe the issue was posted before we reviewed. It doesn't make sense to me.

**Comment by siuc-nate** [comment]
We decided to create the QACredentialOrganization subclass, and any properties exclusively tied to it would be indicated as being QA-related.

I believe we can close this issue.
