### ISSUE TITLE
Systematic review/discussion of CTDL serializations

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#171]
@mparsons1953, @CTITechPlanning, @jkitchensSIUC, & @science, we need to systematically review and discuss *each* of the the serializations of the CTDL for the 2016-11-17 release:

> **Context:** http://www.credreg.net/Page/serializations/#jsonSerialization
> **RDF/Turtle:** http://www.credreg.net/Page/serializations/#turtleSerialization
> **JSON-LD Schema:** http://www.credreg.net/Page/serializations/#jsonSchema

There are a number of issues needing discussing and some aspects needing completion. Here are ***some*** (probably needing their own individual github issues):

 1. Missing: Turtle encoding of properties.
 2. Handling with properties with comma-separated multiple ranges in the Turtle serialization (e.g., multiple rdfs:subClassOf on CredentialOrganization).
 3. How in JSON-LD schema to express cardinality, optionality, and vocabulary class constraints (i.e., acceptable vocabulary values).
 4. There are **two** possible and useful JSON-LD schemas: (a) a schema that is useful in validating the CTDL as a whole; and (b) a schema that defines an acceptable CER record (with constrains (cardinality, optionality, vocabulary class constraints)). **These are two distinct JSON-LD schemas with two distinct functions.** We currently have the first being generated directly from the CTDL spreadsheets; but, we no not have the second. Implementers building tools to generate records for the CER and others creating data for the CER outside the CE toolset are more likely to be interested in the second. 
 5. Some properties in the JSON-LD schema have arrays of "object" that should be ctdl:CredentialOrganization, ctdl:CredentialPerson. I did not check to see whether this was a more pervasive issue.
 6. Etc.
 7. Etc.

``` 
"ctdl:CredentialOrganization, ctdl:CredentialPerson; e.g.,
"ctdl:endorsedBy": {
				"type": "array",
				"items": {
					"type": "object"
				}
```

There are likely others and we should not conflate them all in this single issue. We should  use the "Serializations" label to cluster.

**Comment by jkitchensSIUC** [comment]
Looping in @siuc-nate

**Comment by siuc-nate** [comment]
We will hide the JSON schema validation until we are more certain about it.
