### ISSUE TITLE
Use of "Url" in property labels

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#172]
We need to add to our document of the CTDL the use of the suffix "Url" in property labels. 

In schema.org, "URL" is defined as a datatype (formatted string) and is literally meant to markup URL's in text. E.g., "The restaurant's homepage can be found at http://example.com/ApexRrestaurant." Similarly (but inconsistently), properties in schema.org that append the text "Url" to property name tokens mean that the range or value of the property is a text string following the HTTP protocol.

> ``` DataType > Text > URL```

The CTDL follows this general pattern with all properties with a label token suffix of "Url" having a literal range value of datatype xsd:Uri. 

This stands in sharp contrast to properties known as 'object properties' whose range is some resource, or object.  Object properties defined in the CTDL namespace (http://purl.org/ctdl/terms/) **never use** a suffix of "Url" even though the value (the range) is named by URI.

**Comment by jkitchensSIUC** [comment]
@CTITechPlanning @stuartasutton @siuc-nate do we need to talk about this Monday?

**Comment by stuartasutton** [comment]
Jeanne, as far as I can tell, the usage of the past few days regarding not adding a "Url" suffix to properties is spot on. I do think there are some cleaning up related to this in the CredentialAlignmentObject for which I will create an issue that reference this issue.

**Comment by jkitchensSIUC** [comment]
@siuc-nate please link the document with all URL updates here as well and ensure this is closed out.

**Comment by siuc-nate** [comment]
https://docs.google.com/spreadsheets/d/1j5fBG-dH29uRfo0Zln-Of7BTLIqW0aeuWyFb2CXaO1g/edit#gid=0

**Comment by siuc-nate** [comment]
Refer to Issue #192
