### ISSUE TITLE
CostType: Refine properties and usage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#174]
Updates from this spreadsheet:
https://docs.google.com/spreadsheets/d/19--mCccXkLeCxxQ74c1lx5_k31FCIyk-d-PRqHgQqls/edit#gid=0

Some additional ideas to consider/discuss:
- Augment (or replace) the CostType vocabulary with a literal ("costTypeDescription" or something similar)
- Augment (or replace) the AudienceType vocabulary with a literal ("audienceTypeDescription" or something similar)
- Drop Residency (it may be redundant with Jurisdiction)
- Update definitions (Vocabularies tab)

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton why do we have an ideas to consider list?  I thought we came up with some things to do now and had determined the larger issue now on GitHub as a Cost Manifest proposal.  In particular, the vocabulary definitions need to be updated but this says it's an idea.  Cost Profile is flagged as unstable but we need the vocabulary to work now or we cannot correctly portray costs.

**Comment by stuartasutton** [comment]
Yes, I thought we did as well. We decided to try the estimatedCost property to ConditionProfile so CostProfile would be available to avoid triggering TaskProfile. We also created an issue to look at CostManifest. I assigned CostManifest with the Release Subsequent milestone...i.e., not the 2016-11-17 Release

**Comment by siuc-nate** [comment]
I don't think we had completely discussed CostProfile when this issue was created.  I don't recall whether this issue was created before or during our meeting that day.  Regardless, Stuart's list makes sense.
