### ISSUE TITLE
JurisdictionProfile: remove "online"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#175]
Per the 11-9-16 call, online is not considered a jurisdiction or geopolitical area.  I believe online was originally added to handle things that were available online, which may have been relevant at the time (JurisdictionProfile was one of the first profiles we came up with).  I'm not sure if we lose anything meaningful by removing this field.

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

The ctdl:online property has been removed.
