### ISSUE TITLE
Update CredentialAction subclasses

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#178]
In light of the revisions stemming from the [Jurisdiction and Role Related Properties](https://docs.google.com/document/d/1fT8F2wBsbiPvWeBiDIaHiBT7HOD_AZXGL862emyOYQU/edit) review, we need to return to the [ctdl:CredentialingAction](http://www.credreg.net/page/propertiesviewer#CredentialingAction) subclasses to see the impact here (see green box lower right). 

![2016-11-10-agent-action-credential](https://cloud.githubusercontent.com/assets/2939046/20176926/f5ef7198-a6fe-11e6-80c5-814fbff1cada.png)
 
It seems to me that we have pruning to align with the changes and updating to do there as well prior to the release. We are better off pruning action subclasses of what is not clearly needed and adding later if circumstances require.

This issue is related to #102

**Comment by stuartasutton** [comment]
Also, these subclasses of [ctdl:CredentialingAction](http://www.credreg.net/page/propertiesviewer#CredentialingAction) need their domains updated to include ctdl:QAcredentialOrganization. My assumption is that these domain additions should be done so that they align with the domains column ([column 2]  (https://docs.google.com/document/d/1fT8F2wBsbiPvWeBiDIaHiBT7HOD_AZXGL862emyOYQU/edit)) Google Doc.

**Comment by jkitchensSIUC** [comment]
@stuartasutton I added this to the review list for Monday.

**Comment by jkitchensSIUC** [comment]
Updated on GitHub on November 14, 2016 and assigned to Stuart:
Actions to keep:
AccreditAction
ApproveAction
OfferAction
RecognizeAction
RegulateAction
RenewAction
RevokeAction
RightsAction

**Updated issue #178 to identify the actions that need to be deleted from the range of the ctdl:credentialingAction property:**

AdvancedStandingAction
AssessAction
ConferAction
CreateAction
EndorseAction
MonitorAction
OwnsAction
UpdateAction
ValidateAction
VerifyAction

**Comment by jkitchensSIUC** [comment]
The open item is to add the concepts included:
actionStatusType
URI: ctdl:actionStatusType
Label: Action Status Type
Definition: Indicates the current disposition of the action.
Concepts included: ActiveActionStatus, CompletedActionStatus, FailedActionStatus, and PotentialActionStatus.

**Comment by jkitchensSIUC** [comment]
On November 16, 2016 Nate added the concept scheme and definitions from Schema.org.  This is completed.
