### ISSUE TITLE
Adding "Term Status" as last row for properties/class tables

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#179]
Rather than relying totally on a "Release History" page to document what is unstable, I propose that we actually add a "Term Status" last row to property and class tables (and to the underlying RDF schema). Using this namespace (https://www.w3.org/2003/06/sw-vocab-status/ns# with the prefix "vs:") we can then add a value for "stable" & "unstable".  [They](https://www.w3.org/2003/06/sw-vocab-status/ns#)  also suggest having in the arsenal 'testing', and 'archaic'.

**Comment by siuc-nate** [comment]
This will be handled by the new spreadsheet/viewer mechanism
