### ISSUE TITLE
ConditionProfile: Add CostProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#181]
Per our 11/10/16 call:

In order to attempt to simplify the problem of CostProfile being within TaskProfile, is it worth adding CostProfile to ConditionProfile to simplify markup/entry of, for example, requirements.

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

The property ctdl:estimatedCost with the range of ctdl:CostProfile has been added to ctdl:ConditionProfile:

> http://www.credreg.net/page/propertiesviewer#estimatedCost 

It should be marked as **unstable**.

**Comment by jkitchensSIUC** [comment]
@stuartasutton CostProfile is included with the Unstable list here Inventory of Unstables
INVENTORY of "unstables" in the 2016-11-17 release #155
https://github.com/CredentialTransparencyInitiative/vocabularies/issues/155
https://docs.google.com/spreadsheets/d/1OEeqb53gPVkf5Fa-6BhWogvjSbqTpIuAxqz5HHWBGRw/edit#gid=0  

Can this issue be closed?  We could have an Unstable label and identify each class and property deemed unstable.

**Comment by stuartasutton** [comment]
We should now be able to designate either class or property as unstable.
