### ISSUE TITLE
OrganizationType: add Business

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#182]
@stuartasutton Per our 11/10/16 call, add the to the OrganizationType type vocabulary.  This is the definition agreed upon during the review.
Business: An organization that primarily sells products or services and employs one or more individuals.

**Comment by jkitchensSIUC** [comment]
I updated ctdl:OrganizationType
Term: ctdl:OrganizationType
Label: Business
Definition: An organization that primarily sells products or services and employs one or more individuals.

Closing this issue.
