### ISSUE TITLE
CredentialAction subclass deletes and verification

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#183]
As part of the pruning of the object properties via [Jurisdiction and Role Related Properties](https://docs.google.com/document/d/1fT8F2wBsbiPvWeBiDIaHiBT7HOD_AZXGL862emyOYQU/edit), the following subclasses of [ctdl:CredentialingAction](http://www.credreg.net/page/propertiesviewer#CredentialingAction) have been deleted:

> ctdl:AssessAction
ctdl:ConferAction
ctdl:CreateAction
ctdl:EndorseAction
ctdl:MonitorAction
ctdl:UpdateAction
ctdl:ValidateAction
ctdl:VerifyAction

The remaining subclasses of ctdl:CredentialingAction are:

> [ctdl:AccreditAction](http://www.credreg.net/page/propertiesviewer#AccreditAction)
[ctdl:AdvancedStandingAction](http://www.credreg.net/page/propertiesviewer#AdvancedStandingAction)
[ctdl:ApproveAction](http://www.credreg.net/page/propertiesviewer#ApproveAction)
[ctdl:OfferAction](http://www.credreg.net/page/propertiesviewer#OfferAction)
[ctdl:RecognizeAction](http://www.credreg.net/page/propertiesviewer#RecognizeAction)
[ctdl:RegulateAction](http://www.credreg.net/page/propertiesviewer#RegulateAction)
[ctdl:RenewAction](http://www.credreg.net/page/propertiesviewer#RenewAction)
[ctdl:RevokeAction](http://www.credreg.net/page/propertiesviewer#RevokeAction)
[ctdl:RightsAction](http://www.credreg.net/page/propertiesviewer#RightsAction) (i.e., actions of ownership in material or intellectual property)

 See related Issue #102

**Comment by jkitchensSIUC** [comment]
@stuartasutton can this be closed?

@siuc-nate making sure you saw this.

**Comment by stuartasutton** [comment]
I think this is ready to close
