### ISSUE TITLE
Delete AgentQAPurpose and agentQualityAssurancePurpose & Replace with Description and URL

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#185]
1. Delete ctdl:AgentQAPurpose (Enumeration)
2. Delete ctdl: agentQualityAssurancePurpose
3. Add to both CredentialOrganization and QACredentialOrganization two properties,  ctdl:agentPurposeDescription (literal) and  ctdl:agentPurpose (xsd:anyURI)

ctdl:agentPurposeDescription - A description of the primary purpose of the agent being referenced. 
Scope Note: For ctdl: QAcredentialOrganization  Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement.
ctdl:agentPurpose - A resource that describes the agent's primary purpose.
Scope Note: For ctdl: QAcredentialOrganization  Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement.

The Google Doc for reference is https://docs.google.com/document/d/16He3FM6Qa-PLKcRUaSWI3hNLEGpUYfB7TAOg8vhSAdE/edit?usp=sharing

**Comment by stuartasutton** [comment]
**ACTIONS TAKEN**

 1. Deleted ctdl:AgentQAPurpose
 2. Deleted ctdl: agentQualityAssurancePurpose
 3. Added [ctdl:agentPurposeDescription](http://www.credreg.net/page/propertiesviewer#agentPurposeDescription)
 4. Added [ctdl:agentPurpose](http://www.credreg.net/page/propertiesviewer#agentPurpose)
