### ISSUE TITLE
What property has ctdl:SkillExpressionType as range

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#186]
As part of the revisions  for issue #84 for AssessmentOpportunity and LearningOpportunity, there was a [SkillExpressionType](http://www.credreg.net/page/vocabulariesviewer#SkillExpressionType) vocabulary created. As far as I can tell, it is not within range of any property.

**Comment by jkitchensSIUC** [comment]
@stuartasutton SkillExpressionType is supplanted by the changes we made to learning opportunity and the upcoming assessment profile updates.  All of the SkillExpressionType vocabulary and related property should all be deleted.

**Comment by stuartasutton** [comment]
**ACTION TAKEN**

ctdl:SkillExpressionType vocabulary deleted.
