### ISSUE TITLE
Name changes to some CredentialAlignmentObject properties

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#189]
To continue cleansing "Url" as suffix of property names and to better identify three of the CredentialAlignmentObject properties, the following changes are proposed:

> **alignmentDate** (no name change)
**alignmentType** (no name change)
**codedNotation** (no name change)
**framework** (no name change)(remove definition reference to "URL")
**frameworkName** (no name change)
**targetDescription** (change to) **frameworkNodeDescription** 
**targetName** (change to) **frameworkNodeName** ("The name of a framework node.")
**targetURL** (change to) **frameworkNode** ("The node of a framework targeted by the alignment.")
**weight** (no name change)

**This issue is related to issue #172.**

**Comment by jkitchensSIUC** [comment]
@stuartasutton the naming proposal makes sense to me.  The renaming provides clearer context.  @siuc-nate do you have any thoughts about this?

**Comment by siuc-nate** [comment]
We are currently using CredentialAlignmentObject in places other than frameworks (e.g., vocabularies) - I am okay with using "framework" and "frameworkName"; however, for consistency with our other profiles, to retain flexibility of the CredentialAlignmentObject, and because it keeps us closer to the existing schema.org/AlignmentObject, I would very much prefer to keep the "target" properties.

**Comment by siuc-nate** [comment]
Per Stuart's updated suggestions as of our call on 11/15/2016:
- alignmentDate (no name change)
- alignmentType (no name change)
- codedNotation (no name change)
- framework (no name change)(remove definition reference to "URL")
- frameworkName (no name change)
- targetDescription (change to) targetNodeDescription
- targetName (change to) targetNodeName ("The name of a framework node.")
- targetURL (change to) targetNode ("The node of a framework targeted by the alignment.")
- weight (no name change)

**Comment by siuc-nate** [comment]
Refer to Issue #192 (not closing this just yet)

**Comment by siuc-nate** [comment]
These changes have been made.
