### ISSUE TITLE
Assessment Profile Updates From Group Review Held Nov 14, 2016

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#190]
@stuartasutton an itemized list of Assessment Profile updates are listed in the last column of this Google doc https://docs.google.com/document/d/1GboWMcGrhdFQUEadEJtYKBxzTcYrwLcd5Rf5NKtc1qc/edit?usp=sharing

All of the updates are applicable to the Nov. 17th release.

**Comment by stuartasutton** [comment]
**ACTIONS TAKEN**

From the [Assessment document](https://docs.google.com/document/d/1GboWMcGrhdFQUEadEJtYKBxzTcYrwLcd5Rf5NKtc1qc/edit), all of the additions/changes have been done. NOTE: The URLs below are also recorded in the Assessment document.

> http://www.credreg.net/page/vocabulariesviewer#assessMethod_Exam
http://www.credreg.net/page/vocabulariesviewer#assessMethod_Performance
http://www.credreg.net/page/vocabulariesviewer#assessMethod_Artifact
http://www.credreg.net/page/propertiesviewer#assessmentOutput
http://www.credreg.net/page/propertiesviewer#assessmentExample
http://www.credreg.net/page/propertiesviewer#hasGroupParticipation
http://www.credreg.net/page/propertiesviewer#hasGroupEvaluation
http://www.credreg.net/page/propertiesviewer#assessmentUseType
http://www.credreg.net/page/propertiesviewer#AssessmentUse
http://www.credreg.net/page/vocabulariesviewer#assessUse_Formative
http://www.credreg.net/page/vocabulariesviewer#assessUse_Summative
http://www.credreg.net/page/propertiesviewer#deliveryType
http://www.credreg.net/page/propertiesviewer#deliveryTypeDescription
http://www.credreg.net/page/propertiesviewer#isProctored
http://www.credreg.net/page/propertiesviewer#scoringMethodDescription
http://www.credreg.net/page/propertiesviewer#ScoringMethod
http://www.credreg.net/page/vocabulariesviewer#vocabulary_ScoringMethod
http://www.credreg.net/page/propertiesviewer#scoringMethodExampleDescription
http://www.credreg.net/page/propertiesviewer#scoringMethodExample
http://www.credreg.net/page/propertiesviewer#externalResearch
http://www.credreg.net/page/propertiesviewer#validationMethodDescription

The following have been added to the Scoring Method vocabulary spreadsheet but for some reason are not showing in the vocabulary viewer:

> NormReferenced
CriterionReferenced

**Comment by jkitchensSIUC** [comment]
Completed Nov 15, 2016.
