### ISSUE TITLE
Delete Quality Assurance Related Combos of Description and URLs from Process Profile 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#195]
On Nov 15th it was determined we should delete the following literals and xsd:anyURI properties from Process Profile. They had been included to match up to QA committee mockups.  We're going to hold a QA review and determine if they should be added back in along with potentially other information.

Delete all of the following:

- ctdl:decisionInformationDescription - Literal
- ctdl:decisionInformation - xsd:anyURI
- ctdl:outcomeReviewDescription - Literal
- ctdl:outcomeReview - xsd:anyURI
- ctdl:policiesAndProceduresDescription - Literal
- ctdl:policiesAndProcedures - xsd:anyURI
- ctdl:staffQualificationDescription - Literal
- ctdl:staffQualification - xsd:anyURI

Note that @siuc-nate may have identified some of the Urls with the Url clean up issue.  @siuc-nate should remove these so as not to confuse us now or later:

- ctdl:decisionInformation - xsd:anyURI
- ctdl:outcomeReview - xsd:anyURI
- ctdl:policiesAndProcedures - xsd:anyURI
- ctdl:staffQualification - xsd:anyURI

**Comment by siuc-nate** [comment]
These changes have been made.
