### ISSUE TITLE
VerificationServiceProfile Possible Property Change

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#197]
@stuartasutton we briefly looked at VerificationServiceProfile today http://credreg.net/page/domainsviewer#VerificationServiceProfile 

The only issue I see is it has a property, validationMethodDescription, with two potential changes:

1. Today we talked about it possibly being titled "validation..." because we had a validation profile at one point.  Should it be changed to verificationMethodDescription to be consistent with the other properties in that profile?  Follow above link to see the other properties.
2. I checked the Process Profile  http://credreg.net/page/domainsviewer#ProcessProfile to see if this is redundant but it doesn't look to be redundant.  However, ProcessProfile has other properties with "Method" related property names.  Should the renamed propert, verificationMethodDescription also include a Domain of ProcessProfile?  It already includes AssessmentProfile, Credential, LearningOpportunityProfile and VerificationServiceProfile.  It seems suited as well to ProcessProfile.

**Comment by siuc-nate** [comment]
These changes have been made.
