### ISSUE TITLE
Update to ctdl:accredits definition

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#200]
Action needed today.

Update ctdl:accredits  

Definition:
The agent being described gives a formal status to the resource being referenced based on the resource's conformance to prescribed standards or criteria

Scope Note:
Accredits includes the ongoing monitoring to confirm continued conformance to standards to maintain accreditation.

**Comment by siuc-nate** [comment]
I have made these changes.
