### ISSUE TITLE
Update to Recognizes Definition and Scope Note.

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#201]
Action needed today, update ctdl:recognizes definition and scope note. 

Recognizes 
Definition:
The agent being described recommends, endorses, indicates preference for, or otherwise provides positive judgement of a resource.

Scope Notes:
The agent being described may or may not use a set of formal recognition criteria.

**Comment by siuc-nate** [comment]
I have made these changes.
