### ISSUE TITLE
Mark properties unique to ctdl:CredentialPerson as vs:unstable

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#206]
Our understanding is that properties with either range or domain exclusively of ctdl:CredentialPerson should be marked as unstable, since the entire profile may be dropped:
- employee
- affiliation
- familyName
- givenName
- honorificSuffix
- worksFor

**Comment by stuartasutton** [comment]
Yes, these should be marked as unstable **immediately** with this release.

**Comment by siuc-nate** [comment]
I have marked these properties as unstable.
