### ISSUE TITLE
Drop ctdl:evaluates and ctdl:evaluatedBy

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#207]
These were not included after our reviews of role-related properties, but are still present in the spreadsheet. 

A previous issue (#51) indicates that all instances of assesses/assessedBy were changed to evaluates/evaluatedBy.  However, assesses/assessedBy were still present up until they were recently dropped.  I suspect something got missed along the way.

**Comment by stuartasutton** [comment]
Nate, if the bottom line dropping ctdl:evaluates and ctdl:evaluatedBy, it should happen **immediately** so the release is clean.

**Comment by siuc-nate** [comment]
I have removed these properties.
