### ISSUE TITLE
Fix duplicitous subproperty/subclass and equivalentTo connections

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#208]
Stuart previously indicated that a number of properties and classes were marked as being _both_ a subproperty/subclass of something _and_ equivalentTo it.  The spreadsheet needs to be scanned for such duplicates and cleaned up appropriately.

**Comment by stuartasutton** [comment]
These should be handled **immediately** with this release (see milestone added) by eliminating the "skos:ConceptScheme" from the "Subclass Of" row of the tables. It is applicable to **all** ctdl:ConceptSchemes; e.g.,

> http://www.credreg.net/ctdl/terms#ActionStatus

**Note 1:** Some have the "Subclass Of" value of "skos:ConceptScheme" twice!

**Note 2:** The ConcetSchemes with names ending in "Classification" have the same problem with removal of skos:ConceptScheme, **but do not delete the [ctdl:CredentialFramework](http://www.credreg.net/ctdl/terms#CredentialFramework) subclass!!**

**Comment by siuc-nate** [comment]
So the vocabulary classes should all have an "equivalentTo" skos:ConceptScheme rather than a "subclassOf" skos:ConceptScheme, correct?  This will require a (small) change to how the viewer works as well.

**Comment by stuartasutton** [comment]
N0! I see where my message was easily misinterpreted (and incomplete).

1. All of the concept scheme "Type of Term" skos:ConceptScheme. 
1. They are not "Subclass Of" skos:ConceptScheme. 
1. Like [ctdl:OccupationClassification](http://www.credreg.net/ctdl/terms#OccupationClassification), **all of the vocabularies** should be "Subclass Of" [ctdl:CredentialFramework](http://www.credreg.net/ctdl/terms#CredentialFramework).

**Comment by siuc-nate** [comment]
I have updated the spreadsheet to add a new "Vocabulary" section to explicitly indicate which classes are vocabulary classes (rather than relying on the presence of a reference to skos:ConceptScheme).  **I still have to remove the duplicates**, but I have made this structural change (and adapted the viewer to handle it) to the development and release spreadsheets and updated the servers. From an end-user perspective, it should look and function identically to how it did before.

**Comment by stuartasutton** [comment]
No.

All of the controlled vocabularies are "Type Of" skos:ConceptScheme. That's
all that is needed regarding SKOS. Since they *are* skos:ConceptScheme via
rdfs:type (i.e., "Type Of"), it's pointless to say they are "EquivalentTo"
what they already have been declared to be.

**Comment by siuc-nate** [comment]
I have removed the reference to skos:ConceptScheme from the equivalence and subclass sections.

I also corrected a few erroneous places where a property was referencing one of the vocabulary classes for its range instead of (or inaddition to) ctdl:CredentialAlignmentObject.

**Comment by stuartasutton** [comment]
Nate, in the places where you fixed the range from vocabulary class to CredentialAlignmentObject, did you add the nite to usage referencing the vocabulary as best practice?

**Comment by siuc-nate** [comment]
Would that usage note go on the vocabulary class or the property that points to the vocabulary (it would seem to make more sense on the property, since that is where the user might otherwise get lost with a CredentialAlignmentObject as the range)?

**Comment by stuartasutton** [comment]
On properties...this can close.
