### ISSUE TITLE
Drop ctdl:staffEvaluationUrl

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#209]
This was apparently missed at some point.

**Comment by stuartasutton** [comment]
OK, ctdl:staffEvaluationUrl has a status of "stable" in the current release. It should be IMMEDIATELY marked as "unstable" or **deleted** depending on what was previously determined.

NOTE, marked with 2016-11-17 milestone.

**Comment by siuc-nate** [comment]
I have removed the property.
