### ISSUE TITLE
Drop ctdl:versioning

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#213]
This appears to have been dropped from the Organization classes but is still present for Person.

**Comment by stuartasutton** [comment]
I think that it was a mistake not to catch it in ctdl:CredentialPerson. It is defined as "Description of how change is managed and documented by the described agent for all major credentialing system features" and that seems better handled elsewhere. 

**I suggest DELETING the property ctdl:versioning.**

**Comment by siuc-nate** [comment]
ctdl:versioning has been removed.
