### ISSUE TITLE
Add ctdl:contactType to ctdl:ContactPoint

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#214]
The need is to be able to associate some identifier with a given piece of information, e.g.:

"ctdl:telephone": [
   {
      "type": "ctdl:CredentialAlignmentObject",
      "ctdl:alignmentType": "tollFree",
      "ctdl:codedNotation": "1-800-555-1234"
   }
]
or
"ctdl:email": [
   {
      "type": "ctdl:CredentialAlignmentObject",
      "ctdl:targetNodeName": "main helpdesk",
      "ctdl:codedNotation": "abc@organization.com"
   }
]

Alternatively, it might be possible to enhance http://credreg.net/ctdl/terms/ContactPoint to do the job.

Thoughts?

**Comment by stuartasutton** [comment]
Nate, I'd prefer **not** doing this with AlignmentObject.  

There is already a discussion going on today at schema.org ([issue no. 1435](https://github.com/schemaorg/schemaorg/issues/1435#issuecomment-261689341)) about making ContactPoint within range of telephone and email which would make it possible to gather this additional data. I have marked this for "Release - Subsequent".

**Comment by siuc-nate** [comment]
Earlier today @mparsons1953 suggested adding ctdl:contactType to ctdl:ContactPoint (the property already exists in schema.org) to contextualize a given contact's phone number and/or email address. Would the name of this property conflict with our approach to vocabularies and instead require a different name (e.g. contactDescription)?

Would we need multiple ContactPoints for a given org (one for each phone number and email address), e.g.:
{
   "type": "ctdl:ContactPoint",
   "ctdl:telephone": "123-456-7890",
   "contactType": "customer service"
}

@stuartasutton do you have any thoughts on this?

**Comment by stuartasutton** [comment]
A property with the name ctdl:contactType would be OK for this purpose. Ir
doesn't really conflict with our naming convention.

**Comment by siuc-nate** [comment]
I have added ctdl:contactType to the **pending** spreadsheet.
