### ISSUE TITLE
ctdl:address has erroneous equivalentProperty of ctdl:JurisdictionProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#216]
There is an errors in the ctdl:address.

1. The class ctdl:JusrisdictionProfile that needs removing from equivalentProperty; and
2. schema:PostAddress needs to be removed from the range.

<img width="536" alt="screenshot 2016-11-19 07 35 41" src="https://cloud.githubusercontent.com/assets/2939046/20456443/b11ee7fe-ae2b-11e6-8f5a-508d739c4700.png">

**Comment by siuc-nate** [comment]
I have removed JurisdictionProfile from the equivalentTo section and removed schema:PostalAddress from the range.
