### ISSUE TITLE
Treatment of code blocks in documentation pages

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#217]
In creating the CTDL narrative documentation pages, we need to have a way to set off code (json, turtle etc.) both inline and as blocks. I can't replicate this inline here in github, but here's the block behavior absent, say, a fixed width font like courier:

```
{ "@context": { 
    "dc": "http://purl.org/dc/elements/1.1/", 
    "dct": "http://dublincore.org/terms/", 
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#", 
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#", 
    "ctdl": "http://purl.org/cdtl/terms/" 
    },
            "@id": "http://credentialEngine.org/credentials/CB8EB8D0-208D-4DA0-9F50-  
                        7003F8A39ED6",
            "@type": "ctdl:BachelorDegree", 
            "ctdl:name": {
                "@language": "en-US",
                "@value": "Bachelor of Science in Information Technology"
            },
```

**Comment by stuartasutton** [comment]
And, if this is possible to treat both inline by shifting to a {code} (fixed width) font and in blocks with the {code} font in with colored background (as above), I can include such encoding in my vanilla HTML for documentation files.

**Comment by siuc-nate** [comment]
Probably the best way to do this would be with a <pre> tag (renderable in the content documents by using [[pre]] and [[/pre]] ).  I'll set the site's CSS to render pre blocks sitewide the same way they currently render at the bottom of the competency schema page: http://credreg.net/ctdl/frameworkschema

**Comment by stuartasutton** [comment]
Nate, that will get is 1/2 there. The inline is likely harder; e.g., this probably won't work since [[pre]] will be interpreted as a separate block. 

"The [[pre]]ctdl:Agent[[/pre]] class should not be used; instead, use the more specific subclasses such as [[pre]]ctdl:CredentialOrganization[[/pre]] and [[pre]]ctdl:QAcredentialOrganization[[/pre]]."

The inline is really nothing more than a font shift--i.e., inline code represented as fixed-width font.

**Comment by siuc-nate** [comment]
I have setup both code and pre tags to work the same way, with an additional option of including an "inline" class to render smaller snippets inline, e.g.:

[[code]]This would be a block of code[[/code]]
This line includes [[code class="inline"]]some inline[[/code]] code.

I have updated the site, so this should be available now.

**Comment by stuartasutton** [comment]
Great!

**Comment by siuc-nate** [comment]
Note - browsers don't seem to like pre tags being inside paragraph tags, so it looks like only code tags (with the "inline" class) will work for inline things.
