### ISSUE TITLE
ctdl:Credential (and subs) have erroneous property dct:isPartOf in VIEWER

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#218]
In the viewer when looking at [ctdl:Credential](http://www.credreg.net/ctdl/terms#Credential) or any of its subclasses (e.g., [DigitalBadge](http://www.credreg.net/ctdl/terms#DigitalBadge)), they have a property listed of **dct**:isPartOf, **but** when you click the property and go to its table, you find the **CORRECT** ctdl:isPartOf not dct:isPartOf. 

The dct:isPartOf is correctly listed as an Equivalent Property.  

'Tis a mystery...

**Comment by siuc-nate** [comment]
We still had dct:isPartOf _and_ ctdl:isPartOf as properties on the spreadsheet - I have removed dct:isPartOf and updated the release data.
