### ISSUE TITLE
Discuss removal of ctdl:verificationMethodDescription from ctdl:Credential

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#222]
This property is already on ProcessProfile and VerificationServiceProfile - we need to determine whether or not it also belongs on Credential (where it currently also exists).

**Comment by stuartasutton** [comment]
I say we delete it NOW. It can always be added back in later should it be deemed necessary.

**Comment by siuc-nate** [comment]
I have removed the domain of Credential from the property of ctdl:verificationMethodDescription.
