### ISSUE TITLE
Remove ctdl:assessmentProfiled and ctdl:credentialProfiled from ctdl:LearningOpportunityProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#224]
These property seems to have been erroneously added at some point.  We use targetAssessment to point at an assessment that is associated with a Learning Opportunity, and there is no direct relationship between a Credential and a Learning Opportunity.

**Comment by siuc-nate** [comment]
@stuartasutton Can you confirm that the above comment is correct?  I want to double check before I do the removal.

**Comment by stuartasutton** [comment]
They don't make any sense to me. Delete.

**Comment by siuc-nate** [comment]
This has been taken care of.
