### ISSUE TITLE
Add a property to point to ctdl:scoringMethod vocabulary

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#229]
We currently have these properties:
- ctdl:scoringMethodDescription (literal) - The method used to score the assessment.
- ctdl:scoringMethodExample (URL) - A resource that is an example of the method or tool used to score the assessment.
- ctdl:scoringMethodExampleDescription (literal) - The text of an example of the method or tool used to score the assessment.

We have this vocabulary class:
- ctdl:scoringMethod

However, no property points to an AlignmentObject that would in turn point to that vocabulary. It seems we are missing something like ctdl:scoringMethodType (perhaps the first property should be renamed ctdl:scoringMethodTypeDescription to match?).

**Comment by stuartasutton** [comment]
Yes, analysis looks right....appears we are missing a scoringMethodType with range of CredentialAlignmentObject.

**Comment by siuc-nate** [comment]
I have added scoringMethodType to the **pending** spreadsheet.
