### ISSUE TITLE
Drop ctdl:PersonType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#230]
This vocabulary class has no terms or properties that point to it, and appears to have been left over from some earlier time.

**Comment by jkitchensSIUC** [comment]
We discussed this and marked it as unstable. See the unstable spreadsheet.

**Comment by stuartasutton** [comment]
It was not exactly left over, but ok to delete for now. 

We created it for type concepts since almost all the types on Organization didn't fit Person. Anyway, its destiny is tied up with the yet-to-be-determined fate of ctdl:CredentialPerson.
