### ISSUE TITLE
Rename ctdl:deliveryType or ctdl:DeliveryType to disambiguate

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#231]
To follow our existing pattern, we should probably rename ctdl:DeliveryType (the vocabulary class) to ctdl:Delivery or something similar - this would disambiguate it from the deliveryType property.

**Comment by stuartasutton** [comment]
This is obviously not easy. We should leave the property alone. 

Synonyms for "type" are few and none really appropriate and "Delivery" standing alone for the vocabulary is not the best...although we do do it elsewhere (e.g., Audience).

**Comment by stuartasutton** [comment]
Let's do the vocabulary as ctdl:Delivery

**Comment by siuc-nate** [comment]
I have made the update.
