### ISSUE TITLE
Explain CTDL use of properties with multiple "domains" and "ranges"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#232]
Many of our properties have multiple domains and ranges--i.e., many properties are used with more than one entity class and reference more than one class as values.  Our documentation needs to explain that the CTDL does not use rdfs:domain and rdfs:range in defining its terms but instead uses schema:domainIncludes and schema:rangeIncludes.  Since neither schema:domainIncludes nor schema:rangeIncludes have the same resulting formal entailments as rdfs:domain and rdfs:range, the use of schema:domainIncludes and schema:rangeIncludes is merely suggestive of customary use and create no inferencing incongruities.

**Comment by siuc-nate** [comment]
Agreed, but where in the documentation is the appropriate place for this information?

**Comment by siuc-nate** [comment]
Does this issue need to remain open?

**Comment by stuartasutton** [comment]
It can be deleted. It is already in the outline of the Overview.
