### ISSUE TITLE
Creating a /ctdl/docs purl structure for HTML pages of the CTDL specs

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#233]
Currently, we have no way within the context of CTDL to differentiate purls that directly identify serialization files of /terms/ and /vocabs/ and the human-readable HTML pages describing the terms and vocabs. I want to suggest that we create a new /ctdl/docs/ purl structure for CTDL (**for judicious use**):

* http://purl.org/ctdl/docs: (302) Human-readable and resolves to a master index page listing (links to) CTDL specs, their serializations etc. (see similar page on Dublin Core at http://dublincore.org/documents/.)
* http://purl.org/ctdl/docs/terms (302) Human-readable and resolves to http://credreg.net/ctdl/terms
* http://purl.org/ctdl/docs/vocabs (302) Human-readable and resolves to vocab classes at http://credreg.net/ctdl/terms (anchor?)

Thus we have the following purl pairs for machine access to code & human access to documentation:

* http://purl.org/ ctdl/terms | http://purl.org/ ctdl/docs/terms
* http://purl.org/ ctdl/vocabs/{ vary } | http://purl.org/ ctdl/docs/vocabs

**Comment by siuc-nate** [comment]
We will reexamine this when we have more documentation outside of the schema/viewers to show.
