### ISSUE TITLE
Change "ctdl" prefix to "ceterms" in tables & codings

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#235]
I am resurrecting a conversation started back on November 11th in an email exchange.

I want to change a non-normative part of our specification--the 'project-preferred' (suggested) prefix used to abbreviate the http://purl.org/ctdl/terms/ namespace in codings. The problem I am having is the fact that we use "CTDL" broadly (and appropriately) as the abbreviation for a description language that is comprised not only of the properties and classes in the /terms/ namespace but also of an array of separate concept scheme namespaces (e.g., /agentSector/, /assessMethod/ etc.) as well as guidelines etc. And yet, we use the namespace prefix "ctdl" for only part of it. 

> Change the current preferred prefix of "ctdl" to "ceterms" (throughout) with the 2016-12-05 release. 

Again, this is non-normative stuff and has no technical affect. But, what we put out there now as project-preferred prefixes is what people will tend to use in the long-term.

**Comment by siuc-nate** [comment]
If I'm interpreting you correctly, you want to replace every instance of ctdl: with ceterms: in the entire spreadsheet.  Is this correct?

**Comment by siuc-nate** [comment]
This change has been made.
