### ISSUE TITLE
Non-substantive revision of ceterms:ConditionProfile definition

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#239]
The is a suggested **nonsubstantive** clarification of the definition of ceterms:ConditionProfile currently defined as follows:

> "An entity relating a credential to profiles describing conditions to which the credential is subject during its lifecycle including the requirements to attain the credential."

...with related comment:

> "Related profiles include competencies, assessments, courses, and credentials required to attain the subject credential."

The use of the word "profiles" in the description is potentially confusing since CTDL uses profiles in a very different way (e.g., our model "profiles") as does the rest of the community (e.g., application profiles). In addition, the entities listed in the comment are not profiles.

The suggested revision:

> **Definition:** "A resource describing a condition between a  credential and other resources to which the credential is subject during its lifecycle including the requirements to attain the credential." 
> **Comment:** "Related resources include competencies, assessments, courses, and credentials whether required or recommended to attain the described credential."

**Comment by siuc-nate** [comment]
This has been taken care of.
