### ISSUE TITLE
Erroneous values on spatialCoverage property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#244]
The spatialCoverage property has "Subproperties Of" GeoCoordinates and JurisdictionProfile. These are errors. A property cannot have a class as a subproperty. They need to be removed.

Also, the following properties need to be added as "Subproperties Of" (kinds of) spatialCoverage:
> availableAt
jurisditionException
mainJurisdiction
region

**Comment by siuc-nate** [comment]
This has been taken care of.
