### ISSUE TITLE
Error in range of accreditedBy

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#245]
If we look at [accredits](http://www.credreg.net/ctdl/terms#accredits) in the viewer, we see that it has a domain of QACredentialOrganization (only) which seems right. But, if we look at [accreditedBy](http://credreg.net/ctdl/frameworkschema#accreditedBy), we see that it has a range of all three Agent subclasses (i.e., CredentialOrganization, CredentialPerson & QACredentialOrganization). I believe this is a result of an error in the release spreadsheet (see [pending spreadsheet] (https://docs.google.com/spreadsheets/d/1Bw94UrAWwno9gFg7yOZjnTGq9XUlsyYrgEi_FwgZ_tY/edit#gid=0) which currently says: 

> Range: accreditedBy | expand:Agent

... instead of the correct:

> Range: accreditedBy | QACredentialAgent

Is my analysis of the mechanics of the new spreadsheets (release & pending) accurate?

**Comment by siuc-nate** [comment]
Yes, the expansion mechanic is a feature of the spreadsheets/viewer I haven't had a chance to talk through with you yet, but that is the gist of it.

**Comment by stuartasutton** [comment]
So, (doing my first edit to the new pending spreadsheet), should I make the correction?

**Comment by siuc-nate** [comment]
We currently have the spreadsheets open and are making corrections - we can take care of this one.

**Comment by siuc-nate** [comment]
I have made this change for accreditedBy and regulatedBy.  This change should only be made for properties that are strictly QA - if they apply to QA and other types of orgs, then expand:Agent is correct.
