### ISSUE TITLE
schema:Course & ctdl:Course both present as classes

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#246]
We have a schema:Course in our class listing. Note that since it has a prefix of "schema" as opposed to "ctdl", it appears at the end of the class TOC listing. In the spreadsheet, these variances show up in the following:

> Range: ctdl:learningOpportunityOffered | ctdl:Course
> Equivalent To: ctdl:Course | schema:Course
> SubsetOf: schema:Course | schema:CreativeWork
> Class: schema:Course

The result is that [schema:Course](http://credreg.net/ctdl/frameworkschema#Course) looks like this and ctdl:Course is nowhere to be seen:

![screenshot 2016-11-28 07 21 51](https://cloud.githubusercontent.com/assets/2939046/20673847/8125894c-b53b-11e6-82c1-2c24cccdf5b0.png)

So, this should table should be ctdl:Course which leads me to assume:

> Class: ctdl:Course

...I have no clue why we aren't seeing the Equivalent To of schema:Course in the table. But I am still wrestling with the new spreadsheet...

**Comment by siuc-nate** [comment]
You are correct - the schema:Course entry should have been ctdl:Course, and the equivalentTo section should reflect that ctdl:Course is equivalent to schema:Course.  I have made these changes.
