### ISSUE TITLE
Determine usage of ctdl:Course

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#249]
http://credreg.net/ctdl#Course

What is the intended purpose of this profile?  These seem to be redundant with learning opportunity profile.

**Comment by stuartasutton** [comment]
@siuc-nate there is **no such thing as a Course profile**. This was supposed to be another class without properties (e.g., like [Agent](http://www.credreg.net/ctdl/terms#Agent)) and equivalently classed to schema:Course.  But, I see that it now has the property ctid (artifact of a global add process?) and has three properties with it in range (hasPart, isPartOf, and learningOpportunityOffered? These ranges should not have been added.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton we should talk about this and how we're currently using LearningOpportunityProfile for everything including courses.

**Comment by siuc-nate** [comment]
I have removed the properties from the development spreadsheet - they'll be removed from production/release when I get the update out for the serializations page.
