### ISSUE TITLE
Drop ctdl:RenewalProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#251]
Not sure how this slipped by - renewal is handled via ConditionProfile.

http://credreg.net/ctdl#RenewalProfile

**Comment by stuartasutton** [comment]
Can you be more specific as to 'how'?

**Comment by jkitchensSIUC** [comment]
Remove this now and close this issue.  With next release, include this with a note stating the reason for the removal.  Include with the first release History.

**Comment by siuc-nate** [comment]
This has been taken care of.
