### ISSUE TITLE
History Note Needed for February 11, 2017 Release

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#255]
On November 29, 2016 ceterms:RenewalProfile was removed from CTDL.  It was erroneously included.  This needs to be included with the January 31, 2017 History notes.  Below is a copy paste from the deleted class.

URI: ceterms:RenewalProfile 
Label: Renewal Profile 
Definition: The conditions and methods by which a credential must be renewed by its holder. 
Comment:  
Type of Term: rdf:Class 
Usage Note:  
Status: vs:stable 
Subclass Of: 
schema:CreativeWork 

Domain Includes:  
Range Includes:  
Equivalent Classes:  
Subclasses:  
Properties: 
ceterms:ctid 

JSON Format: View JSON

**Comment by siuc-nate** [comment]
Noted in history tracking.
