### ISSUE TITLE
Better definitions for "profiled" properties vs their equivalent "target" properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#256]
In CTDL, we have the following "profiled" properties, which I believe were originally intended to serve as inverse properties:
- ceterms:assessmentProfiled
- ceterms:conditionProfiled
- ceterms:credentialProfiled
- ceterms:learningOpportunityProfiled
- ceterms:taskProfiled

We also have the following "target" properties, which point to the same entities:
- ceterms:targetAssessment
- ceterms:targetCompetency
- ceterms:targetCompetencyFramework
- ceterms:targetCredential
- ceterms:targetLearningOpportunity
- ceterms:targetNode
- ceterms:targetNodeDescription
- ceterms:targetNodeName
- ceterms:targetPathway
- ceterms:targetTask

Do we need both sets? Do they need to align better?  

Also, the definitions are wildly inconsistent - it might be worth reviewing these as well.

**Comment by stuartasutton** [comment]
@siuc-nate, "target" properties always point forward while "Profiled" properties always point back to a think being profiled. Thus they are two different categories of properties and serve two different purposes.

**(1) assessmentProfiled | targetAssessment**

>*(AssessmentProfile==estimatedCost==>CostProfile)*
>CostProfile==assessmentProfiled==>AssessmentProfile (points back)
>
>AssessmentProfile==targetAssessment==>Assessment (points forward)

**(2) conditionProfiled | targetCondition (does not exist)**

> *(ConditionProfile==targetLearningOpportunity==>LearningOpportunity)*
> LearningOpportunity==conditionProfiled==>ConditionProfile. (points back) 

**(3) credentialProfiled | targetCredential**

Various profiles (Condition, Earnings, EmploymentOutcome, Holders, Revocation, Verification) use credentialProfiled to point back to the Credential (and subclass) they profile; e.g.

> ProcessProfile==targetCredential==>Credential) (points forward)

**(4) learningOpportunityProfiled | targetLearningOpportunity**

The Condition and Process profiles point forward to a LearningOpportunity with targetLearningOpportunity. 

> ConditionProfile==targetLearningOpportunity==>LearningOpportunityProfile (points forward)
ProcessProfile==targetLearningOpportunity==>LearningOpportunityProfile (points forward)

CostProfile has learningOpportunityProfiled and a **MISSING** range LearningOpportunityProfile:

> *(LearningOpportunityProfile==estimatedCost==>CostProfile)*
CostProfile==learningOpportunityProfiled==>LearningOpportunityProfile (points back)

**(5) taskProfiled | targetTask**

>(TaskProfile==estimatedCost==>CostProfile)
>CostProfile==taskProfiled==>TaskProfile (points back)
>
>ConditionProfile==targetTask==>TaskProfile (points forward)

**Comment by stuartasutton** [comment]
Of course, nothing says we have to 'point back'. If not, then all five properties could be eliminated:

>ceterms:assessmentProfiled
ceterms:conditionProfiled
ceterms:credentialProfiled
ceterms:learningOpportunityProfiled
ceterms:taskProfiled

**Comment by siuc-nate** [comment]
I have corrected the missing learning opportunity profile range - it will go out along with the update to serializations.  Per our 12/1/2016 meeting, we still need to review the definitions at a later date.
