### ISSUE TITLE
JSON schema needs to be clarified as to what it actual does/should represent

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#257]
We need to discuss the CER JSON Schema (validation) and answer with certainty the question as to whether what we have is a json (validation) schema for acceptable records for the CER or of the CTDL as a whole. While the later would be 'interesting', people wanting to generate "records" for submission to the CER need the first.

**Comment by siuc-nate** [comment]
Per our call yesterday, we are on the same page that this is intended to validate records.

**Comment by stuartasutton** [comment]
@mparsons1953 being a bit more specific, the JSON Schema is intended to validate records destined for the CER; use is targeted at tool implementors and people wanting to generate data acceptable for ingest.
