### ISSUE TITLE
CostProfile has a range of estimatedCost.

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#258]
CostProfile has a range of estimatedCost. Classes don't have ranges.

**Comment by siuc-nate** [comment]
I think you might be misreading the "in range of" row:
![image](https://cloud.githubusercontent.com/assets/21346519/20811776/9408ce52-b7d4-11e6-948c-c1909b1f60cf.png)

The intent of the "in range of" row (vs the "range includes" row) is to indicate properties that point to this class.
