### ISSUE TITLE
Removing from serializations "classification" concept classes

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#260]
We should discuss removing the following classes from the concept scheme listing on the [Serializations page](http://www.credreg.net/ctdl/schema):

* `ceterms:IndustryClassification`
* `ceterms:InstructonalProgramClassification`
* `ceterms:OccupationClassification` 

**These are not *specific* concept schemes, but classes for clustering kinds of concept schemes.** For example, the Standard Occupational Classification (SOC) system in the U.S. and the European Skills/Competences, Qualifications and Occupations (ESCO) are concept schemes of the class  `ceterms:OccupationClassification`. So, when these vocabularies are actually modeled in RDF/SKOS, they can declare themselves as subclasses of `ceterms:OccupationClassification`. In a semantic system, one could ask to see all the concept schemes of the class `ceterms:OccupationClassification` and pull up SOC and ESCO.

**Comment by siuc-nate** [comment]
How should these be represented in the serializations?

**Comment by stuartasutton** [comment]
**Not at all.** We need to start advising holders of such concept schemes to note the their schemes are of that class...i.e., an issue of socialization.

**Comment by siuc-nate** [comment]
Should they still show up in the viewers?

If so, then does the logic for not showing them in the serializations extend to other property-less classes like LearningResource, Assessment, LearningOpportunity, etc.?

**Comment by stuartasutton** [comment]
Yes, they should be in the viewers as a class.  It was in the listing of actual vocabularies on the serialization page that they made no sense.

**Comment by siuc-nate** [comment]
I have moved these from the "vocabulary classes" section to the "classes" section (a change in the "type of term" from ConceptScheme to Class)
