### ISSUE TITLE
Change "statusType" prefix to "credentialStat" in vocabulary terms

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#263]
Looks like this was missed - hopefully the last bug.

**Comment by stuartasutton** [comment]
Nate, where are you seeing this? I can't find it.

**Comment by siuc-nate** [comment]
http://credreg.net/ctdl/terms/CredentialStatus

Its concepts should be prefixed with "credentialStat" not "statusType"

**Comment by stuartasutton** [comment]
I see it here:

> http://www.credreg.net/ctdl/terms#CredentialStatus

But it appears changed in https://docs.google.com/spreadsheets/d/1Bw94UrAWwno9gFg7yOZjnTGq9XUlsyYrgEi_FwgZ_tY/edit#gid=0 

So, I am confused...

**Comment by siuc-nate** [comment]
Yes, I haven't updated the server yet - I wanted to make sure I didn't make such a change if it was something that needed to be documented or wait until the next version.

**Comment by stuartasutton** [comment]
Nope...no need to wait

**Comment by siuc-nate** [comment]
Done.
