### ISSUE TITLE
Delete "prefix" information in skos:scopeNote value text

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#266]
@siuc-nate, the ttl and json text for for Scope Note includes the property prefix when it should not. A property can only have one scope note. So, in the following ttl and json serializations for http://credreg.net/ctdl/pending#degreeConcentration and in the table text for Scope Note, the `ceterms:degreeConcentration:` should not be there:

>"ceterms:degreeConcentration: Where possible, values should be taken from published frameworks defining degree majors, minors, and concentrations such as the U.S. National Center for Education Statistics' (NCES) Classification of Instructional Programs (CIP)."@en-US ;

This is true for all Scope Note entries.

**Comment by siuc-nate** [comment]
I have updated the viewer and serializations system.

Note that this prefix was originally displayed to accommodate situations where a usage note might be specific to a combination of property and domain (based on our earlier discussions about trying to have jurisdiction text vary by context) and thus something might have multiple usage notes.

**Comment by stuartasutton** [comment]
Variance should be in usage.
