### ISSUE TITLE
Reconsider assigning ctid as domain to many entities

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#267]
We need to revisit this issue and perhaps eat some crow. The CTID has lost all of its original meaning through use across many entities. Read the current definition of the ctid property:

>A globally unique Credential Transparency Identifier (CTID) issued by the Credential Registry Service (CRS) by which the creator/owner/provider of a credential recognizes the credential in transactions with the external environment (e.g., in verifiable claims involving the credential).

and Comment:

> A CTID is resolved through the CRS returning the Credential Registry data describing the identified credential. The CTID is the equivalent of a version identifier for the credential. Different versions of a credential are considered distinct expressions and each must be assigned its own CTID. Each version of a credential can have only one CTID assigned by the Credential Registry Service (CRS) upon registration with the Credential Registry. However, a single version of a credential may have distinct identifier values for both the ctid property and the credentialId property. In such a case both identifiers will be recognized by the credential creator/owner/provider in transactions with the external environment.

**Comment by stuartasutton** [comment]
After today's discussion, we decided to backtrack on the general application of the CTDL to nearly all entities limiting its use to identifying instances of Credential and its subclasses (as originally intended). 

> **ACTION TO BE TAKEN:**
(1) Remove the `ceterms:ctdl` property from all but`ceterms:Credential` and its subclasses; and
(2) The need for the other entities to have URIs remains; they can be generated by appending vanilla UUIDs to the base namespace (PURLs?).

Avoid use of the ceterms:url property for the intended URI of the resource being described. In JSONLD, this should be the @id of the resource. Thus, e.g., 

```  
ceterms:mainJurisdiction": {
   "@type": "ceterms:GeoCoordinates",
   "@id": "http://geonames.org/6252001/",
   "ceterms:name": "United States",
   "ceterms:latitude": 39.76,
   "ceterms:longitude": -98.5
        } 
```

... instead of

```  
ceterms:mainJurisdiction": {
   "@type": "ceterms:GeoCoordinates",
   "ceterms:name": "United States",
   "ceterms:url": "http://geonames.org/6252001/",
   "ceterms:latitude": 39.76,
   "ceterms:longitude": -98.5
        } 
```

**Comment by siuc-nate** [comment]
Regarding action 2 above, it would be ideal to have a property that mirrors the usage of CTID (perhaps without the overhead of a URN prefix) so that the CER APIs can have a predictable input to deal with.  For example, a property that is a subproperty of the credentialId property that is reliably a simple UUID.

**Comment by siuc-nate** [comment]
I have removed ceterms:ctid from all non-credential classes in pending CTDL.

**Comment by stuartasutton** [comment]
Nate, is there no way that the CER couldn't handle this locally without burdening CTDL overall? We know that we have a difficulty with entities needing URI having them at the same time that we don't want people thinking that, say, the URI of the Credential or CredentialOrganization or Learning Opportunity is just another property resulting in a mass of nothing but bnodes and, as a result, no Linked Data. That's my fear. 

**Maybe we could have a discussion (to fill me in) on the role of the CER APIs.**

**Comment by jkitchensSIUC** [comment]
See issue #310

**Comment by siuc-nate** [comment]
Specifically, ceterms:ctid has been removed from the domains of:

ceterms:AccreditAction
ceterms:AdvancedStandingAction
ceterms:ApproveAction
ceterms:AssessmentProfile
ceterms:CareerPathway
ceterms:Competency
ceterms:CompetencyFramework
ceterms:ConditionProfile
ceterms:ContactPoint
ceterms:CostProfile
ceterms:CredentialAlignmentObject
ceterms:CredentialFramework
ceterms:CredentialingAction
ceterms:CredentialOrganization
ceterms:CredentialPerson
ceterms:DurationProfile
ceterms:EarningsProfile
ceterms:EmploymentOutcomeProfile
ceterms:FinancialAlignmentObject
ceterms:GeoCoordinates
ceterms:HoldersProfile
ceterms:IdentifierValue
ceterms:IdentifierValueSet
ceterms:JurisdictionProfile
ceterms:LearningOpportunityProfile
ceterms:OfferAction
ceterms:PostalAddress
ceterms:ProcessProfile
ceterms:QACredentialOrganization
ceterms:RecognizeAction
ceterms:RegulateAction
ceterms:RenewAction
ceterms:RevocationProfile
ceterms:RevokeAction
ceterms:RightsAction
ceterms:TaskProfile
ceterms:VerificationServiceProfile
