### ISSUE TITLE
Missing range of LearningOpportunity on targetLearningOpportunity

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#270]
With `AssessmentProfile`, the `targetAssessment` property has a range of both `AssessmentProfile` and `Assessment`:

> AssessmentProfile==targetAssessment==>AssessmentProfile
AssessmentProfile==targetAssessment==>Assessment 

While with `LearningOpportunityProfile`, the `targetLearningOpportunity` has  range of only `LearningOpportunityProfile` and not `LearningOpportunity`: 

> LearningOpportunityProfile==targetLearningOpportunity=>LearningOpportunityProfile

so, `LearningOpportunityProfile` should also have:

> LearningOpportunityProfile==targetLearningOpportunity=>LearningOpportunity

...because without it, `LearningOpportunityProfile` can't point to an actual learning resource but instead points resursively to `LearningOpportunityProfile`.

**Comment by siuc-nate** [comment]
I have added ceterms:LearningOpportunity to the range of ceterms:targetLearningOpportunity in the pending CTDL

Note: ceterms:targetLearningOpportunity does **not** have a domain of ceterms:LearningOpportunityProfile (A learning opportunity profile points to another learning opportunity profile via its hasPart property as a means of constructing a hierarchy of learning opportunity profiles)

**Comment by stuartasutton** [comment]
I find it odd that a LearningOpportunityProfile cannot point to things of
the class LearningOpportunity. In the context of CTDL, an instance of
schema:Course would be an instance of LearningOpportunity. So, a
LearningOpportunityProfile can't point to that schema:Course?

**Comment by siuc-nate** [comment]
I don't disagree - what you say makes sense. I just wanted to note that it was not currently the case, in case it's something we want to change.

**Comment by stuartasutton** [comment]
OK. Then ceterms:targetLearningOpportunity should have a domain of ceterms:LearningOpportunityProfile as well. That fixes it, right?

**Comment by siuc-nate** [comment]
Done.
