### ISSUE TITLE
Added 'usage note' to LearningOpportunity class

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#271]
I added the following Usage Note to the `ceterms:LearningOpportunity`:

> "Types of learning opportunities such as a Courses class in other namespaces (e.g., schema.org/Course) may be declared as subclasses of ceterms:LearningOpportunity to support their discovery through applications processing CTDL data."

The intention is to encourage 3rd parties developing learning opportunities to declare them as a subclass of `ceterms:LearningOpportunity`.

**Comment by siuc-nate** [comment]
Noted in history tracker.
