### ISSUE TITLE
Consider deprecating ceterms:Course

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#272]
Given the `ceterms:LearningOpportunity` class, let's consider deprecating `ceterms:Course`.

See companion #271

**Comment by stuartasutton** [comment]
I say "consider" because this may not be so simple to deprecate ceterms:Course. We have a commitment to utilization of schema:Course. However, should we want to extend it for the CE context, we'd probably want it as a class. So, sort of thinking out loud.

**Comment by siuc-nate** [comment]
We reviewed this and agree we should keep it as a class - we should discuss it further.

**Comment by stuartasutton** [comment]
Since we have agreement (until circumstances say otherwise), why don't we close this issue?
