### ISSUE TITLE
Remove CER Vocabulary Prefix:

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#273]
@siuc-nate the CTDL tables http://credreg.net/ctdl/terms should not include CER-specific references. For example, remove "CER Vocabulary Prefix:" We need to setup a completely separate CER (Credential Engine Registry) application profile where CER-specific information needs to go.

Below are additional updates that are needed:

- Change Label to Preferred Label

 For only "Concept" tables **remove** the following:

- Subconcept Of:
- Range Includes:	
- Equivalent Concept:	
- Subconcepts:

 For only "Concept" tables **add** the following:

- Broader Concept:

- Narrower Concept:

The Organization Type and Audience Levels both use Broader and Narrower. This needs to be corrected with Organization. Type.  The Google doc I created with the updates for Audience Level show the broader and narrower concepts https://docs.google.com/document/d/1P-3EOR0U-pCuM4qqYsMwOEcfNRHxjHuNKcYHwv6E6SQ/edit?usp=sharing 

The vocabulary spreadsheet saved in Google drive (that's no longer used) https://docs.google.com/spreadsheets/d/1ir1wEF4R2wCG7UME--WJnlib6z1fLTdc5_icXbsAFz0/edit?usp=sharing shows the following in the (skos:broader) column:

Vocabulary (skos:ConceptScheme) / **Term (skos:Concept)** / Preferred Label (skos:prefLabel) / **Broader (skos:broader)**

ctdl:OrganizationType	**orgType:NonTraditional**	Alternative/Non-Traditional School	**secondarySchool**

ctdl:OrganizationType	**orgType:FourYear**	Four-Year College	**postsecondary**

ctdl:OrganizationType	**orgType:HighSchool**	High School	**secondarySchool**

ctdl:OrganizationType	**orgType:Magnet**	Magnet/Competitive Admissions School	**secondarySchool**

ctdl:OrganizationType	**orgType:Technical**	Career and Technical School	**secondary**

ctdl:OrganizationType	**orgType:TwoYear**	Two-Year College	**postsecondary**

**Comment by siuc-nate** [comment]
- CER vocabulary prefix rows have been hidden
- Label changed to Preferred Label
- Range, Equivalent, and Sub[property/class/concept][ of] rows will not show if there is no data
- Subconcept of/Subconcepts labels changed to Broader/Narrower
