### ISSUE TITLE
Switch order of viewer table rows "Properties" and "In Range Of"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#274]
When looking at the Class tables, it is very easy to get the rows "Properties" and "In RangeOf" confused. We land the class table and scroll down for properties and the first properties we see are the "In RangeOf". There will be people that think they are looking at the class properties when they are not. While seemingly subtle, just switching the order of the two rows will help avoid the confusion--i.e., when you scan down a class table the first row relating to properties is "Properties" followed by "In Range Of".

**Comment by siuc-nate** [comment]
This change has been made.
