### ISSUE TITLE
Credential not showing all of its subclasses

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#277]
The [`ceterms:Credential`](http://credreg.net/ctdl/terms#Credential) class is not showing all of its subclasses.

**Comment by siuc-nate** [comment]
Credential shows its direct subclasses - you must go to those subclasses to see their subclasses.  For example:
http://credreg.net/ctdl/terms#Credential shows http://credreg.net/ctdl/terms#Degree
http://credreg.net/ctdl/terms#Degree shows http://credreg.net/ctdl/terms#DoctoralDegree
http://credreg.net/ctdl/terms#DoctoralDegree shows http://credreg.net/ctdl/terms#ProfessionalDoctorate

Should sub-subclasses be shown within the subclasses section?

**Comment by stuartasutton** [comment]
Nate, given the way the viewer handles this, it makes sense "as is" if you
are aware that you have to look at the listed subclasses to see any of them
have subclasses. So, this is not really any kind of error. It just seemed
at first glance like it was an error...and that's the problem...since some
may just look at those listed immediately under the superclass and not go
look any further. I don't really have any solution :-(. In the Overview,
I'll be listing out as a tree the full hierarchy of class/subclass for
Credential.

**Comment by siuc-nate** [comment]
The "Useful Groups" section at the bottom of the viewer exists to handle problems like this - it shows all of the Credential subclasses.

Does this issue need to remain open?

**Comment by stuartasutton** [comment]
No. It does not.
