### ISSUE TITLE
Jurisdiction vs. Region

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#278]
We have two properties that are semantically the same. The `ceterms:jurisdiction` property superceded the `ceterms:region` property some time ago but `ceterms:region` wasn't completely deleted.  I suggest that we deprecate `ceterms:region` "as semantically equivalent".

[ceterms:jurisdiction](http://credreg.net/ctdl/terms#jurisdiction):
> The geo-political region in which the described resource is applicable.

[ceterms:region](http://credreg.net/ctdl/terms#region):
> A geo-political area of the described resource.

**Comment by stuartasutton** [comment]
This "issue" was perhaps a bit hasty. The `ceterms:region` is useful where the intention is to simply identify an area. The `ceterms:jurisdiction` makes it possible to be more descriptive where useful. Both point to GeoCoordinates. I'll make that distinction in the documentation

**Comment by siuc-nate** [comment]
Does this issue need to remain open?

**Comment by stuartasutton** [comment]
No
