### ISSUE TITLE
Add ceterms:LearningOpportunityProfile to range of ceterms:object

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#279]
Currently, `ceterms:object` does not have `ceterms:LearningOpportunityProfile` in it's range. As a result, we cannot have a `ceterms:AccreditAction` that accredits a program of study. E.g., my (classic) *SRJC Dental Assisting Certificate* is the result of a ceterms:LearningOpportunityProfile (instructional program) that has been accredited by the Commission on Dental Accreditation...i.e., the Commission does not accredit the certificate, but the program of study resulting in the certificate.

**Comment by stuartasutton** [comment]
The result looks like the following:

![fig 4a](https://cloud.githubusercontent.com/assets/2939046/21581223/faf54a58-cfdc-11e6-8240-1f6b704c5231.png)

**Comment by siuc-nate** [comment]
Would this be a normative change?

**Comment by stuartasutton** [comment]
No, it would not affect existing systems since it enlarges application and
does not affect any implementations. If we were going the other way and
taking away LearningOpportunityProfile from the range, it would be a
problem.

**Comment by siuc-nate** [comment]
This has been added to the pending CTDL.
