### ISSUE TITLE
Update processMethodType property language referencing vocab ProcessMethod

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#280]
The Usage Note for [`ceterms:processMethodType`](http://www.credreg.net/ctdl/terms#processMethodType) property (range `CredentialAlignmentObject`) references a deleted vocabulary called `ProcessMethod` that used to contain the following concepts:

> AdvisoryGroup
ExpertReview
FocusGroup
MajorChangeReport
MajorIncidentReport
SiteVisit
ValidationSurvey
WrittenReport

The vocabulary was last seen in the old spreadsheet on Nov. 11. **If legitimately gone**, the text of the property Usage Note needs to be cleaned up. And, what vocabulary should it reference?

**Comment by siuc-nate** [comment]
According to:
https://docs.google.com/spreadsheets/d/1dPMEMYB7LLMn9mAZMFRh70TA7a4_fqS8hgWb3T8pN8s/edit#gid=0

We eliminated this vocabulary.  We added "processMethod" and "processMethodDescription" which are a URL and literal, respectively.  The processMethodType property should be removed.

**Comment by siuc-nate** [comment]
I have removed ceterms:processMethodType from the pending CTDL
