### ISSUE TITLE
Correct use of PURL vocabulary prefix in viewer

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#281]
@stuartasutton 
Related to issue #273 the CER vocabulary prefix rows in the concept scheme tables exist to tie those schemes to their respective PURLs (where such PURLs exist - two of them are still unstable).

For example, if you click on any of the vocabulary prefixes in the table at the top of the viewer ( http://credreg.net/ctdl/terms ), you will be taken to that concept scheme.

If there is a correct way to show this data (or if it should be hidden), let me know and I will update the viewer.

**Comment by stuartasutton** [comment]
Nate, it's not a matter of correct/incorrect. The usage notes usually (should always) say something about best practice on vocabulary pick without requiring a particular vocabulary. Perhaps the link could be there in the usage note?

**Comment by siuc-nate** [comment]
I have hidden the data from the concept scheme tables.
