### ISSUE TITLE
Correcting minor typos

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#282]
ceterms:OrganizationType -
Comment corrected "credentialling" to "credentialing"

ceterms:AgentSector - 
Comment corrected "associatiton" to "association"

These changes have been made in the pending and current CTDL.

**Comment by siuc-nate** [comment]
ceterms:AssessmentProfile
Comment corrected "evalutation" to "evaluation"

ceterms:Competency
Definition corrected "peson" to "person"

ceterms:CredentialAlignmentObject
Comment corrected "specilized" to "specialized"

ceterms:CredentialFramework
Comment corrected "proficienty" to "proficiency"

ceterms:CredentialingAction
Definition corrected "resourse" to "resource"

ceterms:JurisdictionProfile
Definition corrected "informaton" to "information"

ceterms;MasterCertificate
Definition corrected "the the" to "the"

ceterms:HoldersProfile
Definition corrected "stastical" to "statistical"

ceterms:administrationProcess
Usage Note corrected "the the" to "the"

ceterms:hasPart
Usage Note corrected "partative" to "partitive"

ceterms:employmentOutcome
Definition corrected "occupaion" to "occupation"

ceterms:latestVersion
Definition corrected "lastest" to "latest"

ceterms:isPartOf
Definition corrected "ther" to "the"

ceterms:offeredBy
Definition corrected "offerred" to "offered"

ceterms:opeID
Definition corrected "somtimes" to "sometimes"

ceterms:recognizes
Definition corrected "judgement" to "judgment"

ceterms:renewal
Definition corrected "maintainance" to "maintenance"
Definition corrected "credential ." to "credential."

ceterms:renewedBy
Definition corrected "described" to "described."

ceterms:postReceiptMonths
Definition corrected "the the" to "the"

These changes have been made in the pending and current CTDL.

**Comment by mparsons1953** [comment]
ceterms:availableAt
Data Type corrected ceterms:GeoCoodinates to ceterms:GeoCoordinates

ceterms:region 
Data Type corrected ceterms:GeoCoodinates to ceterms:GeoCoordinates

**Comment by stuartasutton** [comment]
Can this issue on typos be closed?

**Comment by siuc-nate** [comment]
I would hold onto it for now - I just fixed some more:

ceterms:EarningsProfile
Definition corrected "An resource" to "A resource"

ceterms:VerificationServiceProfile
Definition corrected "An resource" to "A resource"

These changes hav ebeen made in the pending and current CTDL.

**Comment by siuc-nate** [comment]
Note: I will close this issue when we release.
