### ISSUE TITLE
Expand definition of VerificationServiceProfile and add Comment

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#283]
Change definition from:
An resource describing the means by which someone can verify whether a credential has been attained by a person.
to:
An resource describing the means by which someone can verify whether a credential has been attained.

Add comment:
Includes, but is not limited to, verification of issuance of quality assurance to organizations, learning opportunities, and assessments.

**Comment by siuc-nate** [comment]
These changes have been made to pending CTDL.

**Comment by stuartasutton** [comment]
Possible rephrasing of the comment?

> Includes, but is not limited to, verification of whether quality assurance credentials have been issued for organizations, learning opportunities, and assessments.

**Comment by siuc-nate** [comment]
Done.

Is there language we can use that is less cantankerous than "includes, but not limited to ..."?  Something like:
- "[some] examples include ..."
- "includes ..., etc."
- "such as ..."

**Comment by stuartasutton** [comment]
None are as explicit in saying that "the list includes these things but
don't you dare assume that this list is exclusive".
