### ISSUE TITLE
Alpha order of concepts in TOC

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#284]
I guess because concepts have different vocabulary prefixes, they are not in alphabetical order in their viewer [table of contents](http://credreg.net/ctdl/terms/subjectWebpage#vocabularyTerms). Can they be listed in the TOC in alpha order?

**Comment by siuc-nate** [comment]
I'm not sure which section(s) you're referring to exactly - The page table of contents and the term listing within a vocabulary are both in alphabetical order.  Do you mean the entire list of terms? I would think it would be better to keep them grouped by their relevant vocabulary.

**Comment by jkitchensSIUC** [comment]
Sort this TOC to be in alpha order http://credreg.net/ctdl/terms/subjectWebpage#vocabularyTerms

**Comment by siuc-nate** [comment]
This has been fixed.
