### ISSUE TITLE
Add ceterms:contactType

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#287]
We need to be able to identify the kind of contact with ceterms:ContactPoint. We need the following property added:

>**URI:** ceterms:contactType
**Label:** Contact Type
**Domain:** ContactPoint
**Range:** Literal
**Definitions:** The type of contact point.
**Comment:** Values such as "Registration", "Transcripts", "Verifications", and "Financial Assistance".

**Comment by siuc-nate** [comment]
This already exists in pending CTDL: http://credreg.net/ctdl/pending#ContactPoint
I recall it having come up before - was it not added until recently?

Also, we have another case of near-duplicate class and property in ceterms:ContactPoint and ceterms:contactPoint.  Should one or the other be renamed?

**Comment by mparsons1953** [comment]
Would there not be overlap between **ceterms:name** and **ceterms:contactType**? Schema.org uses contactType examples like customer service, and technical support. I could see the latter  (as well as Registration) being entered as the 'name' of the contact point. It would then be confusing to select a contactType (where would be the same as the name).

**Comment by mparsons1953** [comment]
re: vocabulary for contactType. 
There can probably be a very broad range of types. So would we avoid a controlled vocabulary?

**Comment by stuartasutton** [comment]
I think that name and contactType are very different. One asks for the type/category of the contact and the other the name of someone. E.G. contactType Registration", name "Jane Smith". Some contacts may have category and and phone but no name.

**Comment by stuartasutton** [comment]
I think a literal is OK because the range of contactTypes might be quite large.

**Comment by siuc-nate** [comment]
Closing this issue, unless there is anything further.
