### ISSUE TITLE
Direct reference to an existing course description

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#290]
We currently provide no clear means for linking an instance of LearningOpportunityProfile to an existing RDF description of a course that the profile describes such as a description created by a 3rd party using schema.org's pending `course`.  Not a `subjectWebpage` of the course; but, for example, a structured description created a university directly off their course catalog. 

We can reference a learning resource (`ceterms:learningResource`) but not a course. Perhaps this a place for use of [`ceterms:sameAs`] (http://credreg.net/ctdl/terms#sameAs) (i.e., adding `ceterms:LearningOpportunityProfile` as domain)?

**Comment by siuc-nate** [comment]
Solved by #303
