### ISSUE TITLE
Connection properties have incorrect(?) ranges

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#292]
http://credreg.net/ctdl/terms/advancedStandingFrom
http://credreg.net/ctdl/terms/isAdvancedStandingFor
http://credreg.net/ctdl/terms/isPreparationFor
http://credreg.net/ctdl/terms/preparationFrom
http://credreg.net/ctdl/terms/isRequiredFor
are all missing a range of ceterms:ConditionProfile and/or missing a range of ceterms:CredentialAlignmentObject.

http://credreg.net/ctdl/terms/requires
http://credreg.net/ctdl/terms/isRecommendedFor
http://credreg.net/ctdl/terms/recommends
appear to be okay.

All of the above (also) have a range of all Credential subclasses - I do not recall whether or not we decided to do that or if it is correct.

We added weight to ConditionProfile for the sake of the properties in the first set above; those properties no longer point to ConditionProfile. I believe this to be an error and cannot find anything that documents such a change.

However, it may also be an opportunity: In #134 we added weight to CredentialAlignmentObject.  Do we need to have the set of properties above point to ConditionProfile at all or would CredentialAlignmentObject be sufficient?

**Comment by stuartasutton** [comment]
Nate, the original range was the Credential subclasses...so that's correct. I'm not at all sure why ConditionProfile was not included. How do you see CredentialAlignmentObject being applicable as range?.

**Comment by siuc-nate** [comment]
My thinking is that because the only real reason we were using ConditionProfile for those is because we had the "weight" property in it, and because we later added weight to CredentialAlignmentObject, would it not be simpler to use CredentialAlignmentObject instead of ConditionProfile? CredentialAlignmentObject could still point to some target object (though ConditionProfile does have specific target properties, so maybe it's worth sticking with that).

Thoughts?

**Comment by siuc-nate** [comment]
Per our 1/31/2017 call:

We will add ceterms:ConditionProfile to the range of:
http://credreg.net/ctdl/terms/advancedStandingFrom
http://credreg.net/ctdl/terms/isAdvancedStandingFor
http://credreg.net/ctdl/terms/isPreparationFor
http://credreg.net/ctdl/terms/preparationFrom
http://credreg.net/ctdl/terms/isRequiredFor

This correction will occur in pending CTDL.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
