### ISSUE TITLE
Distinguishing a department from a suborganization

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#293]
@stuartasutton 
The CTDL has a property for a sub organization but not a department. Do we need to have this distinction?
Schema.org has a department. 
The current editor (I know this is not a driver) allows for adding a department or a sub organization. A use case would be to list the departments of an organization or to list the sub organizations/subsidiaries. This would not be possible if there is not a property that could be used to uniquely identify one or the other.

**Comment by stuartasutton** [comment]
No problem with adding department.

**Comment by stuartasutton** [comment]
**ACTION**

Add `department` from `schema:department`

**Comment by siuc-nate** [comment]
How's this:

ceterms:department
Label: Department
Definition: A relationship between an organization and a department of that organization, also described as an organization.
Usage Note: For example: a store with a pharmacy, or a bakery with a cafe.

**Comment by siuc-nate** [comment]
Revised:

ceterms:department
Label: Department
Status: vs:stable
Definition: The organization being referenced is a department of the organization being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Usage Note: (none)
Comment: (none)
Equivalent to: http://schema.org/department
Subproperty Of: (none)

**Comment by siuc-nate** [comment]
This has been added to pending CTDL.
