### ISSUE TITLE
Need a "submissionOf" property for required submissions

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#295]
We currently have nothing to identify required submissions (e.g., a transcript or a recommendation). E.g., notice the `submissionOf` in the following guide fig.2.2b:

![fig 2 2b](https://cloud.githubusercontent.com/assets/2939046/22354861/2efe6f9c-e3dc-11e6-8f7c-e0df0ab001d0.png)

Also note the `entryCondition` property--it does not exist either. I'd assume that `submissionOf' would have a domain of `ConditionProfile`. I think it should not hint of "required", however, since it could also be the result of a `recommends` pointing at a `ConditionProfile`

**Comment by siuc-nate** [comment]
Per our 1/31/2017 call:

Create in pending CTDL:
ceterms:submissionOf
Label: Submission Of
Definition: An artifact to be submitted.
Comment: Example artifacts may include transcripts, portfolios, or an affidavit.
Domain: ceterms:ConditionProfile
Range: xsd:Literal

**Comment by siuc-nate** [comment]
This has been done in pending CTDL and noted in history tracking.
