### ISSUE TITLE
Need an "entryCondition" like property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#296]
I think it would be useful to have an `entryCondition` property to distinguish prerequisite conditions from `requires` conditions necessary to earn the credential after entry. See Guide fig.2.2b:

![fig 2 2b](https://cloud.githubusercontent.com/assets/2939046/22355090/81584758-e3dd-11e6-8ceb-b36ef15bf2d2.png)

**Comment by siuc-nate** [comment]
Per our 1/31/2017 call:

Create 
ceterms:entryCondition
Label: Entry Condition
Definition: The prerequisites for entry into the resource being described.
Comment: Such requirements might include transcripts, previous experience, lower-level learning opportunities, etc.
Domain: ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
Range: ceterms:ConditionProfile
subpropertyOf: ceterms:requires

**Comment by siuc-nate** [comment]
This has been added to pending CTDL.
