### ISSUE TITLE
Add an alternativeCondition property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#297]
I suggest the addition of a new property for explicitly handling alternative conditions called `alternativeCondition`. We currently have `additionalCondition` defined as:

> "An additional set of conditions."

with a comment of:

> "In the context of requirements, select at least one of the conditions listed here to fulfill the parent conditions."

The normative definition for `alternativeCondition` simply defines "additions" and not "alternatives". The non-normative comment in essence states that the property does double-duty: (1) defines alternatives when the property is "requires"; and (2) a simple additions when the property is something else (e.g., `recommends`). This distinction in the comment is OK for humans and useless for machines. A machine needs to know whether a particular ConditionProfile is a simple addition or an alternative. So, since we have two different circumstances, we need explicit properties dealing with each.

The a new `alternativeCondition` should be declared as a sub-property of `additionalCondition` and defined somewhat like this:

> "A set of conditions in the context of requirements where more than one alternative set or path have been defined and from which any one path fulfills the parent conditions."

Perhaps the addition of a comment like the following:

> "Two or more sets of alternative conditions are not necessarily mutually exclusive paths; for example, a set of alternative concentrations for a degree may allow a person to optionally complete more than one concentration even though only one is required to earn the degree."

**Comment by siuc-nate** [comment]
Per our 1/31/2017 call, we will deprecate ceterms:additionalCondition and supersede it with ceterms:alternativeCondition, because alternativeCondition (better) serves the original purpose of additionalCondition.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL.

**Comment by siuc-nate** [comment]
Per our discussion on 2/10/2017:

Change:
ceterms:additionalCondition
Status: vs:unstable
Usage Note: The additionalCondition property should not be used where alternative conditions are being defined; use alternativeCondition instead.


Notes:
![image](https://cloud.githubusercontent.com/assets/21346519/22835129/50f7332a-ef7d-11e6-92ec-01179a8b8df6.png)
All 3 ConditionProfiles must still be satisfied in this scenario, which means that their contents could all be combined into one ConditionProfile - therefore additionalCondition is not necessary.

![image](https://cloud.githubusercontent.com/assets/21346519/22835164/72a4f8a4-ef7d-11e6-9b6d-196a3b012282.png)
By comparison, alternativeCondition defines an "either/or (allowing but not requiring both)" set of distinct pathways to fulfill a set of conditions. In the example above, the initial ConditionProfile may contain conditions common to both pathways or it may simply be a container that points to the pathway-specific conditions via alternativeCondition.

![image](https://cloud.githubusercontent.com/assets/21346519/22835342/f1559154-ef7d-11e6-9f3a-b07ddebaafb2.png)
In this example, the Credential requires _both_ of the initial ConditionProfiles, each of which has options (via additionalCondition) for fulfilling it.  Grouping in this manner indicates that at least _two_ of the rightmost ConditionProfiles must be met (one from each "branch" or initial ConditionProfile).

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL, and I have updated the history tracking note to reflect vs:unstable rather than vs:deprecated for the status of ceterms:additionalCondition.
