### ISSUE TITLE
Consider addition of property/ies to handle conferring a credential

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#298]
Surfacing a discussion between @stuartasutton, Eric, and myself.  

Firstly, from Eric:
-
I believe conferredBy is needed for the issued credential.  When an issuer asserts the credential, it needs to be conferred by the official institution.  Here is an example:

        "conferredBy": {"id": "https://issuer.truecred/o/purdue",
          "type": [ "CredentialOrganization","CollegeOrUniversity","Organization"],
          "alternativeIdentifier": "urn:FAFSA:001825",      
          "description" : "description of organization",
          "logo" : "url://images/..", 
          "naics": "611310",
          "ipedsId": "243780", 
          "fein": "35-6002041",
          "duns": "07-205-1394",
          "email": "registrar@school.edu"
          "subOrganization" {
            "name": "KRANNERT SCHOOL OF MANAGEMENT", 
            "url" : "url://school/url"
          }
        }

offeredBy doesn't work in our use case because a YMCA can offer a Red Cross swimming course, but the Red Cross would confer it after the student passed the course.

---
**Note: The previous "conferredBy" property was dropped because it was determined to be redundant with the use of the "offeredBy" property.**  

Stuart's response:
-
So, the "offers" property was intended to include both offering and conferring. Now, if that decision to conflate offer and confer was ill-advised and there are actual cases where an agent can offer but not confer (or vice versa), then we should reconsider (perhaps through two subproperties of the current "offers"--one for each context).

Eric's response:
-
Thanks for all the feedback.  Per above, I do believe the YMCA use case would be good example where the two are separate.  Another one would be, Microsoft and Cisco tech training, which is conferred by them, but also offer by many 2-year schools and professional training organizations.  I guess the big question is: Does Microsoft and Cisco provide the teaching institutions who offer these courses the right to "confer" them, or do they require reporting and final confirmation?  I would suspect that it depends if they are an "authorized" training partner or not.

Another example, would be proctored testing centers that offer Teaching or Nursing tests to acquire a credential/license/etc., but the credential is conferred by the State.

My response:
-
We need to be careful not to conflate the credentials with the learning opportunities that lead to them – one org might offer the learning opportunity while the other might offer the credential.  The second org may approve of (or perform some other kind of QA on/with) the org that offers the learning opportunity.  In other words, something like this:
![image](https://cloud.githubusercontent.com/assets/21346519/22430430/d1c54a44-e6d3-11e6-8d4a-adca640be871.png)

---

I believe that is where the discussion now stands.  If I've missed anything that needs to be added to the summary, let me know.

**Comment by stuartasutton** [comment]
Guys, I took Nate's figure and translated it into the abstract (graphical) grammar
used in the new Guide and appended here the concrete turtle and jsonld syntaxes.

I've fleshed it out with more detail.

![app_fig1](https://cloud.githubusercontent.com/assets/2939046/22433245/9416961e-e6cc-11e6-8c7a-aee6e3790d4b.png)

**Turtle**

```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix res: <http://example.org/resources/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

res:284893f7-4d24-47de-97b5-2c2fd445e7fb a ceterms:Certification ;
    ceterms:ctid "urn:ctid:284893f7-4d24-47de-97b5-2c2fd445e7fb" ;
    ceterms:name "MCSA: Office 365 Certification"@en-US ;
    ceterms:requires res:6912fe79-93d7-4706-bc04-aab06b7b7f5e ;
    ceterms:creator res:f4ddc96e-81bc-4194-aa64-a3150245e19eb ;
    ceterms:offeredBy res:f4ddc96e-81bc-4194-aa64-a3150245e19e .    
    
res:6912fe79-93d7-4706-bc04-aab06b7b7f5e a ceterms:ConditionProfile ;
    ceterms:targetLearningOpportunity res:b218da2a-dc28-44e8-9784-99db63a71700 .

res:b218da2a-dc28-44e8-9784-99db63a71700 a ceterms:LearningOpportunityProfile ;
    ceterms:name "Managing Office 365 Identities and Requirements"@en-US ;
    ceterms:offeredBy res:fb22b0e4-a1be-4329-bae5-a61e1c13adda ;
    ceterms:creator res:f4ddc96e-81bc-4194-aa64-a3150245e19e .
    
res:f4ddc96e-81bc-4194-aa64-a3150245e19eb a ceterms:CredentialingOrganization ;
    ceterms:name "Microsoft Corporation"@en-US ;
    ceterms:approves res:fb22b0e4-a1be-4329-bae5-a61e1c13adda ;
    ceterms:offers res:284893f7-4d24-47de-97b5-2c2fd445e7fb .
    
res:fb22b0e4-a1be-4329-bae5-a61e1c13adda a ceterms:CredentialingOrganization ;
    ceterms:name "IT Academy Inc."@en-US ;
    ceterms:offers res:b218da2a-dc28-44e8-9784-99db63a71700 .        
```

**JSONLD**
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "res": "http://example.org/resources/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "res:f4ddc96e-81bc-4194-aa64-a3150245e19eb",
      "@type": "ceterms:CredentialingOrganization",
      "ceterms:approves": {
        "@id": "res:fb22b0e4-a1be-4329-bae5-a61e1c13adda"
      },
      "ceterms:offers": {
        "@id": "res:284893f7-4d24-47de-97b5-2c2fd445e7fb"
      },
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Microsoft Corporation"
      }
    },
    {
      "@id": "res:fb22b0e4-a1be-4329-bae5-a61e1c13adda",
      "@type": "ceterms:CredentialingOrganization",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "IT Academy Inc."
      },
      "ceterms:offers": {
        "@id": "res:b218da2a-dc28-44e8-9784-99db63a71700"
      }
    },    
    {
      "@id": "res:6912fe79-93d7-4706-bc04-aab06b7b7f5e",
      "@type": "ceterms:ConditionProfile",
      "ceterms:targetLearningOpportunity": {
        "@id": "res:b218da2a-dc28-44e8-9784-99db63a71700"
      }
    },
    {
      "@id": "res:b218da2a-dc28-44e8-9784-99db63a71700",
      "@type": "ceterms:LearningOpportunityProfile",
      "ceterms:creator": {
        "@id": "res:f4ddc96e-81bc-4194-aa64-a3150245e19e"
      },
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Managing Office 365 Identities and Requirements"
      },
      "ceterms:offeredBy": {
        "@id": "res:fb22b0e4-a1be-4329-bae5-a61e1c13adda"
      }
    },
    {
      "@id": "res:284893f7-4d24-47de-97b5-2c2fd445e7fb",
      "@type": "ceterms:Certification",
      "ceterms:creator": {
        "@id": "res:f4ddc96e-81bc-4194-aa64-a3150245e19eb"
      },
      "ceterms:ctid": "urn:ctid:284893f7-4d24-47de-97b5-2c2fd445e7fb",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "MCSA: Office 365 Certification"
      },
      "ceterms:offeredBy": {
        "@id": "res:f4ddc96e-81bc-4194-aa64-a3150245e19e"
      },
      "ceterms:requires": {
        "@id": "res:6912fe79-93d7-4706-bc04-aab06b7b7f5e"
      }
    }    
  ]
}


```

**Comment by siuc-nate** [comment]
Until future notice, we will leave this as-is.  Should circumstances require, consider subclassing the current ceterms:offers/offeredBy to create two properties for offering and conferring a credential.
