### ISSUE TITLE
Add new purl for meta terms

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#299]
We have administration terms that we need to declare in a schema related to CTDL housekeeping. So we need a partial for `http://purl.org/ctdl/meta/`

E.g., `http://purl.org/ctdl/meta/TermHistory`

**Comment by stuartasutton** [comment]
Note that since these terms will show up in terms declarations, they need to be included in @context.

**Comment by jkitchensSIUC** [comment]
Make this PURL entry http://purl.org/ctdl/meta/ and direct the PURL to...

**Comment by siuc-nate** [comment]
I have created the purl and page; however, there is no content on it yet so I have not added it to the site menu.

**Comment by stuartasutton** [comment]
Good, we need to consider how to add it to site menu since we do not want any terms there to get confused with properties for describing a credential etc.
