### ISSUE TITLE
Subproperties of isSimilarTo are missing a range of ConditionProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#304]
http://credreg.net/Ctdl/terms/isSimilarTo
The subproperties here all have ranges of Credential, but not of ConditionProfile.  Per our usage of ConditionProfile with the preparationFor/advancedStandingFor/etc. properties, should we not use ConditionProfile to express the weight of the similarity?  Or is that well-enough defined by the properties themselves?

**Comment by siuc-nate** [comment]
Did we come to a decision on this?

**Comment by siuc-nate** [comment]
Note: ceterms:minorAlignment is also missing a subpropertyOf ceterms:isSimilarTo. I will correct this.

**Comment by siuc-nate** [comment]
I have made the changes in pending CTDL and updated the history tracking.

**Comment by stuartasutton** [comment]
Good...
