### ISSUE TITLE
Namespace table error (vs)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#308]
There is a namespace error in the table at the top of the [terms viewer](http://credreg.net/ctdl/terms)

The `vs` namespace is currently `https://www.w3.org/2003/06/sw-vocab-status/note` and it should be `https://www.w3.org/2003/06/sw-vocab-status/ns`

**Comment by siuc-nate** [comment]
This has been fixed.
