### ISSUE TITLE
Deprecate ceterms:learningOpportunityOffered

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#313]
I'm not sure where this one came from - but we already have a mechanism to express when an organization offers something (offers/offeredBy/offeredIn).  Having a "learningOpportunityOffered" property seems redundant (and there is no companion assessmentOffered property either).

**Comment by stuartasutton** [comment]
I don't know where `learningOpportunityOffered` came from and agree that we've already covered this territory with other properties. Perhaps it is something ancient that we've just missed.

**Comment by siuc-nate** [comment]
I have deprecated ceterms:learningOpportunityOffered and noted in the history tracking.
