### ISSUE TITLE
When to use "Preferred Label" and when to use "Label"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#316]
Recently, the table row "Label" was changed to "Preferred Label" for all types of terms (properties, classes, concept terms). That is not correct. The only type of term that should have "Preferred Label" is the concepts in our concept schemes (i.e., not properties and classes).

The reason is that SKOS for encoding concepts differentiates between "Preferred Label" (`prefLabel`) and a couple other label types (`altLabel` & `hiddenLabel`). The SKOS rule is that there can only be one `skos:prefLabel` per language, but there can be many for different languages, each with a single `prefLabel`. But there can be as many `altLabel` as there are alternatives. So, with our concepts (controlled vocabulary terms), there is a reason to use "Preferred Label". None of these factors apply with general classes or properties, Thus only "Label".

**Comment by siuc-nate** [comment]
This has been fixed.
