### ISSUE TITLE
Wrong serializations with ceterms:credentialingAction

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#318]
The property table for [`ceterms:credentialingAction`](http://credreg.net/ctdl/pending#CredentialingAction) has serializations to the super-class [`ceterms:CredentialingAction`](http://credreg.net/ctdl/pending#CredentialingAction) and not the property. appears to be the problem that class and property have the same lexical string distinguished only by upper/lower case initial letter. 

While they are considered different URI in RDF, they are not in the indexing here. We'll have to change one of them. However, longterm, case sensitivity is critical to RDF functionality.

If my diagnosis is correct, my suggestion is that we deprecate the **class** and declare a new one called `CredentialAction` with all the same properties.

**Comment by siuc-nate** [comment]
While I support being consistent in not using the same string for classes and properties, is this something that would be solved by fixing the metadata viewer/serializer not properly detecting capitalization (which is a fix that needs to be made regardless)?

**Comment by stuartasutton** [comment]
Yes, making the viewer/serializer case insentive would solve the problem.

**Comment by siuc-nate** [comment]
This should now be fixed.  In my testing, it appears to work.  Please let me know if you have any issues.
