### ISSUE TITLE
Differences in display between Firefox and Chrome

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#320]
@siuc-nate, **this is not an error, just an observation.** There is a difference between Firefox and Chrome in how the viewer term tables display where the list of values is long (e.g., listing all the credential subclasses). In Chrome, the long list is broken into two columns making it possible to get them onto a single screen while Firefox has a long single column. The Chrome behavior is the most appealing and useful. Again, not an error...

**Comment by siuc-nate** [comment]
This was due to an unusual bug in how firefox handles the column-count css property inside of a td tag.  It should now be fixed.
