### ISSUE TITLE
Determine whether to eliminate or refine ceterms:CredentialPerson (class) http://credreg.net/ctdl/pending#CredentialPerson

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#33]
Per (closed) issue #12, we now have two agent type vocabularies: (1) a mature OrganizationType, and (2) an undeveloped PersonType. This issue is to remind us that we need to develop at least an initial set of concepts for this PersonType concept scheme...other concepts can be added as they are identified.

**Comment by jkitchensSIUC** [comment]
@stuartasutton does this go on the unstable list? Do we need to address anything for this prior to Nov 17?

**Comment by siuc-nate** [comment]
Does defining a person stray into the territory of putting personal information into the registry? Is that something we want to do?

**Comment by jkitchensSIUC** [comment]
We marked this as unstable.  Need to review with Bob to either delete or form a group to review http://credreg.net/page/domainsviewer#CredentialPerson

**Comment by siuc-nate** [comment]
We should include this with our next TAC meeting.  We need to cover issues like:
- Should a person be able to do the same things that an organization should do?
- Can a person provide quality assurance?

**Comment by stuartasutton** [comment]
I'd also be very interested in a threshhold question of those who suggested
"Person" early on--what purpose do those who asked about adding Person see
in terms of use context.

**Comment by jkitchensSIUC** [comment]
This issue is replace with #324 to determine whether to eliminate or refine ceterms:CredentialPerson.  C
