### ISSUE TITLE
Change assessedBy to evaluatedBy

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#34]

**Comment by stuartasutton** [comment]
@jkitchensSIUC, I change assessedBy to evaluatedBy on the following classes:

> AssessmentProfile
> Credential
> CredentialOrganization
> CredentialPerson
> LearningOpportunityProfile

http://www.credreg.net/page/propertiesviewer#assessedBy

**IMPORTANT: See new issue #51** and comment
