### ISSUE TITLE
Defining Assessment Method and Modality for Assessment Profile

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#36]
E.g. formative and summative assessment. Two vocabularies.  

The method for issuing and completing the assessment.
Whether the assessment is formative or summative.

**Comment by stuartasutton** [comment]
@jkitchensSIUC, we currently have the following:

1. We have an AssessmentMethod vocabulary at https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0 ;
2. We have an assessmentMethodType property on AssessmentProfile that references the vocabulary (http://www.credreg.net/page/propertiesviewer#assessmentMethodType) ;
3. We ***did not*** have an AssessmentModality vocabulary, so I added one to the vocabulary spreadsheet and did **draft** concepts for "formative" and "summative" --all I see in my notes--(http://www.credreg.net/page/propertiesviewer#AssessmentModality) ; and
4. We ***did not*** have an assessmentModalityType property on AssessmentProfile, so I added one and did a **very drafty** definition that must be reviewed/refined. (http://www.credreg.net/page/propertiesviewer#assessmentModalityType)
