### ISSUE TITLE
Quality Assurance Usage

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#39]
How is the quality assurance (accreditation, endorsement, approval, licensure, recognition) used? (check all that apply) 
https://docs.google.com/document/d/144CetlzwrXUyaaC1j_6Nq-AWn7-TlBdxekxn8C3fAOQ/edit

**Comment by stuartasutton** [comment]
To satisfy this requirement, we have a ctdl:agentQualityAssurrancePurpose for use with both CredentialOrganization and CredentialPerson. It has a range of the enumeration AgentQAPurpose. See: 
-- http://www.credreg.net/page/propertiesviewer#agentQualityAssurancePurpose
-- http://www.credreg.net/page/propertiesviewer#AgentQAPurpose
Note that the (new) vocabulary is misnamed "QualityAssurancePurpose" in the vocabulary spreadsheet.
