### ISSUE TITLE
Delete ctdl:resourceURL

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#41]
I propose that we delete the property ctdl:resourceURL as unnecessary and an open invitation to spam and otherwise meaningless references to pages. The property is used solely on ConditionProfile and is defined as follows: "An additional resource relevant to the entity being described."

**Comment by mparsons1953** [comment]
Resource URL has been used on other profiles including: 

- learning opportunities
- assessments
- cost profile

I believe the rational was to allow the entry, of not use URLs, but also allowing entry of a title to allow providing a purpose of the URL

**Comment by stuartasutton** [comment]
Change the range of resousrceURL to THING so we can use things like name, url, description.

Change the domain to RevocationProfile, LearningOpportunityProfile, CostProfile and ConditionProfile.

**Comment by stuartasutton** [comment]
Per the discussion (Nate, Mike, Stuart--Jeanne at other meeting) on 2016-09-01 marathon call, we sync the use of ctdl:resourceURL to align the classes where it was being used in the cataloging tools with the CTDL. At the start of the conversation, the property was used only with ConditionProfile in the CTDL while used in the tool wit LearningOpportunityProfile, AssessmentProfile and CostProfile. There were tw decisions made:

1. Align the CTDL with the tool (i.e., add property as domain of the other classes; and
2. Add a usage note to try and constrain use to where the property is actually useful in order to cut down on the indiscriminate use of the property to point to their "favorite" pages (i.e. spam).

See http://www.credreg.net/page/propertiesviewer#resourceUrl
