### ISSUE TITLE
Scope Notes and Usage Guides Need to Show Crosswalks to Connecting Credentials and Other Vocabularies

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialTransparencyInitiative/vocabularies#43]
Ensure usage guides show crosswalks to Connecting Credentials and other common vocabularies.

**Comment by stuartasutton** [comment]
The properties needing clear usage guidance through notes are:

> requires
> recommends
> requiredFor
> recommendedFor
> hasPart
> isPartOf
> advancedStandingFor
> providesAdvancedStanding

Those notes would best include references to notions others have such as "embedded in" for "isPartOf" etc.

**Comment by stuartasutton** [comment]
Guidelines added (so far) for the following:
> http://www.credreg.net/page/propertiesviewer#hasPart
> http://www.credreg.net/page/propertiesviewer#isPartOf
> http://www.credreg.net/page/propertiesviewer#advancedStandingFor
