### ISSUE TITLE
Use of a profile name/title to indicate purpose of a profile

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#44]
Use of a profile name/title to indicate purpose of a profile - primarily where multiple are possible, and a clear title cannot be derived. 

some arbitrary examples include:
![image](https://cloud.githubusercontent.com/assets/16601156/18171446/a4111826-7027-11e6-8ae7-4d11c83666f2.png)

Cost Item Profile is probably an example where a separate profile name is not necessary, as long as there is a cost type.

**Comment by stuartasutton** [comment]
Add ctdl:name to ConditionProfile
