### ISSUE TITLE
Should general terms like Any/All be allowed, and how to publish when 'All' are selected

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/vocabularies#45]
We have several areas where the option of Any/All was added (perhaps arbitrarily).
Ex
![image](https://cloud.githubusercontent.com/assets/16601156/18171510/eb74e102-7027-11e6-8f4c-44c8331e0cf3.png)

The rationale for the use of these options is to remove the need to users to select every item. However, it also often assumed that the absence of any selections implies there are no restrictions - that is selecting all options can be treated the same as selecting none. 
**Options**:
Remove and make clear that if the current condition, cost, etc applies to all audiences, in this case, then select nothing.
If retaining Any/All, then the interface should be such that the Any/All is a radio button, so that when selected all other option are disabled
Alternately, if Any/All is selected, the system auto selects all other options
If any individual option is selected, then Any/All is unselected

**Publishing**
Regardless of the the approach taken, if all options were selected (or implied), should all options be published? Again will the absence of the all options make clear there are no restrictions, or should we be explicit?

**Comment by stuartasutton** [comment]
Discussed on call today (2016-09-01). I'm of the opinion that whether Any/All is used internally, if data is published to the wild, Any/All should not be present. The creator of the data either explicitly includes data for all intended or none.
