### ISSUE TITLE
Need to determine handling for mission objectives/purpose

### ISSUE THREAD

**Issue by CTITechPlanning** [CredentialTransparencyInitiative/vocabularies#5]
The QA document lists both an enumeration and a description (or perhaps a URL?) for this:
https://docs.google.com/document/d/13NxPR4l4iAuZ5IseRtSzfh61Jj3F6q15NMP2ToYjDhM/edit

Example data:
Main purpose of the QA body:
- Quality assurance
- Continuous quality improvement beyond minimum requirements
- Meeting a standard

Mission/objectives/purpose:
Our mission at Quality Credentials Inc. is to . . . . . . .
[VIEW LINK]

We need to determine:
1) Are these two separate fields (a text/url and an enumeration) or should they be merged?
2) Should this be recorded as text or a URL?

**Comment by stuartasutton** [comment]
Resolved with { missionAndGoalsStatement } on both agent classes (orgs. & people).
