### ISSUE TITLE
Develop a CTDL namespace policy

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#58]
Per the closed issue #17, we need to develop a CTDL _namespace policy_. While circumstances are somewhat different, a good model of such a policy is the [Dublin Core Namespace Policy](http://dublincore.org/documents/dcmi-namespace/).

**Comment by siuc-nate** [comment]
What is the best approach for determining this?

**Comment by stuartasutton** [comment]
Now that the PURL service is back up, we need to have a discussion and generate a documentation page that defines the CE policy. The DCMI document in conjunction with the PURL help page [1] is a good jumping off place for discussion since they touch on all (or almost all) of the key issues. 

[1] http://archive.org/services/purl/help

**Comment by stuartasutton** [comment]
I trust that there are a few "givens" for the CE namespace policy in order to align with good practice. E.g.

1. The invariable PURL for a term or a concept in a vocab always resolves to the latest version (I **really** prefer using "snapshot" to "version"...schema.org's "release" [1]) of the /vocab/ or /terms/ vocabulary encoding in RDF.
2. The PURLs themselves (as already established at [2]), contain no versioning information;
3. When a PURL is updated to point to a new snapshot, the underlying data for that snapshot is "frozen" (i.e., the spreadsheet & official representation on GitHub) and can only be edited based on strict criteria (e.g., typo, grammar error etc.), a systematic review and approval as set out in the namespace policy.
4. The PURL continues to resolve to the same snapshot as further modifications are made in a new working version (e.g., spreadsheet)--i.e.: (a) a set of frozen, date-stamped spreadsheets, and (b) a working spreadsheet where changes are being vetted and recorded. ***Or some similar syncing system that maintains an ongoing set of date-stamped (20160930) snapshots (e.g., 20160930) with the namespace PURL temporarily pointing to the most recent. A continuous linked chain of pointers point new snapshots to the previous snapshot...with PURL always pointing to the latest in that chain.
5. ...

This would mean that when we are ready to declare (and point people to) a snapshot/release as stable, we have:

 1. Frozen copy of previous release that we can point to by date stamp;
 2. A new working copy used for further development with enforced policies as to how changes are submitted, vetted, and recorded in the working copy; and
 3. Some form of snapshot/release document like [1] that sets out the changes made in each release.

Stuart

[1] http://schema.org/docs/releases.html
[2] http://archive.org/services/purl/domain/ctdl

**Comment by stuartasutton** [comment]
A couple of additional namespace policy matters 

 1. No change to a snapshot (stable version), can be made that "breaks" existing systems. Anything that even looks like it **might** break systems must be thoroughly discussed and community input sought.
 2. No release is announced before:
* Working spreadsheet copy (i.e., the new release) is frozen;
* Github version is updated to reflect to reflect the frozen spreadsheet; and 
* Release history is updated. 
* The upcoming release and changes are publicly announced and comments resolved.

This stuff is a fundamental to establishing and maintaining "trust".

**Comment by siuc-nate** [comment]
Refer to the PURL planning document:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#
