### ISSUE TITLE
Need to determine handling for QA policies and procedures

### ISSUE THREAD

**Issue by CTITechPlanning** [CredentialTransparencyInitiative/vocabularies#6]
Would these just be an extension of the Organization metadata?
https://docs.google.com/document/d/13NxPR4l4iAuZ5IseRtSzfh61Jj3F6q15NMP2ToYjDhM/edit

Example data:
POLICIES & PROCEDURES:
- View Conflicts of Interest policy and procedures
- View Complaint Process policy
- View Appeal Process policy

**Comment by stuartasutton** [comment]
For those of you that have looked at many orgs and credentials, is an organization likely to have different policies and procedures applicable to different credentials? If so, then a property for policiesAndProcedures on Credential would make more sense.

**Comment by stuartasutton** [comment]
Note that policies and procedures might also be relegated to the relevant credential profiles (e.g., policies & procedures around assessment seem like a likely candidate(s) for the AssessmentProfile.

**Comment by stuartasutton** [comment]
Solved with { policiesAndProcedures } property on the { ProcessProfile } class.
