### ISSUE TITLE
Add "requires" property to AssessmentProfile and LearningOpportunityProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#61]
This would point to a ConditionProfile and be used in the same way as it is with Credentials to indicate the requirements for taking an assessment or being eligible for a learning opportunities.

We also need to discuss whether or not this should apply to TaskProfile.

**Comment by stuartasutton** [comment]
Added:
http://www.credreg.net/page/propertiesviewer#requires
