### ISSUE TITLE
Enable concrete handling of indicating that an organization primarily operates online

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#64]
We need to be able to indicate in a concrete manner whether or not an organization primarily operates online.  All organizations have one or more physical addresses, and for our purposes, all of them have URLs.  

We need to be able to determine whether or not the address(es) are relevant to the user by being able to indicate that an organization functions primarily online.  

This may also present a need to indicate cases where an organization primarily operates offline as well (though perhaps this is implied by the lack of a primarily-online indication?)

Is it sufficient to add another vocabulary term to organization type to handle this (e.g., "primarilyOnline")? Or do we need another property?

**Comment by stuartasutton** [comment]
I think we should add a concept to the OrganizationType vocabulary for "Primarily Online". An organization can select more than one type so it can be, for example a "Training Provider" and "Primarily Online".

**Comment by stuartasutton** [comment]
ADDED:
https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/organizationType.ttl
