### ISSUE TITLE
Additional organization types

### ISSUE THREAD

**Issue by siuccwd** [CredentialTransparencyInitiative/vocabularies#7]
There are several organization types that we don't include in the vocab spreadsheet at: https://docs.google.com/spreadsheets/d/1Ovyb9_z7uJN02DZOahYiwxYGcmk2y1jvyApaA696VQ0/edit#gid=0

For example
**Affiliated Institution**	        
An institution that has an ongoing, functional relationship with the education institution in order to provide improved educational experiences to an individual and/or the school.
	
**Education Institution**	
A public or private institution, organization, or agency that provides instructional or support services to students or staff at any level.

**Education Organization Network**	
A self-organized membership network of peer-level educational organizations intended to provide shared services or collective procurement.

Should these be added to our list?

**Comment by stuartasutton** [comment]
After weekly tech call, it was determined these 'additional' vocabulary concepts had been, per Jeanne, eliminated in earlier deliberations.
