### ISSUE TITLE
Revocation Profile: drop "revocationType"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#71]
The revocationType property points to an enumeration with just two values (that I made up).  This information is better covered via the revocationCriteria (URL) property. I recommend we drop the revocationType property altogether.

**Comment by mparsons1953** [comment]
Nate, Jeanne, and Mike agree it is not necessary at this time.

**Comment by stuartasutton** [comment]
Done! ctdl:revocationType on ctdl:RevocationProfile deleted.
