### ISSUE TITLE
Credential Alignment Object: educationalFramework is insufficient

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#73]
Currently educationalFramework is used for the name of the framework (and potentially its URL?).  It would be clearer to have distinct properties for the two, e.g., "educationalFrameworkName" and "educationalFrameworkUrl"

**Comment by stuartasutton** [comment]
Since this is a credential alignment object, I see no reason not to change the "education" word to something that's more credential-like and map to the original in the schema. I.e., I'd prefer a ctdl:credentialFrameworkUrl...

**Comment by stuartasutton** [comment]
REVISIONS:

1. ***educationalFramework*** changed to ***credentialFramework*** with owl:equivalentProperty map to schema:educationalFramework (http://www.credreg.net/page/propertiesviewer#credentialFramework)
2. ***credentialFrameworkUrl*** added (http://www.credreg.net/page/domainsviewer#CredentialAlignmentObject)
3. Revised definition for ***credentialFramework*** to make it clear that the value is the name of the framework.

***Note: The Editor Mapping cell for credentialFrameworkUrl and credentialFramework are now  alert yellow.***
