### ISSUE TITLE
Change ctdl:Apprenticeship to ctdl:ApprenticeshipCertificate

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#76]
This will bring it in line with ctdl:MasterCertificate and ctdl:JourneymanCertificate.

Additionally, both of those properties reference "ctdl:ApprenticeshipCertificate" as their superclass.

**Comment by stuartasutton** [comment]
That's an error in the spreadsheet (I'll fix). It was supposed to be ApprenticeshipCredential but all columns of the declaration in the spreadsheet weren't updated.
