### ISSUE TITLE
organization identifier: FEIN vs Tax ID

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#77]
Schema.org has "taxID" as a property of Organization; we are currently not using this.  We are, however, using ctdl:fein for a similar purpose.

Do we need to add ctdl:taxID?

**Comment by mparsons1953** [comment]
see:
http://schema.org/taxID

**Comment by stuartasutton** [comment]
I see no reason to add it just because it exists without asking whether it plays a role particular to the our context.

**Comment by stuartasutton** [comment]
@jkitchensSIUC, what is the verdict here. Is there a functional reason to add a ctdl:taxID (owl:equivaentProperty schema:taxID)?

**Comment by siuc-nate** [comment]
It appears that FEIN is a subtype of TIN:
https://www.irs.gov/individuals/international-taxpayers/taxpayer-identification-numbers-tin

Therefore ctdl:fein would technically be a subproperty of schema:taxID. So we don't need to use taxID, since all we care about are FEIN numbers.
