### ISSUE TITLE
PURL domains for CTDL

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#78]
Establish the base PURLS agreed on for a Credential Engine PURL service account (http://archive.org/services/purl/):

> http://purl.org/ctdl/
> http://purl.org/cedl/

PURLs to: (1) terms (properties/classes), and (2) vocabularies (enumerations):

> http://purl.org/ctdl/terms/ (properties/classes)
> http://purl.org/ctdl/vocabs/ (enumerations)

See help: http://archive.org/services/purl/help; **_you may need personal help**_. These two PURLS are fundamentally like the Dublin Core example used in the PURL service help documentation for "/dc/terms/"...

**Comment by siuc-nate** [comment]
We have created the two purls and setup the CTDL redirects.  Currently the redirects aren't working, but we will check again after some time has passed.

**Comment by siuc-nate** [comment]
Refer to the PURL planning document:
https://docs.google.com/document/d/19HPCUKQFZJnlLhTPqxkb3NUJwww9yujQUS0ssv-4Jd8/edit#

**Comment by mparsons1953** [comment]
Merged with issue 147 as covered there
https://github.com/CredentialTransparencyInitiative/vocabularies/issues/147
