### ISSUE TITLE
Need page anchors in propoerty viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#8]
The viewer for the alphabetical listing of properties and classes (http://www.credreg.net/page/propertiesviewer) needs page anchors throughout that link from the table for each property or class to the relevant table of contents (TOC) that precede each section (properties, classes, enumeration classes). The current scrolling mechanism for moving up from the tables to the TOC for each section does not work effectively and neither does the browser-back for a tech person needing to bounce back-and-forth between TOC and a number of tables. In other words, some small icon or text at the bottom of each table should link back to the relevant TOC.

**Comment by siuc-nate** [comment]
This is now fixed.

**Comment by stuartasutton** [comment]
I have re-opened this old issue because I find working with the browsers (old or new) difficult for any extended period of time that requires moving from table-to-Index. Scrolling up with the browsers built-in slider is no substitute for a tiny page anchor (in lower right of each table?) that takes you instantly back to the "Shortcuts" -- something as simple as an up arrow:

![arrow-blue-rounded-up](https://cloud.githubusercontent.com/assets/2939046/20388061/fbfbcd56-ac77-11e6-8937-1f7e3a71e2b9.jpg)

**Comment by siuc-nate** [comment]
Alleviating this was the purpose of both the Jump To menu:
![image](https://cloud.githubusercontent.com/assets/21346519/20396290/54895438-acab-11e6-8bfa-ec4903ab67a6.png)

as well as part of the inspiration for the Find bar - both are intended to avoid needing to scroll and browse manually.

I suppose I could add an arrow button in, it would be redundant but also more visually/immediately obvious. I'll look into it.
