### ISSUE TITLE
Roles: provider vs offeredBy

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#81]
Is there a sufficient difference between "provider" and "offeredBy" as used in a few places to maintain both properties?  They seem to indicate the same kind of role.

**Comment by stuartasutton** [comment]
Agreed...we can use offeredBy and do an owl:equivalentProperty to schema:provider. Sound like a plan?

**Comment by stuartasutton** [comment]
Can't say off the top of my head...low likelihood...a pass through the property list with that notion in mind would be a good idea.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

 1. All instances of the property ctdl:provider changed to ctdl:offeredBy; and
 2. All instances of ctdl:offeredBy assert an owl:equivalentProperty of schema:provider.
