### ISSUE TITLE
Organization: QualityAssuranceTargetType should be an enumeration

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#83]
The Organization's QualityAssuranceTargetType currently points to a top-level profile (i.e. credential, assessment, etc).  The intent of this field, as I understand it, is to indicate the types of entities that the described organization performs quality assurance on - as such, it seems it would make sense to have the range of this property be an enumeration of various types rather than pointing to actual instances of those types.

**Comment by stuartasutton** [comment]
Nate, it doesn't point to an instance, it points to a class. So the class of things accredited are Credentials etc.

**Comment by stuartasutton** [comment]
Can we close this?

**Comment by siuc-nate** [comment]
As long as that means our enumeration has values like "credential", "assessment", etc., then yes, that resolves the issue.

**Comment by stuartasutton** [comment]
Nate, we aren't communicating. It does not point to an enumeration--a finite set of concepts. It points to classes of things that can be accredited. So an organization could have a assurance type of BachelorDegree, OpenBadge etc. In essence the target types are what's listed in the types viewer [1] + Assessments and Agents over which quality assurance is exercised.

[1] http://www.credreg.net/Page/typeslist
