### ISSUE TITLE
Proposed Vocabulary Rework: Assessment and Learning Opportunity

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#84]
In examining the vocabularies for assessment and learning opportunity recently, we came across several items that seemed loosely placed, duplicitous, and/or unnecessary, between the various vocabularies for enumerations within assessment and learning opportunity.

To try to smooth this out, I have combined all of the vocabularies from those (i.e. the "type", "delivery", and "mode" categories) and redistributed the values.  Attached is an image that represents a rough first draft of this - I welcome comments and suggestions.  The center column has all of the values; the columns to its immediate left and right represent all values potentially relevant to a given profile, and the subsequent columns represent actual enumerations.

One of the things I wanted to do was try to unify the delivery vocabularies into a single vocabulary, DeliveryType, that could potentially be applied in other places as well.  I arrived at this by trying to determine which values meant "how [entity] comes to you" vs "how you come to [entity]" (the latter being more of an "attendanceType" if anything).

I am also trying to stay away from generic unqualified "Type" enumerations (e.g., "[ProfileName]Type"), as "type" is too often loosely defined for any one enumeration to be able to define every potential "type" aspect of a given profile.

Note that items marked in red in the center column were dropped, since they are either marked as "do not include" in the vocabulary spreadsheet or are duplicitous between sources.

![vocabulary reworking](https://cloud.githubusercontent.com/assets/21346519/18972783/2d80266c-8660-11e6-93b7-6dae9fd634f7.PNG)

**Comment by siuc-nate** [comment]
After reexamining the two method enumerations above, I decided to run through a similar process as I described above to see what properties they had in common.  Out of that came the attached diagram.  I did have to sort of give up on wanting to avoid generic [ProfileName]Type enumerations, but in return for that, I was able to create a substantial shared enumeration, "MethodType".

Now AssessmentType and LearningType more purely relate to their associated profiles.

Again, I welcome thoughts on this:
![vocabulary reworking v2](https://cloud.githubusercontent.com/assets/21346519/18973398/e3df6d80-8662-11e6-8e23-4d1e35553456.PNG)

**Comment by stuartasutton** [comment]
Nate, can you sum this up in up in a bulleted list of changes (and new stuff).

**Comment by siuc-nate** [comment]
That is the intent of the image attached to my previous post - did it not display for you?

Also, this is still just a proposal; nobody has yet reviewed or agreed/disagreed with it. I'd like to make sure we're all happy with it first.

**Comment by stuartasutton** [comment]
Technically, I see no problem.  But we probably need @jkitchensSIUC to chime in. It would nevertheless be good to see a bulleted list of exactly what changes are entailed.

**Comment by stuartasutton** [comment]
OK, so I can assume: 
1. what's in red are to be deleted; and
2. We now have 4 vocabularies:
* AssessmentType
* DeliveryType
* LearningType
* SkillExpressionType

And, do we have any properties that are to have SkillExpressionType in range?

Also, I want to look carefully at the enumeration class names in relation to the properties that address them and avoid "Type" in the class names **where possible** and retain "Type" in the property names.

**Comment by siuc-nate** [comment]
Correct, and since skillExpressionType would be a new enumeration, currently nothing points to it - but properties on assessment and learning opportunity would.

I have not yet received feedback from the rest of the team though - perhaps we should discuss this on our weekly call?

**Comment by stuartasutton** [comment]
Makes sense...

**Comment by siuc-nate** [comment]
We have reviewed and updated the proposal:

![vocabulary reworking v3](https://cloud.githubusercontent.com/assets/21346519/19291164/1b575b86-8fd9-11e6-9fea-e919313cce68.PNG)

**Comment by siuc-nate** [comment]
Note: per issue #133 we need to also include "apprenticeship" as a LearningType vocabulary item.

**Comment by stuartasutton** [comment]
OK, here is my take away--there is a:

> 1. Single LearningType vocabulary (+ Apprenticeship);
> 2. Single AssessmentType vocabulary;
> 3. Single SkillExpressionType vocabulary; and
> 4. Single DeliveryType vocabulary.

@siuc-nate, what the diagram does **does not do** is tell us which vocabularies have been affected. Please be more specific than "type", "delivery", and "mode" categories" by referencing their vocabulary class name in the [Vocabularies Spreadsheet] (https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0). That will facilitate changes.

**Comment by siuc-nate** [comment]
Correct on all four.

Those 4 vocabularies would completely replace these existing vocabularies:
- AssessmentDelivery
- AssessmentMethod
- AssessmentMode
- LearningDelivery
- LearningSchedule

The affected properties are:
- AssessmentProfile: assessmentDeliveryType
- AssessmentProfile: assessmentMethodType 
- AssessmentProfile: assessmentModeType 
- LearningOpportunityProfile: learningDeliveryType
- There does not appear to be a LearningOpportunityProfile property for "Learning Schedule"
- CostProfile: ScheduleType (see note)

**Note:** I have found out why the LearningSchedule vocabulary has (had?) a "wholeCourse" term - we use it with CostProfile as a means of indicating which type of schedule a given cost applies to (e.g., the cost for the "whole course") - we do not use it anywhere with assessments or learning opportunities.

The terms for learning schedule (including independentStudy) would be useful in the context of CostProfile as described above - and one could make the argument that "wholeCourse" could apply to learning opportunities that can effectively be completed in one sitting (or to which the notion of full/part time does not really apply - e.g., a one week training course with one hour sessions each day). 

That's perhaps a bit of a stretch, but it would make sense to have the CostProfile schedule vocabulary be the same one used when describing learning opportunities, so that a given CostProfile can align 100% with a given learning opportunity in terms of the description of schedule.

So, in that case, I propose "wholeCourse" (or some term that means the same thing but doesn't include the word "course" if we want to open that can of worms) be reinstated as a member of the proposed LearningType vocabulary.

**Comment by siuc-nate** [comment]
Given our discussion on tuesday, in which:
- We were unable to find a suitable definition for wholeCourse in the context of schedule type
- We were unable to justify it as a member of the cost type vocabulary (costs are implicitly for the entire thing - course or otherwise - especially if no other type is selected)
- We decided that "fullTime" and "partTime" are actually descriptions of the _audience_ rather than the learning opportunity, and thus belong in our Audience vocabulary

I have updated the diagram.  In the course of this process, I noticed that "LearningType" was reduced to just two properties: "selfPaced" and "independentStudy".  Both of these could also be considered "delivery types" (just as "blendedLearning" and "correspondence" already were), so I moved them to the DeliveryType vocabulary and eliminated the LearningType vocabulary altogether.

This results in a significant change to the diagram:
![vocabulary reworking v4](https://cloud.githubusercontent.com/assets/21346519/19821165/94024a0e-9d22-11e6-8982-54bb17de9daf.PNG)

@stuartasutton @jkitchensSIUC @bobgsheets please review this so we can finalize it.

Thanks.

**Comment by stuartasutton** [comment]
**ACTION TAKEN:**

I went ahead and made this last round of changes assuming Bob's approval including the removal of the LearningType vocabulary after moving the selfPaced and independentStudy properties.

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate @CTITechPlanning The draft potential re-work of types of assessment is documented in this Google Drive folder https://docs.google.com/document/d/1GboWMcGrhdFQUEadEJtYKBxzTcYrwLcd5Rf5NKtc1qc/edit?usp=sharing 

The Google Doc with draft definitions for: Exam, Performance and Creative Work is here https://docs.google.com/document/d/1GboWMcGrhdFQUEadEJtYKBxzTcYrwLcd5Rf5NKtc1qc/edit?usp=sharing

**Comment by siuc-nate** [comment]
Updates are being/have been made here:
https://docs.google.com/document/d/1GboWMcGrhdFQUEadEJtYKBxzTcYrwLcd5Rf5NKtc1qc/edit

**Comment by jkitchensSIUC** [comment]
Issue #104 includes the Learning Opp issues.  Aren't the only ope items some of the Assessment Profile vocabs that are under review now?

**Comment by siuc-nate** [comment]
Yes, I believe this issue is/was covered by the various updates to assessments and learning opportunities for their vocabularies.
