### ISSUE TITLE
AgentSector: add Professional Association

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#85]
Per Bob's note (moved from spreadsheet to here):
Also need Professional Association defined as membership organization primarily engaged in promoting the interests of a particular profession, the interests of individuals engaged in that profession, and providing them with services that may involve the provision of education and credentialing services.

**Comment by stuartasutton** [comment]
***ACTION TAKEN***

ProfessionalAssociation added to spreadsheet for agentSector.ttl vocabulary and and agentSector.ttl updated on Github [1]

Stuart

[1] https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/agentSector.ttl
