### ISSUE TITLE
Assessment Mode: add diagnostic

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#86]
Per Bob's note on the spreadsheet, we need assessment modes of "formative", "summative", and "diagnostic".  We have the first two already.

**Comment by stuartasutton** [comment]
ACTION TAKEN:

Concept diagnostic added to assessmentModality.ttl vocabulary with the definition of:

>"An assessment before beginning a learning activity to determine a learner's prior knowledge and misconceptions."
