### ISSUE TITLE
LearningDelivery and LearningSchedule: remove values marked "Do not Include"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#88]
LearningDelivery: earlyCollege
LearningSchedule: wholeCourse

**Comment by stuartasutton** [comment]
***ACTIONS TAKEN:***

* Concept of *earlyCollege* removed from LearningDelivery vocabulary (https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/learningDelivery.ttl).
*  Concept of *wholeCourse* removed from LearningSchedule vocabulary (https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/learningSchedule.ttl)
