### ISSUE TITLE
EducationLevel: add definitions

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#89]
https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0
Rows 75-79

**Comment by stuartasutton** [comment]
Someone else needs to provide definitions, I have "view only" for the vocabs spreadsheet.

**Comment by siuc-nate** [comment]
I added you to edit access - it's strange that it didn't inherit that from the folder to begin with

**Comment by stuartasutton** [comment]
I have added **draft** definitions for all but have a question about "highSchoolOrEquivalent". Should this be "secondarySchoolOrEquivalent" to pass the international smell test?

**NO action taken to update github until the draft definitions are reviewed and approval signaled.**

**Comment by jkitchensSIUC** [comment]
I agree it should be secondary and the definition can state High School. @bobsheets please comment.

**Comment by siuc-nate** [comment]
We updated this to be "secondarySchoolOrEquivalent" and added a scope note referencing high school
