### ISSUE TITLE
Organization Type: Update postsecondary definition

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#90]
https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0

Row #119, Postsecondary Educational Institution. Bob added this note saying that the definition needs to be updated:
"This excludes adult basic education but we have community colleges doing that function. This IPEDS definition needs to be updated."

Current Definition:
An organization such as a college or university: (1) whose sole purpose is to provide postsecondary education defined as the provision of a formal instructional program whose curriculum is designed primarily for students who are beyond the compulsory age for high school and (2) has the authority to award degrees. This includes programs whose purpose is academic, vocational, and continuing professional education (IPEDS).

**Comment by stuartasutton** [comment]
Can we not include "iPeds" in the text of the definition. It belongs in
source.

**Comment by stuartasutton** [comment]
I am having difficulty seeing how this "excludes adult basic education" and as a result have no means to modify the definition. Is it the word "degree"? What? There's these criteria:

1. It's college or university (community college fits);
2. provides postsecondary education (maybe add "***basic*** and postsecondary education"??);
3. formal instruction;
4. "primarily" beyond compulsory age for high school (should be secondary school...Euopeans no clue of "high school");
5. Awards degrees (perhaps expand degrees to include certificates etc.)
6. Academic, vocational, and continuing professional education programs (add basic education?)

**Comment by jkitchensSIUC** [comment]
Ipeds should not be in the definition only the scope notes.  @bobgsheets needs to clarify so we can close this out.

**Comment by siuc-nate** [comment]
We reviewed this today and moved the reference to IPEDS from the definition to a scope note.
