### ISSUE TITLE
ConditionProfile: Minimum Age - update definition

### ISSUE THREAD

**Issue by siuc-nate** [CredentialTransparencyInitiative/vocabularies#91]
Now that condition profile is used with assessments and learning opportunities, the definition of minimum age (which refers to credentials) is no longer accurate.

**Comment by stuartasutton** [comment]
***Action Taken:***

Definition changed from 
>"The minimum allowed age (in years) at which a person is eligible for the credential."

to
> "The minimum allowed age (in years) at which a person is eligible for the resource."
