### ISSUE TITLE
Deleting AudienceLevel / adding EducationLevel

### ISSUE THREAD

**Issue by stuartasutton** [CredentialTransparencyInitiative/vocabularies#99]
Just to make sure I don't mess up since I was not privy to the conversation that led to the following changes... 

In github, we have a vocabulary for Audience Level at [1]. As far as I can tell, this vocabulary was deleted by Mike from the vocabulary spreadsheet and Education Level added (see [2] at lines 76-80) on September 27. 

***Is this correct?*** If so, I'll: 

 1. go ahead and deprecate the AudienceLevel vocabulary by moving it to the GitHub Deprecated folder, and 
 2. add the Education Level vocabulary with new draft definitions.

Also, please verify that the uses of the new Education Level vocabulary are accurate:

> Credential==typicallyAudienceLevelType==>EducationLevel
> ConditionProfile==educationLevel==>EducationLevel

 1. Shouldn't educationLevel be educationLevelType; and
 2. Are both typicallyAudienceLevelType and educationLevel{Type} necessary?

Stuart

[1] https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/audienceLevel.ttl
[2] https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0

**Comment by jkitchensSIUC** [comment]
Back when we did the 2-day CTDL deep dive, we all had agreed to use Education Level and Years of Experience as the two pieces of data necessary to identify the intended level of a credential in combination with years of experience.  Bob had asked that we use Education Level.  If it's consistent with all of the other Types, that could be appended to the label.  From what I understand, we only need one or the other and Education Level was determined to be the better choice.

**Comment by stuartasutton** [comment]
OK, I *think* I have it:

1. Deprecate the AudienceLevel vocabulary in [GitHub](https://github.com/CredentialTransparencyInitiative/vocabularies/blob/master/audienceLevel.ttl) (i.e. move to deprecated folder); 
2. Add new EducationLevel vocabulary to GitHub from vocabulary spreadsheet (***definitions approved?***);
3. Change educationLevel property to educationLevelType.

Correct?

**Comment by siuc-nate** [comment]
Item 3 above is done, but we're leaving this open for Stuart to take care of the GitHub updates.

**Comment by stuartasutton** [comment]
**GITHUB ACTIONS TAKEN:**

* AudienceLevel moved to deprecated folder;
* EducationLevel added.
